Repository foundryvtt/dnd5e, pull requests merged in 2022-09, with the labels that each got.

#1773 Fix CSS build target
  CONTRIBUTING.md
  package.json
Labels: bug

#1785 [#1784] Fix icon migrations with leading slash & fix renamed core icons
  json/spell-icon-migration.json
  module/migration.mjs
Labels: bug

#1786 [#1779] Fix issue with d20 rolls failing when they include min() or max()
  module/dice/d20-roll.mjs
Labels: bug, dice

#1791 [#1790] Fix infinite loop bug with custom skills on new actors
  module/documents/actor/actor.mjs
Labels: bug

#1799 [#1625] Fix target count of Acid Splash
  packs/spells.db
  packs/src/spells/cantrip/acid-splash.json
Labels: compendium content

#1792 [#1769] Fix hit dice subtracting health with negative con mod, rework rollHitDie to use base Roll rather than DamageRoll
  module/documents/actor/actor.mjs
Labels: bug, breaking

#1747 [#1707] Display max uses formula warnings on sheet
  dnd5e.css
  lang/en.json
  less/apps.less
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  templates/actors/parts/actor-warnings.hbs
Labels: ui

#1815 [#1809] Convert chapter & appendix data in rules compendium into flags
  module/applications/srd-compendium.mjs
  packs/rules.db
  packs/src/rules/appendix-a-conditions.json
  packs/src/rules/appendix-b-gods-and-the-multiverse.json
  packs/src/rules/appendix-c-creatures.json
  packs/src/rules/appendix-d-senses-and-speeds.json
  packs/src/rules/chapter-1-beyond-1st-level.json
  packs/src/rules/chapter-10-spellcasting.json
  packs/src/rules/chapter-11-dm-tools.json
  packs/src/rules/chapter-2-races.json
  packs/src/rules/chapter-3-classes.json
  packs/src/rules/chapter-4-personality-and-background.json
  packs/src/rules/chapter-5-equipment.json
  packs/src/rules/chapter-6-customization-options.json
  packs/src/rules/chapter-7-using-ability-scores.json
  packs/src/rules/chapter-8-adventuring.json
  packs/src/rules/chapter-9-combat.json
  packs/src/rules/disclaimer.json
  packs/src/rules/magic-items-a-z.json
  packs/src/rules/spells-a-z.json
Labels: compendium content, localization

#1803 [#1581] Add d4 hit die denomination
  module/config.mjs
Labels: feature request

#1766 Allow drag and drop of effects on items
  module/applications/item/item-sheet.mjs
Labels: ux, active effects
