Repository foundryvtt/dnd5e, pull requests merged in 2022-08, with the labels that each got.

#1671 [#1002] Add hooks to `Item5e` rolling methods
  module/documents/item.mjs
Labels: api

#1662 [#1002, #1543, #1677] Add hooks to `Item5e#roll` & `Item5e#displayCard` to allow modules to enhance that workflow
  module/applications/actor/base-sheet.mjs
  module/canvas/ability-template.mjs
  module/documents/item.mjs
  module/documents/macro.mjs
  templates/apps/ability-use.hbs
Labels: api

#1608 [#1607] avoid setting NPC weapon proficiency/equipped if already set
  module/documents/item.mjs
Labels: bug

#1676 [#1675] Add UUID to `Advancement` & make work with `fromUuid` & `fromUuidSync`
  module/advancement/advancement.mjs
  module/advancement/types/item-grant.mjs
  module/documents/item.mjs
Labels: api

#1597 [#1470] Allow migration version to be set via world manifest flag
  dnd5e.mjs
Labels: bug, api

#1659 [#1140] Fix rolling criticals when number of dice is a formula
  module/dice/damage-roll.mjs
Labels: dice

#1704 Fix issue with argument parsing in gulp scripts
  utils/javascript.mjs
  utils/packs.mjs
Labels: bug

#1619 Fix number of Telepathic Bond targets
  packs/spells.db
  packs/src/spells/level-5/telepathic-bond.json
Labels: compendium content

#1708 [#1698] Fix rollDeathSave not respecting roll mode when roll is fast forwarded
  module/dice/dice.mjs
Labels: bug, dice

#1710 [#1532] Displaying toolType in tool sheet header
  templates/items/tool.hbs
Labels: ui

#1723 Switch actor and item sheets over to using the ProseMirror editor.
  templates/actors/character-sheet.hbs
  templates/items/parts/item-description.hbs
Labels: api

#1725 [#1713] Fix price and weight herbalism kit
  packs/items.db
  packs/src/items/tool/herbalism-kit.json
Labels: compendium content

#1739 Update migration scripts to migrate effect icons
  module/migration.mjs
Labels: api

#1742 [#1741] Fix ability consumption display in item sheets
  module/applications/item/item-sheet.mjs
Labels: bug, ui

#1744 [#1743] Fix stealth input having a value
  module/documents/item.mjs
  templates/items/equipment.hbs
Labels: bug

#1706 Add support for "Space Vehicle" tool proficiencies
  lang/en.json
  module/config.mjs
Labels: feature request

#1582 [#1314, #1395] Allow skills to be customized by modules
  dnd5e.css
  less/actors.less
  module/applications/actor/base-sheet.mjs
  module/applications/actor/skill-config.mjs
  module/config.mjs
  module/documents/actor/actor.mjs
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet.hbs
  templates/apps/skill-config.hbs
Labels: api

#1709 Improve gulp logging
  package-lock.json
  package.json
  utils/packs.mjs
Labels: compendium content

#1752 Fix deprecation warnings with skill lists on class sheet
  module/applications/item/item-sheet.mjs
  module/applications/trait-selector.mjs
  templates/items/class.hbs
Labels: bug

#1614 [#1610] Apply temp HP from context menu on dice rolls
  lang/en.json
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
Labels: ux
