Repository foundryvtt/dnd5e, pull requests merged in 2022-12, with the labels that each got.

#1939 [#1835] Create system data models for equipment
  lang/en.json
  module/data/item/_module.mjs
  module/data/item/equipment.mjs
  module/migration.mjs
Labels: api

#1688 [#1505, #1684, #1686, #1687] Improve scale value advancement with better formatting & conversion
  lang/en.json
  module/advancement/advancement-config.mjs
  module/advancement/types/scale-value.mjs
  module/data/advancement/_module.mjs
  module/data/advancement/scale-value.mjs
  module/documents/item.mjs
  packs/classes.db
  packs/src/classes/cleric.json
  packs/src/classes/druid.json
  templates/advancement/scale-value-config.hbs
  templates/advancement/scale-value-flow.hbs
Labels: advancement

#1954 [#1835] Create system data model for tools
  module/data/item/_module.mjs
  module/data/item/tool.mjs
Labels: api

#1905 [#1835] Create system data model for consumables
  module/data/abstract.mjs
  module/data/item/_module.mjs
  module/data/item/consumable.mjs
  module/data/item/templates/activated-effect.mjs
Labels: api

#1953 [#1835] Create system data model for containers (aka backpacks)
  lang/en.json
  module/data/_module.mjs
  module/data/actor/group.mjs
  module/data/item/_module.mjs
  module/data/item/container.mjs
  module/data/item/templates/action.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/templates/item-description.mjs
  module/data/item/templates/mountable.mjs
  module/data/item/templates/physical-item.mjs
  module/data/shared/_module.mjs
  module/data/shared/currency.mjs
Labels: api

#1980 Determine ActiveEffect suppression on all actor types
  module/documents/active-effect.mjs
Labels: bug, active effects

#1986 [#1983] Allow class to be level 0 to prevent advancement issue
  module/data/item/class.mjs
Labels: bug

#1829 Use RAW GP as standard for currency conversions
  module/config.mjs
  module/documents/actor/actor.mjs
Labels: feature request, api

#1826 Remove classes & methods deprecated since 1.6
  lang/en.json
  module/advancement/class-features.mjs
  module/applications/_module.mjs
  module/applications/select-items-prompt.mjs
  module/config.mjs
  module/documents/actor/actor.mjs
Labels: api

#1988 Add grouping back to item target type
  templates/items/parts/item-activation.hbs
Labels: ui

#1770 [#1348] Add feature type & subtype to `feat` items
  dnd5e.css
  lang/en.json
  less/items.less
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/item/feat.mjs
  module/utils.mjs
  template.json
  templates/items/feat.hbs
Labels: feature request

#1877 Add ability score selection to the skills configuration.
  templates/apps/skill-config.hbs
Labels: feature request

#1987 [#1929] Reorganize advancement file structure to match other documents & applications
  dnd5e.mjs
  module/advancement/_module.mjs
  module/advancement/types/_module.mjs
  module/applications/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/advancement/_module.mjs
  module/applications/advancement/advancement-config.mjs
  module/applications/advancement/advancement-confirmation-dialog.mjs
  module/applications/advancement/advancement-flow.mjs
  module/applications/advancement/advancement-manager.mjs
  module/applications/advancement/advancement-selection.mjs
  module/applications/advancement/hit-points-config.mjs
  module/applications/advancement/hit-points-flow.mjs
  module/applications/advancement/item-grant-config.mjs
  module/applications/advancement/item-grant-flow.mjs
  module/applications/advancement/scale-value-config.mjs
  module/applications/advancement/scale-value-flow.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/documents/_module.mjs
  module/documents/advancement/_module.mjs
  module/documents/advancement/advancement.mjs
  module/documents/advancement/hit-points.mjs
  module/documents/advancement/item-grant.mjs
  module/documents/advancement/scale-value.mjs
  module/documents/item.mjs
Labels: breaking, advancement

#1992 [#1835] Move equipped and atunement to seperate template
  module/data/item/_module.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/templates/physical-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
Labels: api

#1994 Support an initiative roll configuration Dialog for characters
  dnd5e.mjs
  lang/en.json
  module/applications/actor/character-sheet.mjs
  module/documents/actor/actor.mjs
  module/documents/combat.mjs
Labels: ux, dice

#1990 [#1835] Create system data models for actors
  dnd5e.mjs
  lang/en.json
  module/data/abstract.mjs
  module/data/actor/_module.mjs
  module/data/actor/character.mjs
  module/data/actor/group.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/templates/common.mjs
  module/data/actor/templates/creature.mjs
  module/data/actor/templates/details.mjs
  module/data/actor/templates/traits.mjs
  module/data/actor/vehicle.mjs
  module/data/fields.mjs
  module/data/item/class.mjs
  module/data/item/equipment.mjs
  module/data/item/spell.mjs
  module/data/item/templates/action.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/templates/physical-item.mjs
  module/data/item/weapon.mjs
  module/documents/actor/actor.mjs
  module/migration.mjs
  template.json
Labels: api

#1590 [#406, #866] Convert max HP to calculated value on characters & add hit points configuration app
  dnd5e.css
  lang/en.json
  less/actors.less
  less/apps.less
  module/applications/actor/_module.mjs
  module/applications/actor/armor-config.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/hit-points-config.mjs
  module/applications/actor/npc-sheet.mjs
  module/config.mjs
  module/data/actor/character.mjs
  module/documents/actor/actor.mjs
  module/documents/advancement/hit-points.mjs
  template.json
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet.hbs
  templates/apps/hit-points-config.hbs
Labels: ui, feature request
