Repository foundryvtt/dnd5e, pull requests merged in 2022-11, with the labels that each got.

#1912 [#1910] [#1911] Address class-subclass and identifier discrepancies a…
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  templates/items/class.hbs
  templates/items/subclass.hbs
Labels: bug, api

#1903 [#1901] Take ammo's critical threshold into account when calculating attack's threshold
  module/documents/item.mjs
Labels: feature request

#1896 [#1882] Fix new Character's token prototypes not having vision enabled by default
  module/documents/actor/actor.mjs
Labels: bug

#1860 [#1806] Fix number deltas not being accepted on actor sheet
  dnd5e.css
  less/actors.less
  module/applications/actor/base-sheet.mjs
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet.hbs
  templates/actors/parts/actor-inventory.hbs
  templates/actors/parts/actor-spellbook.hbs
  templates/actors/vehicle-sheet.hbs
Labels: bug

#1914 [#1853] Relieve automatic resizing of Item Sheets when dragged
  module/applications/item/item-sheet.mjs
Labels: bug, ui

#1920 [#1919] Disable grid snapping when placing ability templates onto gridless scenes
  module/canvas/ability-template.mjs
Labels: bug, ux

#1928 [#1835] Create system data model for classes
  module/advancement/advancement.mjs
  module/data/fields.mjs
  module/data/item/_module.mjs
  module/data/item/class.mjs
  module/documents/item.mjs
  module/migration.mjs
Labels: api

#1935 Add support for a group actor type to represent parties of characters traveling together in a region map.
  dnd5e.css
  dnd5e.mjs
  lang/en.json
  less/dnd5e.less
  less/group.less
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/group-sheet.mjs
  module/applications/actor/movement-config.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/actor/vehicle-sheet.mjs
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/item-sheet.mjs
  module/canvas/token.mjs
  module/data/_module.mjs
  module/data/actor/_module.mjs
  module/data/actor/group.mjs
  module/documents/actor/actor.mjs
  module/documents/combat.mjs
  module/documents/item.mjs
  system.json
  template.json
  templates/actors/group-sheet.hbs
  templates/actors/parts/actor-inventory.hbs
  templates/apps/actor-flags.hbs
  templates/apps/movement-config.hbs
  templates/items/tool.hbs
Labels: epic, feature request

#1927 [#1926] Add try-catch handling to placeTemplate case of Item5e._onChatCardAction
  module/documents/item.mjs
Labels: bug
