Repository foundryvtt/dnd5e, pull requests merged in 2022-10, with the labels that each got.

#1827 Provide an event option to `item#use` from character sheet usage
  module/applications/actor/base-sheet.mjs
  module/documents/item.mjs
Labels: api

#1828 Centralize fastForward detection for roll configs, allow explicit false
  module/dice/dice.mjs
  module/documents/item.mjs
Labels: api

#1600 [#1506] Add a copy button next to Scalar variable name
  lang/en.json
  module/advancement/types/scale-value.mjs
  templates/advancement/scale-value-config.hbs
Labels: ux

#1840 Polymorph Improvements
  dnd5e.css
  lang/en.json
  less/apps.less
  module/applications/actor/base-sheet.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/settings.mjs
  templates/apps/polymorph-prompt.hbs
Labels: bug, feature request, api, ux

#1812 [#1716] Convert `Advancement` to `DataModel`
  dnd5e.mjs
  module/advancement/advancement-config.mjs
  module/advancement/advancement-selection.mjs
  module/advancement/advancement.mjs
  module/advancement/types/hit-points.mjs
  module/advancement/types/item-grant.mjs
  module/advancement/types/scale-value.mjs
  module/applications/item/item-sheet.mjs
  module/data/_module.mjs
  module/data/advancement/_module.mjs
  module/data/advancement/base-advancement.mjs
  module/data/advancement/item-grant.mjs
  module/data/advancement/scale-value.mjs
  module/data/advancement/spell-config.mjs
  module/data/fields.mjs
  module/documents/item.mjs
  module/utils.mjs
  templates/advancement/advancement-step.hbs
  templates/advancement/item-grant-config.hbs
  templates/advancement/parts/advancement-controls.hbs
  templates/advancement/parts/advancement-spell-config.hbs
  templates/advancement/scale-value-config.hbs
Labels: api, advancement

#1863 [#1629] Adds confirmation prompt to item deletion.
  module/applications/actor/base-sheet.mjs
Labels: feature request, ux

#1881 [#1880] Fix token HP bar height
  module/canvas/token.mjs
Labels: bug

#1878 [#1807] Move advancement type setup to CONFIG
  module/advancement/advancement-selection.mjs
  module/config.mjs
  module/documents/item.mjs
Labels: bug, advancement

#1603 [#1334] Support variables in Duration field of items
  module/applications/item/item-sheet.mjs
  module/documents/item.mjs
  packs/classfeatures.db
  packs/spells.db
  packs/src/classfeatures/wild-shape.json
  packs/src/spells/level-2/animal-messenger.json
  packs/src/spells/level-3/magic-circle.json
  packs/src/spells/level-8/dominate-monster.json
  templates/items/parts/item-activation.hbs
Labels: feature request, compendium content

#1864 [#1839] Provided `parts` array overriding default `parts` in various rolls.
  module/documents/actor/actor.mjs
  module/documents/item.mjs
Labels: bug, api

#1872 [#1835] Add `loot` data model
  dnd5e.mjs
  lang/en.json
  module/applications/actor/base-sheet.mjs
  module/data/_module.mjs
  module/data/abstract.mjs
  module/data/item/_module.mjs
  module/data/item/loot.mjs
  module/data/item/templates/item-description.mjs
  module/data/item/templates/physical-item.mjs
  module/documents/item.mjs
  module/migration.mjs
Labels: api

#1887 [#1835] Add `feat` data definition with action & activated effect templates
  lang/en.json
  module/data/abstract.mjs
  module/data/fields.mjs
  module/data/item/_module.mjs
  module/data/item/feat.mjs
  module/data/item/templates/action.mjs
  module/data/item/templates/activated-effect.mjs
  module/migration.mjs
  template.json
  templates/items/parts/item-activation.hbs
Labels: api

#1888 [#1550, #1575] Refactor spellcasting preparation & add support for custom progressions
  lang/en.json
  module/config.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/utils.mjs
Labels: feature request, api

#1890 [#1835] Create system data models for spells
  lang/en.json
  module/data/fields.mjs
  module/data/item/_module.mjs
  module/data/item/spell.mjs
  template.json
Labels: api

#1899 [#1334, #1835] Fix ActivatedEffectTemplate not allowing formulas for durations
  module/data/item/templates/activated-effect.mjs
Labels: bug, api

#1728 [#1722] Create custom journal page for displaying an automatically generated class summary
  dnd5e.css
  dnd5e.mjs
  lang/en.json
  less/apps.less
  less/dnd5e.less
  less/journal.less
  module/applications/_module.mjs
  module/applications/journal/_module.mjs
  module/applications/journal/class-sheet.mjs
  module/applications/journal/journal-editor.mjs
  module/applications/journal/srd-compendium.mjs
  module/data/_module.mjs
  module/data/journal/_module.mjs
  module/data/journal/class.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/utils.mjs
  packs/classes.db
  packs/classfeatures.db
  packs/rules.db
  packs/src/classes/bard.json
  packs/src/classes/cleric.json
  packs/src/classes/druid.json
  packs/src/classes/paladin.json
  packs/src/classes/ranger.json
  packs/src/classes/sorcerer.json
  packs/src/classes/warlock.json
  packs/src/classes/wizard.json
  packs/src/classfeatures/circle-spells.json
  packs/src/classfeatures/eldritch-invocations.json
  packs/src/classfeatures/fighting-style-fighter.json
  packs/src/classfeatures/fighting-style-paladin.json
  packs/src/classfeatures/fighting-style-ranger.json
  packs/src/classfeatures/fighting-style.json
  packs/src/classfeatures/font-of-magic.json
  packs/src/classfeatures/metamagic.json
  packs/src/classfeatures/pact-magic.json
  packs/src/classfeatures/sacred-oath.json
  packs/src/classfeatures/spellcasting-bard.json
  packs/src/classfeatures/spellcasting-cleric.json
  packs/src/classfeatures/spellcasting-druid.json
  packs/src/classfeatures/spellcasting-paladin.json
  packs/src/classfeatures/spellcasting-ranger.json
  packs/src/classfeatures/spellcasting-sorcerer.json
  packs/src/classfeatures/spellcasting-wizard.json
  packs/src/classfeatures/unarmored-movement-monk.json
  packs/src/classfeatures/unarmored-movement.json
  packs/src/classfeatures/wild-shape.json
  packs/src/rules/chapter-3-classes.json
  packs/src/subclasses/life-domain.json
  packs/src/subclasses/oath-of-devotion.json
  packs/src/subclasses/the-fiend.json
  packs/subclasses.db
  template.json
  templates/journal/journal-editor.hbs
  templates/journal/page-class-edit.hbs
  templates/journal/page-class-view.hbs
  templates/journal/parts/journal-table.hbs
  templates/journal/srd-compendium.hbs
Labels: compendium content, api

#1898 [#1835] Create system data model for weapons
  module/data/item/_module.mjs
  module/data/item/templates/mountable.mjs
  module/data/item/weapon.mjs
  template.json
Labels: api
