Repository foundryvtt/dnd5e, pull requests merged in 2022-07, with the labels that each got.

#1630 [#1617] Update CONTRIBUTING.md to reflect move to GitHub
  CONTRIBUTING.md
Labels: documentation

#1648 Fix various issues with custom abilities caused by V10 transition
  module/documents/actor/actor.mjs
  templates/apps/ability-config.html
Labels: bug

#1589 Replace text inputs that use Number dtype with proper number inputs
  dnd5e.css
  less/actors.less
  less/advancement.less
  less/items.less
  module/applications/actor/base-sheet.mjs
  templates/actors/character-sheet.html
  templates/actors/npc-sheet.html
  templates/actors/parts/actor-inventory.html
  templates/actors/parts/actor-spellbook.html
  templates/actors/vehicle-sheet.html
  templates/advancement/scale-value-config.html
  templates/items/backpack.html
  templates/items/class.html
  templates/items/equipment.html
  templates/items/feat.html
  templates/items/parts/item-action.html
  templates/items/parts/item-activation.html
  templates/items/parts/item-description.html
  templates/items/parts/item-mountable.html
  templates/items/spell.html
  templates/items/tool.html
  templates/items/weapon.html
Labels: breaking, ux

#1649 Fix several bugs in item grant advancement
  module/advancement/advancement.mjs
  module/advancement/types/item-grant.mjs
  module/documents/item.mjs
  module/utils.mjs
Labels: bug

#1655 Fix v10 macro & token migration issues
  dnd5e.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/item/item-sheet.mjs
  module/documents/_module.mjs
  module/documents/macro.mjs
  module/migration.mjs
Labels: bug

#1661 [#1660] correctly await `item.getChatData` when expanding sheet item
  module/applications/actor/base-sheet.mjs
Labels: bug
