Repository foundryvtt/dnd5e, pull requests merged in 2023-01, with the labels that each got.

#1886 [#1885] Centralize trait configuration & merge `TraitSelector` applications
  lang/en.json
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/trait-selector.mjs
  module/applications/damage-trait-selector.mjs
  module/applications/item/item-sheet.mjs
  module/applications/proficiency-selector.mjs
  module/applications/trait-selector.mjs
  module/config.mjs
  module/documents/_module.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/trait.mjs
  module/utils.mjs
  templates/actors/parts/actor-traits.hbs
  templates/advancement/advancement-config.hbs
  templates/apps/parts/trait-list.hbs
  templates/apps/trait-selector.hbs
Labels: api

#2014 [#1944] Fix bug with displaying updates in AdvancementConfig
  module/applications/advancement/advancement-config.mjs
  module/documents/advancement/advancement.mjs
  module/documents/item.mjs
Labels: bug, advancement

#2009 [#1997] Add support for preRollInitiative and rollInitiative hooks.
  dnd5e.mjs
  module/applications/_module.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/combat/_module.mjs
  module/applications/combat/combat-tracker.mjs
  module/dice/d20-roll.mjs
  module/dice/dice.mjs
  module/documents/actor/actor.mjs
Labels: bug, feature request, dice

#2019 Rework sheet and roll data preparation to avoid mutating actor and item state
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/group-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/actor/vehicle-sheet.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet.hbs
  templates/actors/parts/actor-features.hbs
  templates/actors/parts/actor-inventory.hbs
  templates/actors/parts/actor-spellbook.hbs
  templates/actors/parts/actor-traits.hbs
  templates/actors/vehicle-sheet.hbs
Labels: breaking

#2020 Rename Species feature subtype to Race
  lang/en.json
  module/config.mjs
  packs/races.db
  packs/src/races/artificers-lore.json
  packs/src/races/brave.json
  packs/src/races/breath-weapon.json
  packs/src/races/damage-resistance.json
  packs/src/races/dwarven-resilience.json
  packs/src/races/fey-ancestry.json
  packs/src/races/gnome-cunning.json
  packs/src/races/halfling-nimbleness.json
  packs/src/races/hellish-resistance.json
  packs/src/races/infernal-legacy.json
  packs/src/races/lucky.json
  packs/src/races/naturally-stealthy.json
  packs/src/races/relentless-endurance.json
  packs/src/races/savage-attacks.json
  packs/src/races/stonecunning.json
  packs/src/races/tinker.json
Labels: compendium content

#2021 Fix issue with toObject changing Sets to Arrays, modify Trait#choices to take sets
  module/data/abstract.mjs
  module/documents/actor/trait.mjs
Labels: bug

#2035 Change backgrounds on start heroes to proper background items, fix wildshape CR on Aoth
  packs/heroes.db
  packs/src/heroes/akra-dragonborn-cleric.json
  packs/src/heroes/aoth-human-druid.json
  packs/src/heroes/beiro-half-elf-bard.json
  packs/src/heroes/krusk-half-orc-paladin.json
  packs/src/heroes/merric-halfling-barbarian.json
  packs/src/heroes/morthos-tiefling-sorcerer.json
  packs/src/heroes/perrin-halfling-monk.json
  packs/src/heroes/quillathe-elf-ranger.json
  packs/src/heroes/randal-human-fighter.json
  packs/src/heroes/riswynn-dwarf-rogue.json
  packs/src/heroes/sefris-half-elf-warlock.json
  packs/src/heroes/zanna-gnome-wizard.json
Labels: compendium content

#2062 [#2053] Fix spellcasting not being prepared if no class exists with spellcasting type
  module/documents/actor/actor.mjs
Labels: bug

#2060 Move proficiency calculating into Proficiency class
  module/applications/journal/class-sheet.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/proficiency.mjs
Labels: api

#2063 [#2061] Fix issue with item data missing from duration formula preparation
  module/documents/item.mjs
Labels: bug

#2011 [#1605] Prepare scale values earlier to allow them to be modified by active effects
  module/documents/actor/actor.mjs
Labels: advancement

#2070 [#2064] Fix system DataModel migrations causing issues with core migrations, up minimum core version
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/vehicle.mjs
  module/data/advancement/scale-value.mjs
  module/data/item/class.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/spell.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/documents/item.mjs
  system.json
Labels: bug

#2074 [#2018] Replace titles with tooltips on sheets
  templates/actors/character-sheet.hbs
  templates/actors/group-sheet.hbs
  templates/actors/limited-sheet.hbs
  templates/actors/npc-sheet.hbs
  templates/actors/parts/active-effects.hbs
  templates/actors/parts/actor-features.hbs
  templates/actors/parts/actor-inventory.hbs
  templates/actors/parts/actor-spellbook.hbs
  templates/actors/parts/actor-traits.hbs
  templates/actors/vehicle-sheet.hbs
  templates/advancement/item-grant-config.hbs
  templates/advancement/scale-value-config.hbs
  templates/apps/actor-type.hbs
  templates/apps/hit-dice-config.hbs
  templates/apps/hit-points-config.hbs
  templates/items/background.hbs
  templates/items/backpack.hbs
  templates/items/class.hbs
  templates/items/consumable.hbs
  templates/items/equipment.hbs
  templates/items/feat.hbs
  templates/items/loot.hbs
  templates/items/parts/item-activation.hbs
  templates/items/parts/item-advancement.hbs
  templates/items/spell.hbs
  templates/items/subclass.hbs
  templates/items/tool.hbs
  templates/items/weapon.hbs
  templates/journal/page-class-edit.hbs
Labels: ui

#2081 [#1564] Convert property attribution to use tooltips
  dnd5e.css
  less/actors.less
  less/apps.less
  module/applications/actor/base-sheet.mjs
  module/applications/property-attribution.mjs
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet.hbs
  templates/apps/property-attribution.hbs
Labels: ui

#2086 [#2054] Fix crew & passengers sections not displaying on vehicle sheet
  module/utils.mjs
  templates/actors/parts/actor-features.hbs
  templates/actors/parts/actor-inventory.hbs
  templates/actors/parts/actor-spellbook.hbs
Labels: bug

#2095 [#2082, #2089] Fix Cloak of Protection AE, remove recharge from features
  packs/classfeatures.db
  packs/items.db
  packs/src/classfeatures/action-surge.json
  packs/src/classfeatures/second-wind.json
  packs/src/items/equipment/cloak-of-protection.json
Labels: compendium content

#2088 [#244] Preserve expanded state of items on actor sheets across re-render
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/actor/vehicle-sheet.mjs
  module/utils.mjs
  templates/actors/parts/actor-features.hbs
  templates/actors/parts/actor-inventory.hbs
  templates/actors/parts/actor-spellbook.hbs
  templates/items/parts/item-summary.hbs
Labels: bug, ui

#2101 Fix issues with modifying custom skills
  module/applications/actor/ability-config.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/skill-config.mjs
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet.hbs
Labels: bug

#2103 [#2041] Disable fields that are overridden by an Active Effect and display a tooltip explaining why they cannot be edited
  dnd5e.css
  lang/en.json
  less/actors.less
  module/applications/actor/_module.mjs
  module/applications/actor/ability-config.mjs
  module/applications/actor/armor-config.mjs
  module/applications/actor/base-config.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/hit-dice-config.mjs
  module/applications/actor/hit-points-config.mjs
  module/applications/actor/initiative-config.mjs
  module/applications/actor/movement-config.mjs
  module/applications/actor/senses-config.mjs
  module/applications/actor/sheet-flags.mjs
  module/applications/actor/skill-config.mjs
  module/applications/actor/trait-selector.mjs
  templates/actors/parts/actor-spellbook.hbs
Labels: ui, ux, active effects

#2109 [#2108] Fix issue with localized ability abbreviations causing issues with skills
  module/applications/actor/base-sheet.mjs
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet.hbs
Labels: bug

#2107 [#1401] Add ItemChoiceAdvancement to SRD items
  packs/classes.db
  packs/classfeatures.db
  packs/src/classes/barbarian.json
  packs/src/classes/bard.json
  packs/src/classes/druid.json
  packs/src/classes/fighter.json
  packs/src/classes/monk.json
  packs/src/classes/paladin.json
  packs/src/classes/ranger.json
  packs/src/classes/rogue.json
  packs/src/classes/sorcerer.json
  packs/src/classes/warlock.json
  packs/src/classes/wizard.json
  packs/src/classfeatures/defensive-tactics.json
  packs/src/classfeatures/hunters-prey.json
  packs/src/classfeatures/multiattack.json
  packs/src/classfeatures/mystic-arcanum-7th-level-spell.json
  packs/src/classfeatures/mystic-arcanum-8th-level-spell.json
  packs/src/classfeatures/mystic-arcanum-9th-level-spell.json
  packs/src/classfeatures/mystic-arcanum.json
  packs/src/classfeatures/pact-boon.json
  packs/src/classfeatures/signature-spells-first-spell.json
  packs/src/classfeatures/signature-spells.json
  packs/src/classfeatures/superior-hunters-defense.json
  packs/src/classfeatures/wholeness-of-body.json
  packs/src/subclasses/champion.json
  packs/src/subclasses/college-of-lore.json
  packs/src/subclasses/hunter.json
  packs/subclasses.db
Labels: compendium content

#1876 [#1258, #1858, #1867] Conditionally show/hide item activation fields
  dnd5e.css
  lang/en.json
  less/items.less
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/item/templates/activated-effect.mjs
  packs/spells.db
  packs/src/spells/level-2/arcane-lock.json
  packs/src/spells/level-2/continual-flame.json
  packs/src/spells/level-2/magic-mouth.json
  packs/src/spells/level-3/glyph-of-warding.json
  packs/src/spells/level-5/hallow.json
  packs/src/spells/level-6/instant-summons.json
  packs/src/spells/level-6/magic-jar.json
  packs/src/spells/level-6/programmed-illusion.json
  packs/src/spells/level-7/sequester.json
  packs/src/spells/level-7/simulacrum.json
  packs/src/spells/level-7/symbol.json
  packs/src/spells/level-9/imprisonment.json
  templates/items/parts/item-activation.hbs
Labels: ui

#1847 [#1846] Allow ability type & defaults to be defined in config
  dnd5e.mjs
  module/applications/actor/ability-config.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/property-attribution.mjs
  module/config.mjs
  module/dice/d20-roll.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
Labels: api, breaking

#2110 [#2094] Move Item getters into system data models
  module/applications/item/item-sheet.mjs
  module/data/item/class.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/spell.mjs
  module/data/item/templates/action.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/templates/item-description.mjs
  module/data/item/templates/physical-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/documents/item.mjs
  templates/items/class.hbs
  templates/items/equipment.hbs
  templates/items/parts/item-action.hbs
  templates/items/parts/item-activation.hbs
  templates/items/weapon.hbs
Labels: api

#2126 [#2124] Fix bug with dropping classes & subclasses onto class journal pages
  module/applications/journal/class-sheet.mjs
Labels: bug

#2127 Remove deprecated methods targeted for removal in 2.2
  dnd5e.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/advancement/advancement-config.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/documents/actor/actor.mjs
  module/documents/advancement/advancement.mjs
Labels: api

#2113 [#774] Refactor tools implementation to be more like skills
  dnd5e.css
  lang/en.json
  less/actors.less
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/proficiency-config.mjs
  module/applications/actor/skill-config.mjs
  module/applications/actor/tool-selector.mjs
  module/applications/actor/trait-selector.mjs
  module/data/actor/character.mjs
  module/data/actor/templates/creature.mjs
  module/data/item/tool.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/migration.mjs
  system.json
  template.json
  templates/actors/character-sheet.hbs
  templates/actors/parts/actor-traits.hbs
  templates/apps/proficiency-config.hbs
  templates/items/tool.hbs
Labels: api, breaking
