Repository foundryvtt/dnd5e, pull requests merged in 2023-12, with the labels that each got.

#2657 [#2634] Removed Proficiency / Trait granting AE's in favor or those granted by trait Advancements.
  packs/classes.db
  packs/classfeatures.db
  packs/src/classes/rogue.json
  packs/src/classfeatures/bonus-proficiency-life-domain.json
  packs/src/classfeatures/divine-health.json
  packs/src/classfeatures/dragon-ancestor.json
  packs/src/classfeatures/purity-of-body.json
  packs/src/classfeatures/slippery-mind.json
  packs/src/subclasses/draconic-bloodline.json
  packs/subclasses.db
Labels: compendium content

#2677 Apply critical/fumble class only to the correct elements
  module/documents/chat-message.mjs
Labels: bug

#2676 [#2168] Standardize item system type format
  module/applications/actor/vehicle-sheet.mjs
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/fields/item-type-field.mjs
  module/data/item/loot.mjs
  module/data/item/templates/item-type.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/trait.mjs
  module/documents/item.mjs
  module/migration.mjs
  template.json
  templates/items/consumable.hbs
  templates/items/equipment.hbs
  templates/items/tool.hbs
  templates/items/weapon.hbs
  utils/packs.mjs
Labels: api

#2688 [#2168] Tweak item types to allow certain fields to not be included
  module/data/item/_module.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/fields/item-type-field.mjs
  module/data/item/loot.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
Labels: api

#2690 [#2689] Convert properties into a set
  module/applications/item/item-sheet.mjs
  module/data/item/consumable.mjs
  module/data/item/weapon.mjs
  templates/items/consumable.hbs
  templates/items/weapon.hbs
Labels: api, breaking

#2681 [#2636] Migrate spell `components` into `properties`, add `properties` to feature items, create `DND5E.itemProperties` and `DND5E.validProperties`.
  lang/en.json
  module/applications/actor/base-sheet.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/item/feat.mjs
  module/data/item/spell.mjs
  module/documents/item.mjs
  templates/items/feat.hbs
  templates/items/spell.hbs
Labels: api, breaking
