Repository foundryvtt/dnd5e, pull requests merged in 2023-05, with the labels that each got.

#2230 [#2229] Add support for getField requests to MappingField
  module/data/fields.mjs
Labels: api

#2278 Fixes for v11.
  dnd5e.css
  dnd5e.mjs
  lang/en.json
  less/journal.less
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/group-sheet.mjs
  module/applications/actor/vehicle-sheet.mjs
  module/applications/advancement/item-choice-config.mjs
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/item-sheet.mjs
  module/data/item/loot.mjs
  module/documents/active-effect.mjs
  module/documents/advancement/item-choice.mjs
  module/documents/advancement/item-grant.mjs
  module/documents/combat.mjs
  module/documents/macro.mjs
  templates/apps/actor-flags.hbs
  templates/chat/roll-dialog.hbs
Labels: bug

#2282 v11 compatibility updates.
  .gitignore
  dnd5e.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/abstract.mjs
  module/documents/actor/actor.mjs
  module/documents/token.mjs
  module/migration.mjs
  system.json
  templates/apps/initiative-config.hbs
  templates/apps/proficiency-config.hbs
  templates/apps/skill-config.hbs
Labels: bug

#2169 [#2166] Fix bug with equipment details not displaying on vehicle sheet
  module/applications/actor/vehicle-sheet.mjs
  module/data/item/templates/activated-effect.mjs
  module/utils.mjs
  template.json
  templates/actors/parts/actor-features.hbs
  templates/actors/parts/actor-inventory.hbs
Labels: bug, ui

#2186 [#2162, #2185] Fix sheet layout issues with long background or class names
  dnd5e.css
  less/actors.less
  less/character.less
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet.hbs
  templates/actors/vehicle-sheet.hbs
Labels: bug, ui

#2198 Consult source of hp max for characters
  templates/actors/character-sheet.hbs
Labels: bug

#2177 [#2176] Add min height and width to SRD Rules compendium
  dnd5e.css
  dnd5e.mjs
  less/journal.less
Labels: ui

#2131 Move distance units in range dropdown to top
  templates/items/parts/item-activation.hbs
Labels: ux

#2179 [#2161] Move base ability & skill prep into MappingField
  module/data/actor/templates/common.mjs
  module/data/actor/templates/creature.mjs
  module/data/fields.mjs
  module/data/shared/currency.mjs
  module/documents/actor/actor.mjs
Labels: bug, api
