Repository foundryvtt/dnd5e, pull requests merged in 2023-10, with the labels that each got.

#2498 [#1405] Data Structure for TraitAdvancement
  icons/LICENSE
  icons/svg/trait-armor-proficiencies.svg
  icons/svg/trait-condition-immunities.svg
  icons/svg/trait-damage-immunities.svg
  icons/svg/trait-damage-resistances.svg
  icons/svg/trait-damage-vulnerabilities.svg
  icons/svg/trait-languages.svg
  icons/svg/trait-saves.svg
  icons/svg/trait-skills.svg
  icons/svg/trait-tool-proficiencies.svg
  icons/svg/trait-weapon-proficiencies.svg
  icons/svg/trait.svg
  lang/en.json
  module/config.mjs
  module/data/advancement/_module.mjs
  module/data/advancement/trait.mjs
  module/utils.mjs
Labels: advancement

#2485 [#2456] Fix methods returning notification ids rather than null
  dnd5e.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/hit-points-config.mjs
  module/applications/advancement/ability-score-improvement-flow.mjs
  module/applications/advancement/advancement-config.mjs
  module/applications/advancement/item-choice-flow.mjs
  module/applications/item/item-sheet.mjs
  module/applications/trait-selector.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/documents/macro.mjs
Labels: bug

#2494 Add NaN logic to ASI flow
  module/applications/advancement/ability-score-improvement-flow.mjs
Labels: advancement

#2486 [#2457] Fix non-GMs being unable to drop items onto advancement flows
  module/applications/advancement/advancement-flow.mjs
Labels: bug, advancement

#2514 [#2470] Fix issue with ASI being applied incorrectly when effect targets ability
  module/documents/advancement/ability-score-improvement.mjs
Labels: bug, advancement

#2499 [#1405] Modify trait utilities to support prefixed trait keys & add SelectChoices
  lang/en.json
  module/applications/actor/base-sheet.mjs
  module/applications/actor/proficiency-config.mjs
  module/applications/actor/trait-selector.mjs
  module/documents/_module.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/select-choices.mjs
  module/documents/actor/trait.mjs
  module/utils.mjs
Labels: breaking, advancement

#2500 [#1865] Add dnd5e-specific rolling enrichers
  dnd5e.css
  dnd5e.mjs
  lang/en.json
  less/chat.less
  less/journal.less
  module/config.mjs
  module/documents/actor/actor.mjs
  module/enrichers.mjs
Labels: feature request

#2506 [#2495] Allow prepareData methods to be called on module actors
  module/data/actor/group.mjs
  module/documents/actor/actor.mjs
Labels: bug, api

#2516 [#2515] Fix warning from referenced active effect label
  dnd5e.mjs
  module/applications/actor/base-sheet.mjs
  module/documents/active-effect.mjs
  templates/actors/parts/active-effects.hbs
Labels: bug

#2537 Require confirmation to delete effects.
  module/documents/active-effect.mjs
Labels: ux

#2540 Require confirmation to delete effects.
  module/documents/active-effect.mjs
Labels: ux

#2527 [#2135, #2136] Add multiple inline editors to items & display chat description
  dnd5e.css
  less/apps.less
  less/items.less
  module/applications/accordion.mjs
  module/applications/item/item-sheet.mjs
  templates/chat/item-card.hbs
  templates/items/parts/item-description.hbs
Labels: feature request

#2534 [#2504] Convert source on items & actors into object
  module/data/actor/npc.mjs
  module/data/actor/vehicle.mjs
  module/data/item/templates/item-description.mjs
  module/data/shared/_module.mjs
  module/data/shared/source-field.mjs
  template.json
  templates/actors/npc-sheet.hbs
  templates/actors/vehicle-sheet.hbs
  templates/items/background.hbs
  templates/items/backpack.hbs
  templates/items/class.hbs
  templates/items/consumable.hbs
  templates/items/equipment.hbs
  templates/items/feat.hbs
  templates/items/loot.hbs
  templates/items/spell.hbs
  templates/items/subclass.hbs
  templates/items/tool.hbs
  templates/items/weapon.hbs
Labels: feature request
