Repository foundryvtt/dnd5e, pull requests merged in 2023-07, with the labels that each got.

#2341 Icon updates for various misc items in items.db
  packs/items.db
  packs/src/items/backpack/barrel.json
  packs/src/items/backpack/bucket.json
  packs/src/items/backpack/chest.json
  packs/src/items/backpack/sack.json
  packs/src/items/backpack/vial.json
  packs/src/items/loot/bag-of-sand.json
  packs/src/items/loot/blanket.json
  packs/src/items/loot/grappling-hook.json
  packs/src/items/loot/ink-pen.json
  packs/src/items/loot/paper.json
  packs/src/items/loot/parchment.json
  packs/src/items/loot/signal-whistle.json
  packs/src/items/loot/small-knife.json
  packs/src/items/loot/steel-mirror.json
  packs/src/items/loot/two-person-tent.json
  packs/src/items/trinket/bag-of-tricks-grey.json
  packs/src/items/trinket/candle.json
  packs/src/items/trinket/chain-10-feet.json
  packs/src/items/trinket/iron-spike.json
  packs/src/items/trinket/lamp.json
  packs/src/items/trinket/manacles.json
  packs/src/items/weapon/net-1.json
  packs/src/items/weapon/net-2.json
  packs/src/items/weapon/net-3.json
  packs/src/items/weapon/net.json
Labels: compendium content

#2159 [#1013] Add max to ability scores
  lang/en.json
  module/config.mjs
  module/data/actor/templates/common.mjs
  module/documents/actor/actor.mjs
  template.json
  templates/apps/ability-config.hbs
Labels: api

#2117 [#2036] Add physical properties to ammunition
  lang/en.json
  module/applications/item/item-sheet.mjs
  module/data/item/consumable.mjs
  templates/items/consumable.hbs
Labels: feature request

#2158 [#1403] Ability Score Improvement Advancement
  dnd5e.css
  icons/LICENSE
  icons/svg/ability-score-improvement.svg
  lang/en.json
  less/advancement.less
  module/applications/advancement/_module.mjs
  module/applications/advancement/ability-score-improvement-config.mjs
  module/applications/advancement/ability-score-improvement-flow.mjs
  module/applications/advancement/advancement-flow.mjs
  module/applications/advancement/advancement-manager.mjs
  module/applications/journal/class-sheet.mjs
  module/config.mjs
  module/data/_module.mjs
  module/data/abstract.mjs
  module/data/advancement/_module.mjs
  module/data/advancement/ability-score-improvement.mjs
  module/data/advancement/base-advancement.mjs
  module/data/advancement/spell-config.mjs
  module/documents/advancement/_module.mjs
  module/documents/advancement/ability-score-improvement.mjs
  module/settings.mjs
  module/utils.mjs
  templates/advancement/ability-score-improvement-config.hbs
  templates/advancement/ability-score-improvement-flow.hbs
  templates/advancement/parts/advancement-ability-score-control.hbs
Labels: advancement

#2143 [#1082] Add proficiency automation for weapons, armour, and tools.
  lang/en.json
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/actor/templates/creature.mjs
  module/data/item/equipment.mjs
  module/data/item/spell.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/migration.mjs
  template.json
  templates/items/equipment.hbs
  templates/items/tool.hbs
  templates/items/weapon.hbs
Labels: api, ux

#2173 [#885] [#2026] Add 'none' as an option when choosing the ability modifier
  module/data/item/templates/action.mjs
  module/documents/item.mjs
  templates/items/parts/item-action.hbs
Labels: feature request

#2182 Tweaks and fixes to the scroll creation process
  lang/en.json
  module/documents/item.mjs
Labels: feature request, api, localization

#2378 [#974] [#1122] Add 'any', 'creature or object', and 'willing creature' as available target types.
  lang/en.json
  module/config.mjs
Labels: api

#2172 [#2170] Add ammo, focus, and container types
  lang/en.json
  module/config.mjs
Labels: api

#2345 pack folders
  system.json
Labels: compendium content
