Repository foundryvtt/dnd5e, pull requests merged in 2023-11, with the labels that each got.

#2535 [#2451] Fix bug with custom skills & abilities causing transformation to fail
  module/documents/actor/actor.mjs
Labels: bug

#2522 [#1405] Add TraitAdvancement & TraitConfig
  dnd5e.css
  lang/en.json
  less/advancement.less
  less/apps.less
  module/applications/advancement/_module.mjs
  module/applications/advancement/trait-config.mjs
  module/config.mjs
  module/documents/actor/trait.mjs
  module/documents/advancement/_module.mjs
  module/documents/advancement/trait.mjs
  templates/advancement/trait-config.hbs
  templates/apps/parts/trait-list.hbs
Labels: advancement

#2530 Add cached roll to direct rollInitiative call
  module/documents/actor/actor.mjs
Labels: bug

#2425 [#986] Allow for rotating a square/cube template
  lang/en.json
  module/canvas/ability-template.mjs
  module/settings.mjs
Labels: feature request

#2541 [#342, #2538] Display race on sheet, add singleton logic to race & background items
  lang/en.json
  module/applications/actor/character-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/actor/vehicle-sheet.mjs
  module/data/abstract.mjs
  module/data/actor/character.mjs
  module/data/actor/templates/details.mjs
  module/data/fields.mjs
  module/data/item/background.mjs
  module/data/item/race.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/documents/mixin.mjs
  module/migration.mjs
  system.json
  templates/actors/character-sheet.hbs
Labels: feature request, breaking, migration

#2543 [#1405] Add TraitFlow & application methods
  dnd5e.css
  lang/en.json
  less/advancement.less
  module/applications/advancement/_module.mjs
  module/applications/advancement/advancement-flow.mjs
  module/applications/advancement/advancement-manager.mjs
  module/applications/advancement/trait-config.mjs
  module/applications/advancement/trait-flow.mjs
  module/data/advancement/trait.mjs
  module/documents/actor/trait.mjs
  module/documents/advancement/trait.mjs
  module/utils.mjs
  templates/advancement/trait-config.hbs
  templates/advancement/trait-flow.hbs
Labels: advancement

#2533 [#2529] Implement damage enricher
  lang/en.json
  module/enrichers.mjs
Labels: feature request

#2547 [#1405] Update class journal page to display proficiencies from TraitAdvancement
  lang/en.json
  module/applications/journal/class-sheet.mjs
  packs/rules.db
  packs/src/rules/chapter-3-classes.json
  templates/journal/page-class-view.hbs
Labels: advancement

#2557 [#342] Add creature type data to PCs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/shared/creature-type-field.mjs
  module/data/shared/source-field.mjs
  templates/actors/parts/actor-traits.hbs
Labels: feature request

#2554 Add preHook on the "createScrollFromSpell" function
  module/documents/item.mjs
Labels: feature request, api

#2556 [#342] Apply senses/movement to actor when race is added
  module/applications/actor/base-sheet.mjs
  module/data/actor/character.mjs
  module/data/item/race.mjs
Labels: feature request

#2544 [#1405] Add traits to SRD content
  packs/backgrounds.db
  packs/classes.db
  packs/src/backgrounds/acolyte.json
  packs/src/classes/barbarian.json
  packs/src/classes/bard.json
  packs/src/classes/cleric.json
  packs/src/classes/druid.json
  packs/src/classes/fighter.json
  packs/src/classes/monk.json
  packs/src/classes/paladin.json
  packs/src/classes/ranger.json
  packs/src/classes/rogue.json
  packs/src/classes/sorcerer.json
  packs/src/classes/warlock.json
  packs/src/classes/wizard.json
  packs/src/subclasses/college-of-lore.json
  packs/src/subclasses/life-domain.json
  packs/subclasses.db
Labels: compendium content, advancement

#2559 [#342, #2558] Improve advancement interaction with race items
  dnd5e.css
  lang/en.json
  less/advancement.less
  module/applications/advancement/ability-score-improvement-flow.mjs
  module/data/advancement/ability-score-improvement.mjs
  module/data/advancement/base-advancement.mjs
  module/data/item/race.mjs
  module/documents/advancement/ability-score-improvement.mjs
  module/documents/advancement/advancement.mjs
  module/documents/advancement/size.mjs
  module/documents/item.mjs
  templates/advancement/ability-score-improvement-config.hbs
  templates/advancement/ability-score-improvement-flow.hbs
Labels: advancement

#2570 [#2561] Display ASI values in config mode
  module/documents/advancement/ability-score-improvement.mjs
Labels: ui, advancement

#2573 [#2567, #2569] Add status indicator to accordions, fix jump on sheet re-render
  dnd5e.css
  less/apps.less
  less/items.less
  module/applications/accordion.mjs
  templates/items/parts/item-description.hbs
Labels: bug, ui

#2575 [#2528] Add categories to languages
  lang/en.json
  module/config.mjs
  module/documents/actor/trait.mjs
Labels: feature request

#2546 [#1405] Migrate existing class saves/skills data to TraitAdvancement
  lang/en.json
  module/applications/_module.mjs
  module/applications/item/item-sheet.mjs
  module/applications/trait-selector.mjs
  module/data/item/class.mjs
  module/documents/item.mjs
  module/migration.mjs
  template.json
  templates/items/class.hbs
Labels: breaking, advancement

#2581 Make the item description edit buttons slightly easier to hit
  dnd5e.css
  less/apps.less
  less/items.less
Labels: ui

#2576 [#2504] Implement editor for source data
  dnd5e.css
  lang/en.json
  less/items.less
  less/npc.less
  module/applications/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/item/item-sheet.mjs
  module/applications/source-config.mjs
  module/config.mjs
  module/data/shared/source-field.mjs
  module/utils.mjs
  templates/actors/npc-sheet.hbs
  templates/apps/source-config.hbs
  templates/items/background.hbs
  templates/items/backpack.hbs
  templates/items/class.hbs
  templates/items/consumable.hbs
  templates/items/equipment.hbs
  templates/items/feat.hbs
  templates/items/loot.hbs
  templates/items/parts/item-source.hbs
  templates/items/race.hbs
  templates/items/spell.hbs
  templates/items/subclass.hbs
  templates/items/tool.hbs
  templates/items/weapon.hbs
  templates/journal/page-class-edit.hbs
Labels: ui, feature request

#2589 Update Starter Heroes with Races & TraitAdvancement on classes, fix issues with Races
  module/applications/actor/base-sheet.mjs
  module/data/item/race.mjs
  packs/classes.db
  packs/classfeatures.db
  packs/heroes.db
  packs/races.db
  packs/src/classes/druid.json
  packs/src/classes/rogue.json
  packs/src/classfeatures/druidic.json
  packs/src/classfeatures/thieves-cant.json
  packs/src/heroes/akra-dragonborn-cleric.json
  packs/src/heroes/aoth-human-druid.json
  packs/src/heroes/beiro-half-elf-bard.json
  packs/src/heroes/krusk-half-orc-paladin.json
  packs/src/heroes/merric-halfling-barbarian.json
  packs/src/heroes/morthos-tiefling-sorcerer.json
  packs/src/heroes/perrin-halfling-monk.json
  packs/src/heroes/quillathe-elf-ranger.json
  packs/src/heroes/randal-human-fighter.json
  packs/src/heroes/riswynn-dwarf-rogue.json
  packs/src/heroes/sefris-half-elf-warlock.json
  packs/src/heroes/zanna-gnome-wizard.json
  packs/src/races/dragonborn.json
  packs/src/races/dwarven-resilience.json
  packs/src/races/half-elf.json
  packs/src/races/half-orc.json
  packs/src/races/hellish-resistance.json
  packs/src/races/high-elf.json
  packs/src/races/hill-dwarf.json
  packs/src/races/human.json
  packs/src/races/lightfoot-halfling.json
  packs/src/races/lucky.json
  packs/src/races/rock-gnome.json
  packs/src/races/tiefling.json
  packs/src/races/tinker.json
Labels: compendium content

#2593 [#2579] Fix creature type still being editable despite being overridden by an Active Effect.
  dnd5e.css
  less/apps.less
  module/applications/actor/type-config.mjs
Labels: bug

#2601 Added missing translated label
  templates/advancement/trait-config.hbs
Labels: localization

#2612 [#2609] Fix bugs with singleton enforcement
  module/applications/actor/base-sheet.mjs
Labels: bug

#2611 [#2596] Fix expertise modes not working with tools on TraitAdvancement
  module/documents/actor/select-choices.mjs
  module/documents/actor/trait.mjs
  module/documents/advancement/trait.mjs
Labels: bug, advancement

#2635 [#2401] Allow max HP to be overriden by effects
  module/documents/actor/actor.mjs
Labels: bug, active effects

#2613 [#2607] Fix collpased accordion sections not opening after editing description
  module/applications/accordion.mjs
Labels: bug, ui

#2647 Amend warning on AbilityUseDialog for pact slots
  module/applications/item/ability-use-dialog.mjs
  templates/apps/ability-use.hbs
Labels: bug

#2650 Fix enrichers using full key rather then short key when calling roll method
  module/config.mjs
  module/enrichers.mjs
Labels: bug
