Repository foundryvtt/dnd5e, pull requests merged in 2024-09, with the labels that each got.

#4077 [#4076] Allow removal of Perception for ActorSheet5eNPC2
  module/applications/actor/npc-sheet-2.mjs
Labels: bug

#4080 [#4079] Handle limited uses on granted spells
  lang/en.json
  module/applications/advancement/item-choice-config.mjs
  module/applications/advancement/item-grant-config.mjs
  module/data/activity/save-data.mjs
  module/data/advancement/spell-config.mjs
  module/data/item/spell.mjs
  module/documents/advancement/item-grant.mjs
  templates/advancement/parts/advancement-spell-config.hbs
  templates/items/details/details-spell.hbs
Labels: bug, system: advancement, system: activities

#4102 [#3462] Hex grid TokenPlacement
  module/canvas/token-placement.mjs
Labels: bug, system: summoning

#4098 Display activities in-sheet
  lang/en.json
  less/v2/dark/inventory.less
  less/v2/forms.less
  less/v2/inventory.less
  less/variables.less
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/npc-sheet-2.mjs
  module/applications/actor/sheet-mixin.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/components/inventory.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/data/shared/range-field.mjs
  module/data/shared/uses-field.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/utils.mjs
  templates/activity/activity-row-summary.hbs
  templates/activity/columns/activity-column-controls.hbs
  templates/activity/columns/activity-column-formula.hbs
  templates/activity/columns/activity-column-price.hbs
  templates/activity/columns/activity-column-quantity.hbs
  templates/activity/columns/activity-column-range.hbs
  templates/activity/columns/activity-column-recovery.hbs
  templates/activity/columns/activity-column-roll.hbs
  templates/activity/columns/activity-column-school.hbs
  templates/activity/columns/activity-column-target.hbs
  templates/activity/columns/activity-column-time.hbs
  templates/activity/columns/activity-column-uses.hbs
  templates/activity/columns/activity-column-weight.hbs
  templates/actors/parts/columns/column-uses.hbs
  templates/actors/tabs/creature-features.hbs
  templates/actors/tabs/creature-spells.hbs
  templates/shared/inventory2.hbs
Labels: ui, ux

#4094 [#4093] Update to magical axe weapon icons
  packs/_source/items/weapon/battleaxe-1.json
  packs/_source/items/weapon/battleaxe-2.json
  packs/_source/items/weapon/battleaxe-3.json
  packs/_source/items/weapon/berserker-battleaxe.json
  packs/_source/items/weapon/berserker-greataxe.json
  packs/_source/items/weapon/berserker-handaxe.json
  packs/_source/items/weapon/giant-slayer-battleaxe.json
  packs/_source/items/weapon/giant-slayer-greataxe.json
  packs/_source/items/weapon/giant-slayer-handaxe.json
  packs/_source/items/weapon/greataxe-2.json
  packs/_source/items/weapon/greataxe-3.json
  packs/_source/items/weapon/greataxe.json
  packs/_source/items/weapon/handaxe-1.json
  packs/_source/items/weapon/handaxe-2.json
  packs/_source/items/weapon/handaxe-3.json
  packs/_source/items/weapon/vicious-battleaxe.json
  packs/_source/items/weapon/vicious-greataxe.json
  packs/_source/items/weapon/vicious-handaxe.json
Labels: compendium content

#4105 [#2508] Add spell list filter to compendium browser
  module/applications/compendium-browser.mjs
  module/data/item/spell.mjs
  module/registry.mjs
Labels: feature request, system: compendium browser

#4106 [#3801] Automatically determine source book from module
  module/applications/actor/api/base-config-sheet.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/api/document-sheet.mjs
  module/applications/item/item-sheet.mjs
  module/applications/source-config.mjs
  module/config.mjs
  module/data/actor/npc.mjs
  module/data/actor/vehicle.mjs
  module/data/item/background.mjs
  module/data/item/class.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/loot.mjs
  module/data/item/race.mjs
  module/data/item/spell.mjs
  module/data/item/subclass.mjs
  module/data/item/templates/item-description.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/data/shared/source-field.mjs
  module/module-registration.mjs
  system.json
  templates/apps/source-config.hbs
Labels: ui, feature request

#4114 [#4107] Fix applying rider effects on enchantment. Fix flagging rider effects.
  module/applications/item/item-sheet.mjs
  module/documents/active-effect.mjs
  module/documents/item.mjs
Labels: bug

#4104 Add `simplify` method to `BasicRoll`
  module/dice/basic-roll.mjs
Labels: system: dice

#4117 [#3914] Fix enchanted damage types into activities
  module/data/activity/attack-data.mjs
  module/data/item/consumable.mjs
  module/data/item/weapon.mjs
Labels: bug, system: enchantment

#4123 [#4024] Rework Check Activity to support multiple checks
  lang/en.json
  module/applications/activity/check-sheet.mjs
  module/data/activity/check-data.mjs
  module/documents/activity/check.mjs
  templates/activity/parts/check-details.hbs
Labels: feature request, system: activities

#4126 [#4125] New icons for magic bows
  packs/_source/items/weapon/longbow-1.json
  packs/_source/items/weapon/longbow-2.json
  packs/_source/items/weapon/longbow-3.json
  packs/_source/items/weapon/longbow.json
  packs/_source/items/weapon/shortbow-2.json
  packs/_source/items/weapon/shortbow-3.json
  packs/_source/items/weapon/shortbow.json
  packs/_source/items/weapon/vicious-longbow.json
Labels: compendium content

#4130 [#4129] New icons for magic ammo.
  packs/_source/items/ammunition/arrow-1.json
  packs/_source/items/ammunition/arrow-2.json
  packs/_source/items/ammunition/arrow-3.json
  packs/_source/items/ammunition/arrow-of-slaying.json
  packs/_source/items/ammunition/arrow.json
  packs/_source/items/ammunition/blowgun-needle.json
  packs/_source/items/ammunition/bolt-of-slaying.json
  packs/_source/items/ammunition/crossbow-bolt-1.json
  packs/_source/items/ammunition/crossbow-bolt-2.json
  packs/_source/items/ammunition/crossbow-bolt-3.json
  packs/_source/items/ammunition/crossbow-bolt.json
  packs/_source/items/ammunition/sling-bullet-1.json
  packs/_source/items/ammunition/sling-bullet-2.json
  packs/_source/items/ammunition/sling-bullet-3.json
  packs/_source/items/ammunition/sling-bullet-of-slaying.json
  packs/_source/items/ammunition/sling-bullet.json
  packs/_source/items/container/crossbow-bolt-case/_container.json
  packs/_source/items/container/efficient-quiver/_container.json
  packs/_source/items/container/quiver/_container.json
Labels: compendium content

#4132 [#4131] New icons for magic crossbows
  packs/_source/items/weapon/hand-crossbow-1.json
  packs/_source/items/weapon/hand-crossbow-2.json
  packs/_source/items/weapon/hand-crossbow-3.json
  packs/_source/items/weapon/hand-crossbow.json
  packs/_source/items/weapon/heavy-crossbow-1.json
  packs/_source/items/weapon/heavy-crossbow-2.json
  packs/_source/items/weapon/heavy-crossbow-3.json
  packs/_source/items/weapon/light-crossbow-1.json
  packs/_source/items/weapon/light-crossbow-2.json
  packs/_source/items/weapon/light-crossbow-3.json
  packs/_source/items/weapon/vicious-hand-crossbow.json
  packs/_source/items/weapon/vicious-heavy-crossbow.json
  packs/_source/items/weapon/vicious-light-crossbow.json
Labels: compendium content

#4127 Toggle localization changes with Rules Version setting
  dnd5e.mjs
  lang/en.json
  module/config.mjs
  templates/journal/page-spell-list-edit.hbs
Labels: localization

#4128 [#3762] Add arbitrary effects to summoned creatures
  less/v2/activities.less
  module/applications/activity/summon-sheet.mjs
  module/data/activity/summon-data.mjs
  module/documents/activity/summon.mjs
  templates/activity/parts/summon-changes.hbs
Labels: feature request, system: summoning

#4138 [#3803] Add rider activities to enchantments
  lang/en.json
  module/applications/activity/activity-choice-dialog.mjs
  module/applications/activity/enchant-sheet.mjs
  module/data/activity/enchant-data.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  module/migration.mjs
  templates/activity/parts/enchant-enchantments.hbs
Labels: feature request, system: enchantment, system: activities

#4085 [#4084] Update config.mjs humanoid icon
  module/config.mjs
Labels: ui

#4139 [#3803] Fix adding new enchantments to activity
  module/documents/item.mjs
Labels: bug

#4148 Add sources filtering to compendium browser.
  lang/en.json
  less/v2/compendium-browser.less
  less/v2/inventory.less
  less/v2/tooltips.less
  module/applications/compendium-browser.mjs
  module/data/shared/source-field.mjs
  templates/compendium/browser-entry.hbs
  templates/compendium/browser-results.hbs
  templates/compendium/browser-sidebar-filter-set.hbs
  templates/compendium/browser-sidebar-filters.hbs
Labels: system: compendium browser

#4177 Add application for configuring compendium browser source exclusions.
  lang/en.json
  less/v2/apps.less
  less/v2/compendium-browser.less
  less/v2/dark/apps.less
  module/applications/_module.mjs
  module/applications/compendium-browser-source-config.mjs
  module/applications/compendium-browser.mjs
  module/settings.mjs
  templates/compendium/browser-header.hbs
  templates/compendium/sources-packs.hbs
  templates/compendium/sources-sidebar.hbs
Labels: api

#4152 New icons for magic longswords
  packs/_source/items/weapon/dancing-longsword.json
  packs/_source/items/weapon/defender-longsword.json
  packs/_source/items/weapon/dragon-slayer-longsword.json
  packs/_source/items/weapon/flame-tongue-longsword.json
  packs/_source/items/weapon/frost-brand-longsword.json
  packs/_source/items/weapon/holy-avenger-longsword.json
  packs/_source/items/weapon/longsword-1.json
  packs/_source/items/weapon/longsword-2.json
  packs/_source/items/weapon/longsword-3.json
  packs/_source/items/weapon/longsword-of-life-stealing.json
  packs/_source/items/weapon/longsword-of-sharpness.json
  packs/_source/items/weapon/longsword-of-wounding.json
  packs/_source/items/weapon/luck-blade-longsword.json
  packs/_source/items/weapon/nine-lives-stealer-longsword.json
  packs/_source/items/weapon/sun-blade.json
  packs/_source/items/weapon/vicious-longsword.json
Labels: compendium content

#4156 New icons for magic scimitars
  packs/_source/items/weapon/dancing-scimitar.json
  packs/_source/items/weapon/defender-scimitar.json
  packs/_source/items/weapon/dragon-slayer-scimitar.json
  packs/_source/items/weapon/flame-tongue-scimitar.json
  packs/_source/items/weapon/frost-brand-scimitar.json
  packs/_source/items/weapon/giant-slayer-scimitar.json
  packs/_source/items/weapon/holy-avenger-scimitar.json
  packs/_source/items/weapon/luck-blade-scimitar.json
  packs/_source/items/weapon/nine-lives-stealer-scimitar.json
  packs/_source/items/weapon/scimitar-1.json
  packs/_source/items/weapon/scimitar-2.json
  packs/_source/items/weapon/scimitar-3.json
  packs/_source/items/weapon/scimitar-of-life-stealing.json
  packs/_source/items/weapon/scimitar-of-sharpness.json
  packs/_source/items/weapon/scimitar-of-speed.json
  packs/_source/items/weapon/scimitar-of-wounding.json
  packs/_source/items/weapon/vicious-scimitar.json
  packs/_source/items/weapon/vorpal-scimitar.json
Labels: compendium content

#4173 New icons for capes, cloaks, clothes, & robes
  packs/_source/items/equipment/cape-of-the-mountebank.json
  packs/_source/items/equipment/cloak-of-arachnida.json
  packs/_source/items/equipment/cloak-of-displacement.json
  packs/_source/items/equipment/cloak-of-elvenkind.json
  packs/_source/items/equipment/cloak-of-the-bat.json
  packs/_source/items/equipment/cloak-of-the-manta-ray.json
  packs/_source/items/equipment/costume-clothes.json
  packs/_source/items/equipment/fine-clothes.json
  packs/_source/items/equipment/mantle-of-spell-resistance.json
  packs/_source/items/equipment/robe-of-eyes.json
  packs/_source/items/equipment/robe-of-scintillating-colors.json
  packs/_source/items/equipment/robe-of-stars.json
  packs/_source/items/equipment/robe-of-the-archmagi.json
  packs/_source/items/equipment/robe-of-useful-items.json
  packs/_source/items/equipment/robes.json
  packs/_source/items/equipment/travelers-clothes.json
  packs/_source/items/equipment/wings-of-flying.json
Labels: compendium content

#4183 New icons for select classes & subclasses
  packs/_source/classes/bard.json
  packs/_source/classes/monk.json
  packs/_source/classes/paladin.json
  packs/_source/subclasses/champion.json
  packs/_source/subclasses/hunter.json
  packs/_source/subclasses/life-domain.json
  packs/_source/subclasses/the-fiend.json
Labels: compendium content

#4185 New icons for magic rods and scrolls
  packs/_source/items/ammunition/blowgun-needle.json
  packs/_source/items/container/map-or-scroll-case/_container.json
  packs/_source/items/rod/immovable-rod.json
  packs/_source/items/rod/rod-of-absorption.json
  packs/_source/items/rod/rod-of-alertness.json
  packs/_source/items/rod/rod-of-lordly-might.json
  packs/_source/items/rod/rod-of-rulership.json
  packs/_source/items/rod/rod-of-security.json
  packs/_source/items/scroll/spell-scroll-1st-level.json
  packs/_source/items/scroll/spell-scroll-2nd-level.json
  packs/_source/items/scroll/spell-scroll-3rd-level.json
  packs/_source/items/scroll/spell-scroll-4th-level.json
  packs/_source/items/scroll/spell-scroll-5th-level.json
  packs/_source/items/scroll/spell-scroll-6th-level.json
  packs/_source/items/scroll/spell-scroll-7th-level.json
  packs/_source/items/scroll/spell-scroll-8th-level.json
  packs/_source/items/scroll/spell-scroll-9th-level.json
  packs/_source/items/scroll/spell-scroll-cantrip.json
  packs/_source/items/weapon/rod.json
  packs/_source/items/weapon/vicious-dart.json
Labels: compendium content

#4160 Refactor `Item5e#displayCard` to remove unnecessary data
  module/documents/item.mjs
Labels: api

#4144 [#4143] Move Active Effect formula changes into FormulaField
  module/data/fields/formula-field.mjs
  module/documents/active-effect.mjs
Labels: system: active effects

#4141 [#3785] Add refund button to chat cards
  lang/en.json
  module/data/activity/fields/consumption-targets-field.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/check.mjs
  module/documents/activity/damage.mjs
  module/documents/activity/heal.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/save.mjs
  module/documents/activity/summon.mjs
  module/documents/activity/utility.mjs
Labels: feature request, system: activities

#4164 [#3582] Add Burning status effect
  icons/LICENSE
  icons/svg/statuses/burning.svg
  lang/en.json
  less/v1/apps.less
  module/config.mjs
Labels: feature request

#4165 [#4163] Add Dehydration, Falling, Malnutrition, and Suffocation
  icons/LICENSE
  icons/svg/statuses/dehydration.svg
  icons/svg/statuses/falling.svg
  icons/svg/statuses/malnutrition.svg
  icons/svg/statuses/suffocation.svg
  lang/en.json
  module/config.mjs
Labels: feature request

#4175 [#4174] Defer item regsitry loading if Babel is present
  module/registry.mjs
Labels: localization

#4181 [#4024] Add spellcasting ability as option for Check activity
  module/applications/activity/check-sheet.mjs
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/check-data.mjs
  module/data/activity/save-data.mjs
Labels: system: activities

#4159 [#2138] Refactor `rollRecharge` to use `BasicRoll` & new hooks
  module/applications/components/inventory.mjs
  module/data/shared/uses-field.mjs
  module/dice/basic-roll.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/utility.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
Labels: api, system: dice

#4179 [#3317] Consume thrown weapon quantity unless Returning is checked
  lang/en.json
  module/documents/activity/attack.mjs
Labels: feature request, system: activities

#4187 [#1539] Use migration to set identifier on items
  module/migration.mjs
Labels: migration

#4190 Add context menus to in-sheet Activities.
  less/v2/dark/activities.less
  module/applications/actor/character-sheet-2.mjs
  module/applications/components/inventory.mjs
  module/applications/item/item-sheet-2.mjs
  module/documents/activity/mixin.mjs
  templates/actors/tabs/creature-features.hbs
  templates/actors/tabs/creature-spells.hbs
  templates/items/parts/item-activities.hbs
  templates/shared/inventory2.hbs
Labels: ui, ux

#4191 [#2125] Only display features in table, simplify subclass tables
  module/applications/journal/class-page-sheet.mjs
Labels: feature request, system: journals

#4199 Allow activities to be added directly to favourites.
  less/v2/dark/activities.less
  less/v2/dark/forms.less
  module/applications/actor/character-sheet-2.mjs
  module/applications/components/inventory.mjs
  module/data/actor/character.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/save.mjs
  templates/actors/character-sheet-2.hbs
Labels: ux, system: activities

#4200 Add Offhand Throw attack mode & returning property to ammunition
  lang/en.json
  module/data/activity/attack-data.mjs
  module/data/item/consumable.mjs
  module/data/item/weapon.mjs
  module/documents/activity/attack.mjs
Labels: feature request

#3122 Add `statuses` to `Actor#getRollData`
  module/documents/actor/actor.mjs
Labels: api

#3759 Enable `textSearch` for fields of `JournalEntryPage` sub-types
  module/data/journal/class.mjs
  module/data/journal/rule.mjs
  module/data/journal/spells.mjs
  module/data/journal/subclass.mjs
Labels: ux, system: journals

#4198 append item rollData when recovering during rest
  module/documents/actor/actor.mjs
Labels: api

#4207 New icons for books
  packs/_source/items/loot/book-of-lore.json
  packs/_source/items/loot/book.json
  packs/_source/items/loot/prayer-book.json
  packs/_source/items/loot/spellbook.json
  packs/_source/items/trinket/manual-of-bodily-health.json
  packs/_source/items/trinket/manual-of-gainful-exercise.json
  packs/_source/items/trinket/manual-of-golems.json
  packs/_source/items/trinket/manual-of-quickness-of-action.json
  packs/_source/items/trinket/tome-of-clear-thought.json
  packs/_source/items/trinket/tome-of-leadership-and-influence.json
  packs/_source/items/trinket/tome-of-understanding.json
Labels: compendium content

#4133 Document activities system and each activity type for Wiki
  wiki/Activities.md
  wiki/Activity-Type-Attack.md
  wiki/Activity-Type-Check.md
  wiki/Activity-Type-Damage.md
  wiki/Activity-Type-Enchant.md
  wiki/Activity-Type-Heal.md
  wiki/Activity-Type-Save.md
  wiki/Activity-Type-Summon.md
  wiki/Activity-Type-Utility.md
  wiki/Enchantment.md
  wiki/Home.md
  wiki/Summoning.md
  wiki/images/activities/activity-consumption.jpg
  wiki/images/activities/activity-creation.jpg
  wiki/images/activities/activity-effect.jpg
  wiki/images/activities/activity-identity.jpg
  wiki/images/activities/activity-tab.jpg
  wiki/images/activities/activity-targeting.jpg
  wiki/images/activities/activity-time.jpg
  wiki/images/activities/attack-chat-dialog.jpg
  wiki/images/activities/attack-effect.jpg
  wiki/images/activities/attack-identity.jpg
  wiki/images/activities/check-card.jpg
  wiki/images/activities/check-effect.jpg
  wiki/images/activities/damage-effect.jpg
  wiki/images/activities/heal-effect.jpg
  wiki/images/activities/save-effect.jpg
  wiki/images/activities/utility-effect.jpg
  wiki/images/activities/utility-identity.jpg
  wiki/images/enchantment/enchant-enchantments-multiple.jpg
  wiki/images/enchantment/enchant-enchantments-riders.jpg
  wiki/images/enchantment/enchant-restrictions.jpg
  wiki/images/enchantment/enchantment-chat-message.jpg
  wiki/images/enchantment/enchantment-configuration.jpg
  wiki/images/enchantment/enchantment-item-details.jpg
  wiki/images/enchantment/enchantment-summary.jpg
  wiki/images/summoning/summoning-changes.jpg
  wiki/images/summoning/summoning-configuration.jpg
  wiki/images/summoning/summoning-cr-configuration.jpg
  wiki/images/summoning/summoning-cr-prompt.jpg
  wiki/images/summoning/summoning-identity.jpg
  wiki/images/summoning/summoning-item-details.jpg
  wiki/images/summoning/summoning-profiles-challenge-rating.jpg
  wiki/images/summoning/summoning-profiles-direct-link.jpg
  wiki/images/summoning/summoning-profiles-empty.jpg
  wiki/images/summoning/summoning-profiles-level-limits.jpg
  wiki/images/summoning/summoning-prompt.jpg
  wiki/images/summoning/summoning-quantity-level.jpg
  wiki/images/summoning/summoning-summary.jpg
Labels: documentation

#4136 Update AE Guide, Enrichers, & Roll Formulas, document Module Registration
  wiki/Active-Effect-Guide.md
  wiki/Compendium-Browser.md
  wiki/Enrichers.md
  wiki/Home.md
  wiki/Module-Registration.md
  wiki/Roll-Formulas.md
Labels: documentation

#4134 Update hooks page to reflect new activity hooks
  module/documents/activity/summon.mjs
  module/documents/activity/utility.mjs
  wiki/Hooks.md
Labels: documentation

#4203 [#4135] Pre-create `MappingField` data before applying effects
  module/data/actor/templates/creature.mjs
  module/data/fields/mapping-field.mjs
  module/data/shared/roll-config-field.mjs
  module/documents/active-effect.mjs
Labels: bug, system: active effects

#4209 New icons for assorted SRD items
  packs/_source/items/equipment/stone-of-good-luck-luckstone.json
  packs/_source/items/loot/blanket.json
  packs/_source/items/loot/chalk.json
  packs/_source/items/loot/fishing-tackle.json
  packs/_source/items/loot/ink-bottle.json
  packs/_source/items/loot/merchants-scale.json
  packs/_source/items/trinket/block-and-tackle.json
  packs/_source/items/trinket/bowl-of-commanding-water-elementals.json
  packs/_source/items/trinket/brazier-of-commanding-fire-elementals.json
  packs/_source/items/trinket/broom-of-flying.json
  packs/_source/items/trinket/candle-of-invocation.json
  packs/_source/items/trinket/chime-of-opening.json
  packs/_source/items/trinket/deck-of-illusions.json
  packs/_source/items/trinket/deck-of-many-things.json
  packs/_source/items/trinket/dimensional-shackles.json
  packs/_source/items/trinket/folding-boat.json
  packs/_source/items/trinket/healers-kit.json
  packs/_source/items/trinket/horseshoes-of-speed.json
  packs/_source/items/trinket/hunting-trap.json
  packs/_source/items/trinket/portable-ram.json
  packs/_source/items/trinket/universal-solvent.json
Labels: compendium content

#3739 Update Modifying-Your-Game-with-Scripts.md
  wiki/Modifying-Your-Game-with-Scripts.md
Labels: documentation

#4211 [#4037] Various wiki fixes
  wiki/Activity-Type-Attack.md
  wiki/Activity-Type-Check.md
  wiki/Activity-Type-Damage.md
  wiki/Activity-Type-Heal.md
  wiki/Activity-Type-Save.md
  wiki/Activity-Type-Utility.md
  wiki/Hooks.md
  wiki/images/activities/attack-chat-dialog.jpg
Labels: documentation

#4212 Fix image paths on top-level activities page
  wiki/Activities.md
Labels: documentation

#4237 Fix grey-bag-of-tricks.json icon
  packs/_source/tables/grey-bag-of-tricks.json
Labels: compendium content

#4234 New icons for boots, hats etc.
  packs/_source/items/equipment/boots-of-elvenkind.json
  packs/_source/items/equipment/boots-of-levitation.json
  packs/_source/items/equipment/boots-of-speed.json
  packs/_source/items/equipment/boots-of-striding-and-springing.json
  packs/_source/items/equipment/hat-of-disguise.json
  packs/_source/items/equipment/helm-of-brilliance.json
  packs/_source/items/equipment/helm-of-comprehending-languages.json
  packs/_source/items/equipment/helm-of-telepathy.json
  packs/_source/items/equipment/helm-of-teleportation.json
  packs/_source/items/equipment/slippers-of-spider-climbing.json
  packs/_source/items/equipment/winged-boots.json
Labels: compendium content

#4231 Update icons of Equipment Packs
  packs/_source/items/container/alms-box/_container.json
  packs/_source/items/equipment-packs/burglars-pack/_container.json
  packs/_source/items/equipment-packs/burglars-pack/ball-bearings.json
  packs/_source/items/equipment-packs/diplomats-pack/_container.json
  packs/_source/items/equipment-packs/diplomats-pack/fine-clothes.json
  packs/_source/items/equipment-packs/diplomats-pack/ink-bottle.json
  packs/_source/items/equipment-packs/diplomats-pack/map-case/_container.json
  packs/_source/items/equipment-packs/diplomats-pack/scroll-case/_container.json
  packs/_source/items/equipment-packs/dungeoneers-pack/_container.json
  packs/_source/items/equipment-packs/entertainers-pack/costume-clothes.json
  packs/_source/items/equipment-packs/priests-pack/_container.json
  packs/_source/items/equipment-packs/priests-pack/alms-box/_container.json
  packs/_source/items/equipment-packs/priests-pack/blanket.json
  packs/_source/items/equipment-packs/scholars-pack/_container.json
  packs/_source/items/equipment-packs/scholars-pack/book-of-lore.json
  packs/_source/items/equipment-packs/scholars-pack/ink-bottle.json
Labels: compendium content

#4226 New icons for hand and eyewear
  packs/_source/items/equipment/bracers-of-archery.json
  packs/_source/items/equipment/bracers-of-defense.json
  packs/_source/items/equipment/eyes-of-charming.json
  packs/_source/items/equipment/eyes-of-minute-seeing.json
  packs/_source/items/equipment/eyes-of-the-eagle.json
  packs/_source/items/equipment/gauntlets-of-ogre-power.json
  packs/_source/items/equipment/gloves-of-missile-snaring.json
  packs/_source/items/equipment/gloves-of-swimming-and-climbing.json
  packs/_source/items/equipment/goggles-of-night.json
Labels: compendium content

#4255 New icons for Carpets, Cubes, Ropes, etc.
  packs/_source/items/equipment-packs/burglars-pack/rations.json
  packs/_source/items/equipment-packs/dungeoneers-pack/rations.json
  packs/_source/items/equipment-packs/entertainers-pack/rations.json
  packs/_source/items/equipment-packs/explorers-pack/rations.json
  packs/_source/items/equipment-packs/priests-pack/block-of-incense.json
  packs/_source/items/equipment-packs/priests-pack/rations.json
  packs/_source/items/food/feed.json
  packs/_source/items/food/rations.json
  packs/_source/items/loot/block-of-incense.json
  packs/_source/items/loot/stick-of-incense.json
  packs/_source/items/trinket/carpet-of-flying-3x5.json
  packs/_source/items/trinket/carpet-of-flying-4x6.json
  packs/_source/items/trinket/carpet-of-flying-5x7.json
  packs/_source/items/trinket/carpet-of-flying-6x9.json
  packs/_source/items/trinket/cubic-gate.json
  packs/_source/items/trinket/instant-fortress.json
  packs/_source/items/trinket/rope-of-climbing.json
  packs/_source/items/trinket/rope-of-entanglement.json
  packs/_source/tables/carpet-of-flying.json
Labels: compendium content

#4228 New container icons
  packs/_source/items/container/backpack/_container.json
  packs/_source/items/container/bag-of-devouring/_container.json
  packs/_source/items/container/bag-of-holding/_container.json
  packs/_source/items/container/basket/_container.json
  packs/_source/items/container/component-pouch/_container.json
  packs/_source/items/container/flask/_container.json
  packs/_source/items/container/handy-haversack/_container.json
  packs/_source/items/container/jug/_container.json
  packs/_source/items/container/pouch/_container.json
  packs/_source/items/container/tankard/_container.json
  packs/_source/items/trinket/alchemy-jug.json
Labels: compendium content

#4232 add null guard around ammoUpdate
  module/documents/activity/attack.mjs
Labels: bug

#4268 Fix some items missing activities migrations.
  module/data/activity/base-activity.mjs
  module/data/item/templates/activities.mjs
  module/documents/item.mjs
  system.json
Labels: bug, migration

#4273 [#4235] Fix issue with header clipping
  less/v2/apps.less
  less/v2/items.less
Labels: bug, ui

#4267 Fix bracers-of-defense icon
  packs/_source/items/equipment/bracers-of-defense.json
Labels: compendium content

#4269 Re-shuffle languages based on 2024 rules. Add Common Sign Language.
  dnd5e.mjs
  lang/en.json
  module/config.mjs
  module/data/advancement/trait.mjs
Labels: feature request

#4277 [#4276] Fix effect bug caused by `persistSourceMigration`
  module/migration.mjs
Labels: bug, migration

#4302 Fix activity sheet crashing when AEs are deleted on the parent item.
  module/applications/activity/activity-sheet.mjs
  module/applications/components/effects.mjs
  module/documents/active-effect.mjs
Labels: bug

#4299 [#4278, #4279, #4297] Fix concentration from activities
  module/data/shared/duration-field.mjs
  module/documents/active-effect.mjs
  module/documents/activity/mixin.mjs
  module/documents/actor/actor.mjs
Labels: bug, system: activities

#4304 Update concentration hooks to include activity
  wiki/Hooks.md
Labels: documentation

#4300 Some additional chat card polish.
  lang/en.json
  module/data/activity/attack-data.mjs
  module/documents/activity/mixin.mjs
  module/documents/chat-message.mjs
Labels: ui, ux

#4306 Fix effects tray appearing on attack and damage roll cards.
  module/documents/chat-message.mjs
Labels: bug

#4329 [#4316] Fix legacy translations
  dnd5e.mjs
Labels: bug, localization

#4372 [#4358] Fix chat pills not showing properties from the correct activity
  module/data/abstract.mjs
  module/data/activity/base-activity.mjs
  module/documents/activity/mixin.mjs
  module/documents/item.mjs
Labels: bug, system: activities

#4401 [#4376] Sort activities on initialisation
  module/applications/activity/activity-choice-dialog.mjs
  module/applications/item/item-sheet-2.mjs
  module/data/fields/activities-field.mjs
  module/documents/item.mjs
Labels: bug, system: activities

#4388 Allow legacy system.ability to transfer on enchantment effects
  module/data/active-effect/enchantment.mjs
Labels: system: enchantment

#4345 [#2902] Flame Tongue swords
  packs/_source/items/weapon/flame-tongue-greatsword.json
  packs/_source/items/weapon/flame-tongue-longsword.json
  packs/_source/items/weapon/flame-tongue-rapier.json
  packs/_source/items/weapon/flame-tongue-scimitar.json
  packs/_source/items/weapon/flame-tongue-shortsword.json
Labels: compendium content

#4346 [#861] Null avatar of death cr
  packs/_source/monsters/undead/avatar-of-death.json
Labels: compendium content

#4347 [#4342, #4343] Update hempen and silk ropes
  packs/_source/items/trinket/hempen-rope-50-ft.json
  packs/_source/items/trinket/silk-rope-50-ft.json
Labels: compendium content

#4348 [#4341] Wand of Secrets
  packs/_source/items/wand/wand-of-secrets.json
Labels: compendium content

#4371 Fix for `Glass Bottle` capacity and `Hourglass` description
  packs/_source/items/container/glass-bottle/_container.json
  packs/_source/items/loot/hourglass.json
Labels: compendium content

#4344 Savage Attacks AE
  packs/_source/races/orc/orc-features/savage-attacks.json
Labels: compendium content

#4349 [#4339] Bag of Beans item and table updates
  packs/_source/items/trinket/bag-of-beans.json
  packs/_source/tables/bag-of-beans.json
Labels: compendium content

#4447 [#3879] Remove NPC check in prepared spell filtering
  module/applications/actor/base-sheet.mjs
Labels: bug
