Repository foundryvtt/dnd5e, pull requests merged in 2024-08, with the labels that each got.

#3906 [#1964] Move use method from item to activity
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/activity-usage-dialog.mjs
  module/data/item/feat.mjs
  module/documents/activity/mixin.mjs
  module/documents/item.mjs
  templates/activity/parts/activity-consumption.hbs
  templates/chat/activity-card.hbs
  templates/chat/item-card.hbs
Labels: epic, in progress, api, ux, system: activities

#3928 [#1964] Add arbitrary roll to `UtilityActivity`
  lang/en.json
  module/applications/activity/_module.mjs
  module/applications/activity/utility-sheet.mjs
  module/data/activity/_module.mjs
  module/data/activity/utility-data.mjs
  module/documents/activity/utility.mjs
  templates/activity/utility-effect.hbs
Labels: feature request, system: activities

#3929 [#1964, #2349] Allow placing templates from activities
  module/canvas/ability-template.mjs
  module/documents/activity/mixin.mjs
  module/documents/mixins/pseudo-document.mjs
Labels: bug, api, system: activities

#3927 [#1964] Add method to localize schemas in `ArrayField`s
  dnd5e.mjs
  lang/en.json
  module/data/activity/base-activity.mjs
  module/data/shared/uses-field.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/summon.mjs
  templates/activity/parts/damage-parts.hbs
  templates/activity/parts/summon-profiles.hbs
Labels: localization, system: activities

#3925 Item & Container sheet V2 skeleton & header matter
  dnd5e.mjs
  lang/en.json
  less/dnd5e.less
  less/v2/apps.less
  less/v2/items.less
  module/applications/_module.mjs
  module/applications/actor/_module.mjs
  module/applications/fields.mjs
  module/applications/item/_module.mjs
  module/applications/item/container-sheet-2.mjs
  module/applications/item/item-sheet-2.mjs
  module/applications/item/item-sheet.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/data/abstract.mjs
  module/data/item/background.mjs
  module/data/item/class.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/loot.mjs
  module/data/item/race.mjs
  module/data/item/spell.mjs
  module/data/item/subclass.mjs
  module/data/item/templates/physical-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  templates/items/item-sheet-2.hbs
Labels: ui, in progress, ux

#3926 [#3911] Add `SaveActivity` data and sheet
  icons/LICENSE
  icons/svg/activity/save.svg
  lang/en.json
  less/v2/activities.less
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/attack-sheet.mjs
  module/applications/activity/save-sheet.mjs
  module/applications/activity/summon-sheet.mjs
  module/config.mjs
  module/data/activity/_module.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/fields/applied-effect-field.mjs
  module/data/activity/save-data.mjs
  module/documents/activity/_module.mjs
  module/documents/activity/save.mjs
  templates/activity/parts/activity-effects.hbs
  templates/activity/parts/damage-parts.hbs
  templates/activity/parts/save-damage.hbs
  templates/activity/parts/save-details.hbs
  templates/activity/parts/save-effect-settings.hbs
  templates/activity/parts/summon-profiles.hbs
  templates/activity/save-effect.hbs
Labels: epic, ui, feature request, in progress, system: activities

#3935 [#3914] Add `EnchantActivity` data and sheet
  lang/en.json
  module/applications/activity/_module.mjs
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/enchant-sheet.mjs
  module/applications/activity/summon-sheet.mjs
  module/applications/components/effects.mjs
  module/applications/item/enchantment-config.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/activity/_module.mjs
  module/data/activity/enchant-data.mjs
  module/data/item/fields/enchantment-field.mjs
  module/documents/active-effect.mjs
  module/documents/activity/_module.mjs
  module/documents/activity/enchant.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  system.json
  templates/activity/enchant-effect.hbs
  templates/activity/parts/activity-effects.hbs
  templates/activity/parts/enchant-enchantments.hbs
  templates/activity/parts/enchant-restrictions.hbs
  templates/activity/parts/summon-profiles.hbs
  templates/actors/limited-sheet-2.hbs
  templates/apps/enchantment-config.hbs
  templates/items/parts/item-action.hbs
Labels: epic, ui, feature request, in progress, system: enchantment, system: activities

#3934 [#3912] Add `DamageActivity` & `HealingActivity` data & sheets
  icons/LICENSE
  icons/svg/activity/damage.svg
  icons/svg/activity/healing.svg
  lang/en.json
  module/applications/activity/_module.mjs
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/attack-sheet.mjs
  module/applications/activity/damage-sheet.mjs
  module/applications/activity/healing-sheet.mjs
  module/applications/activity/save-sheet.mjs
  module/config.mjs
  module/data/activity/_module.mjs
  module/data/activity/damage-data.mjs
  module/data/activity/healing-data.mjs
  module/data/shared/damage-field.mjs
  module/documents/activity/_module.mjs
  module/documents/activity/damage.mjs
  module/documents/activity/healing.mjs
  module/documents/activity/mixin.mjs
  templates/activity/damage-effect.hbs
  templates/activity/healing-effect.hbs
  templates/activity/parts/attack-damage.hbs
  templates/activity/parts/damage-damage.hbs
  templates/activity/parts/damage-part.hbs
  templates/activity/parts/damage-parts.hbs
  templates/activity/parts/healing-damage.hbs
  templates/activity/parts/save-damage.hbs
Labels: epic, ui, feature request, in progress, system: activities

#3936 Item sheets V2 Description tab
  lang/en.json
  less/dnd5e.less
  less/v2/dark/items.less
  less/v2/items.less
  module/applications/item/item-sheet.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/data/item/equipment.mjs
  module/data/item/spell.mjs
  module/data/item/weapon.mjs
  module/utils.mjs
  templates/items/item-sheet-2.hbs
  templates/items/parts/item-description2.hbs
Labels: ui, ux

#3944 Corrected roll formula simplification for display purposes.
  module/dice/simplify-roll-formula.mjs
Labels: bug, system: dice

#3943 Resolve additional deprecated issues with V12
  dnd5e.mjs
  less/v1/advancement.less
  module/applications/actor/sheet-mixin.mjs
  module/canvas/token-placement.mjs
  module/data/item/fields/summons-field.mjs
  module/dice/aggregate-damage-rolls.mjs
  module/dice/d20-roll.mjs
  module/dice/damage-roll.mjs
  module/dice/simplify-roll-formula.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  module/utils.mjs
  templates/advancement/parts/advancement-controls.hbs
Labels: compatibility

#3946 Item Sheet V2: Container Contents tab
  less/v2/items.less
  module/applications/item/container-sheet-2.mjs
  module/applications/item/item-sheet-2.mjs
  module/applications/item/sheet-v2-mixin.mjs
  templates/items/item-sheet-2.hbs
Labels: ui, ux

#3884 Document the Enchantment active effects
  wiki/Enchantment.md
Labels: documentation

#3950 Item Sheet V2: Advancement tab
  icons/LICENSE
  icons/svg/multiclass.svg
  icons/svg/original-class.svg
  lang/en.json
  less/v2/dark/items.less
  less/v2/items.less
  less/v2/journal.less
  module/applications/advancement/advancement-selection.mjs
  module/applications/components/item-list-controls.mjs
  module/applications/item/item-sheet-2.mjs
  module/applications/item/item-sheet.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/config.mjs
  module/documents/advancement/ability-score-improvement.mjs
  module/documents/advancement/advancement.mjs
  module/documents/advancement/hit-points.mjs
  module/documents/advancement/item-choice.mjs
  module/documents/advancement/item-grant.mjs
  module/documents/advancement/scale-value.mjs
  module/documents/advancement/size.mjs
  module/documents/advancement/trait.mjs
  module/utils.mjs
  templates/items/item-sheet-2.hbs
  templates/items/parts/item-advancement2.hbs
Labels: ui, ux, system: advancement

#3951 [#1964] Remove Action & Activated Effect data & add shims
  lang/en.json
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/damage-data.mjs
  module/data/activity/enchant-data.mjs
  module/data/activity/summon-data.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/spell.mjs
  module/data/item/templates/action.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/templates/activities.mjs
  module/data/item/templates/mountable.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/data/shared/activation-field.mjs
  module/data/shared/duration-field.mjs
  module/data/shared/range-field.mjs
  module/data/shared/target-field.mjs
  module/documents/activity/mixin.mjs
  templates/activity/parts/activity-identity.hbs
  templates/activity/parts/attack-damage.hbs
  templates/activity/parts/attack-details.hbs
  templates/activity/parts/damage-damage.hbs
Labels: in progress, api, system: activities

#3956 [#1964] Migrate weapon base & versatile damage
  module/data/activity/attack-data.mjs
  module/data/item/weapon.mjs
Labels: migration, system: activities

#3957 [#1964] Migrate spell activation & target
  module/data/activity/base-activity.mjs
  module/data/item/spell.mjs
Labels: migration, system: activities

#3954 Item Sheet V2: Add equipped/identified toggles
  less/v2/actors.less
  less/v2/apps.less
  less/v2/items.less
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
Labels: ui, ux

#3959 [#1964] Prepare final formulas and labels
  lang/en.json
  module/applications/activity/activity-sheet.mjs
  module/config.mjs
  module/data/activity/base-activity.mjs
  module/data/item/spell.mjs
  module/data/item/templates/activities.mjs
  module/data/item/weapon.mjs
  module/data/shared/activation-field.mjs
  module/data/shared/duration-field.mjs
  module/data/shared/range-field.mjs
  module/data/shared/target-field.mjs
  module/data/shared/uses-field.mjs
  module/documents/activity/mixin.mjs
  module/utils.mjs
  templates/activity/parts/activity-consumption.hbs
  templates/activity/parts/activity-targeting.hbs
  templates/activity/parts/activity-time.hbs
Labels: epic, in progress, api, system: activities

#3960 [#1964] Copy inferred data from items to activity, add overrides
  lang/en.json
  module/applications/activity/activity-sheet.mjs
  module/data/activity/base-activity.mjs
  module/data/item/spell.mjs
  templates/activity/parts/activity-targeting.hbs
  templates/activity/parts/activity-time.hbs
Labels: ui, in progress, system: activities

#3961 [#1964] Add inferred attack data, fix bug in save sheet
  lang/en.json
  less/v2/forms.less
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/attack-sheet.mjs
  module/config.mjs
  module/data/abstract.mjs
  module/data/activity/attack-data.mjs
  module/data/item/spell.mjs
  module/data/item/weapon.mjs
  module/documents/item.mjs
  templates/activity/parts/damage-part.hbs
  templates/activity/parts/damage-parts.hbs
  templates/activity/parts/save-damage.hbs
  templates/activity/parts/save-details.hbs
Labels: system: activities

#3962 Item Sheet V2: Activities tab
  lang/en.json
  less/v2/dark/items.less
  less/v2/forms.less
  less/v2/items.less
  less/v2/sheets.less
  module/applications/item/item-sheet-2.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/documents/item.mjs
  module/utils.mjs
  templates/items/item-sheet-2.hbs
  templates/items/parts/item-activities.hbs
Labels: ui, ux

#3967 Item Sheet V2: Non-Activated Items
  lang/en.json
  less/dnd5e.less
  less/v2/dark/actors.less
  less/v2/dark/apps.less
  less/v2/dark/forms.less
  less/v2/dark/items.less
  less/v2/dark/journal.less
  less/v2/forms.less
  less/v2/items.less
  less/v2/journal.less
  module/applications/fields.mjs
  module/applications/item/item-sheet-2.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/data/item/background.mjs
  module/data/item/class.mjs
  module/data/item/container.mjs
  module/data/item/loot.mjs
  module/data/item/race.mjs
  module/data/item/subclass.mjs
  module/data/item/templates/starting-equipment.mjs
  module/utils.mjs
  templates/items/details/details-background.hbs
  templates/items/details/details-class.hbs
  templates/items/details/details-container.hbs
  templates/items/details/details-loot.hbs
  templates/items/details/details-species.hbs
  templates/items/details/details-spellcasting.hbs
  templates/items/details/details-starting-equipment.hbs
  templates/items/details/details-subclass.hbs
  templates/items/item-sheet-2.hbs
  templates/items/parts/item-details.hbs
Labels: ui, ux

#3964 [#1964] Remove activation-based preparation from items
  lang/en.json
  module/applications/activity/attack-sheet.mjs
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/damage-data.mjs
  module/data/activity/heal-data.mjs
  module/data/activity/save-data.mjs
  module/data/item/class.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/spell.mjs
  module/data/item/templates/activities.mjs
  module/data/item/weapon.mjs
  module/data/shared/activation-field.mjs
  module/data/shared/duration-field.mjs
  module/data/shared/range-field.mjs
  module/data/shared/target-field.mjs
  module/data/shared/uses-field.mjs
  module/documents/activity/mixin.mjs
  module/documents/item.mjs
  module/utils.mjs
  templates/activity/parts/attack-details.hbs
  templates/activity/parts/save-details.hbs
Labels: system: activities

#3974 [#1964] Migrate chat message flags to new structure, add shims
  module/applications/item/ability-use-dialog.mjs
  module/documents/active-effect.mjs
  module/documents/activity/mixin.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
Labels: api, migration

#3970 [#1964] Add buttons to activity messages, rollFormula for Utility
  module/documents/activity/mixin.mjs
  module/documents/activity/utility.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  templates/chat/activity-card.hbs
Labels: api, system: dice, system: activities

#3972 Item Sheets V2: Activated Items
  lang/en.json
  less/v2/forms.less
  module/applications/item/item-sheet-2.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/fields/enchantment-field.mjs
  module/data/item/spell.mjs
  module/data/item/templates/activities.mjs
  module/data/item/templates/mountable.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/utils.mjs
  templates/items/details/details-consumable.hbs
  templates/items/details/details-damage.hbs
  templates/items/details/details-equipment.hbs
  templates/items/details/details-feat.hbs
  templates/items/details/details-mountable.hbs
  templates/items/details/details-spell.hbs
  templates/items/details/details-tool.hbs
  templates/items/details/details-uses.hbs
  templates/items/details/details-weapon.hbs
  templates/items/item-sheet-2.hbs
Labels: ui, ux

#3811 [#1021, #2978] Automatically calculated spell preparation limits
  lang/en.json
  module/data/advancement/spell-config.mjs
  module/data/item/_module.mjs
  module/data/item/class.mjs
  module/data/item/fields/spellcasting-field.mjs
  module/data/item/spell.mjs
  module/data/item/subclass.mjs
  packs/_source/classes/cleric.json
  packs/_source/classes/druid.json
  packs/_source/classes/paladin.json
  packs/_source/classes/wizard.json
  templates/advancement/parts/advancement-spell-config.hbs
  templates/items/details/details-spell.hbs
  templates/items/details/details-spellcasting.hbs
Labels: feature request

#3977 [#1964] Add options to utility roll
  lang/en.json
  module/applications/activity/utility-sheet.mjs
  module/data/activity/utility-data.mjs
  module/documents/activity/utility.mjs
  templates/activity/utility-effect.hbs
  templates/activity/utility-identity.hbs
Labels: system: dice, system: activities

#3975 [#3910] Move rollAttack to AttackActivity
  module/data/activity/attack-data.mjs
  module/data/item/spell.mjs
  module/data/item/templates/activities.mjs
  module/data/item/weapon.mjs
  module/dice/d20-roll.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/utility.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
Labels: in progress, api, system: dice, system: activities

#3976 [#3911] Add Saving Throw button for `SaveActivity`
  less/v2/chat.less
  module/data/item/feat.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/save.mjs
  module/documents/activity/utility.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  module/enrichers.mjs
  module/utils.mjs
  templates/chat/activity-card.hbs
Labels: system: dice, system: activities

#3978 [#3912] Implement damage rolls for Damage & Heal activities
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/damage-data.mjs
  module/data/activity/heal-data.mjs
  module/dice/damage-roll.mjs
  module/documents/activity/damage.mjs
  module/documents/activity/heal.mjs
  module/documents/activity/mixin.mjs
  module/documents/item.mjs
Labels: in progress, api, system: dice, system: activities

#3979 [#3911] Add damage rolls for `SaveActivity`
  lang/en.json
  module/data/activity/damage-data.mjs
  module/data/activity/save-data.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/save.mjs
  module/documents/activity/utility.mjs
  module/documents/chat-message.mjs
Labels: system: dice, system: activities

#3888 Keep the original token's sight.enabled value when transforming an actor
  module/documents/actor/actor.mjs
Labels: bug

#3980 [#3910] Add damage rolls for `AttackActivity`
  module/data/activity/attack-data.mjs
  module/data/shared/damage-field.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/damage.mjs
  module/documents/item.mjs
Labels: api, system: dice, system: activities

#3800 [#3799] Add option to register source books directly in manifest
  dnd5e.mjs
  module/module-registration.mjs
Labels: api

#3985 Fix copy/paste error in magical armor example
  wiki/Enchantment.md
Labels: documentation

#3986 [#1964] Implement initial activity usage dialog
  lang/en.json
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/dice/roll-configuration-dialog.mjs
  module/config.mjs
  module/data/activity/base-activity.mjs
  module/data/shared/uses-field.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/utility.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/utils.mjs
  templates/activity/activity-usage-concentration.hbs
  templates/activity/activity-usage-consumption.hbs
  templates/activity/activity-usage-creation.hbs
  templates/activity/activity-usage-notes.hbs
  templates/activity/activity-usage-scaling.hbs
  templates/activity/parts/activity-consumption.hbs
Labels: ui, in progress, ux, system: activities

#3990 Activities: Drag-drop reordering, copying, and context menus
  lang/en.json
  less/v2/items.less
  module/applications/item/item-sheet-2.mjs
  module/applications/item/item-sheet.mjs
  module/data/activity/base-activity.mjs
  module/data/item/weapon.mjs
  templates/items/parts/item-activities.hbs
Labels: ux

#3987 [#1964] Properly scale items when activated
  module/applications/activity/activity-usage-dialog.mjs
  module/data/abstract.mjs
  module/data/activity/base-activity.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/item/spell.mjs
  module/data/shared/damage-field.mjs
  module/documents/_module.mjs
  module/documents/activity/mixin.mjs
  module/documents/item.mjs
  module/documents/scaling.mjs
Labels: system: activities

#3880 [#1192] Hide dex tiebreakers in combat tracker
  module/applications/combat/combat-tracker.mjs
Labels: ui

#3918 Add armor class minimum property
  module/data/actor/templates/attributes.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
Labels: feature request

#3866 [#3865] Add setting for default skills.
  lang/en.json
  module/applications/actor/npc-sheet-2.mjs
  module/settings.mjs
Labels: feature request

#3876 [#2010] Add bloodied status effect that auto-applies at 50% HP
  icons/LICENSE
  icons/svg/statuses/bloodied.svg
  lang/en.json
  module/config.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
  module/settings.mjs
Labels: feature request

#3905 [#3596] Remove multiplication constant from damage tooltips
  module/documents/chat-message.mjs
Labels: bug

#3770 [#2129] Add additional hint for dice scale value & <copyable-text>
  lang/en.json
  less/elements.less
  less/v1/advancement.less
  module/applications/advancement/scale-value-config.mjs
  module/applications/components/_module.mjs
  module/applications/components/copyable-text.mjs
  templates/advancement/scale-value-config.hbs
Labels: ux, system: advancement

#3698 [#3530] Evaluate die maximum in damage-roll.mjs
  module/dice/basic-roll.mjs
  module/dice/damage-roll.mjs
Labels: bug, system: dice

#3826 [#3443] Holding shift as GM shows original delete icon for chat messages
  dnd5e.mjs
  less/v2/chat.less
  module/documents/chat-message.mjs
Labels: ui, ux

#3997 [#3920, #3982] Add rules version setting, implement new exhaustion
  lang/en.json
  module/config.mjs
  module/data/activity/attack-data.mjs
  module/data/actor/templates/attributes.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/hit-dice.mjs
  module/settings.mjs
Labels: feature request

#3872 [#2201, #2550, #2551] Uncap XP tracking & add epic boon calculation
  lang/en.json
  less/v2/character.less
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/group-sheet.mjs
  module/applications/award.mjs
  module/config.mjs
  module/data/actor/character.mjs
  module/migration.mjs
  module/settings.mjs
  module/utils.mjs
  templates/actors/character-sheet-2.hbs
  ui/boon-badge.webp
Labels: feature request, api

#3999 [#2212, #3998] Add primary ability to classes
  lang/en.json
  less/v2/forms.less
  module/applications/journal/class-page-sheet.mjs
  module/data/item/class.mjs
  templates/items/class.hbs
  templates/items/details/details-class.hbs
  templates/journal/page-class-view.hbs
Labels: feature request

#3992 [#1964] Handle activity resource & spell slot consumption
  lang/en.json
  module/applications/activity/activity-sheet.mjs
  module/config.mjs
  module/data/activity/_module.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/fields/consumption-targets-field.mjs
  module/documents/activity/mixin.mjs
  module/documents/item.mjs
Labels: system: activities

#3994 [#3914] Move enchanting functionality into `EnchantActivity`
  dnd5e.mjs
  icons/LICENSE
  icons/svg/activity/enchant.svg
  lang/en.json
  module/applications/activity/_module.mjs
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/activity/enchant-usage-dialog.mjs
  module/applications/components/effects.mjs
  module/applications/components/enchantment-application.mjs
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/item-sheet.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/config.mjs
  module/data/activity/enchant-data.mjs
  module/data/item/feat.mjs
  module/data/item/fields/enchantment-field.mjs
  module/data/item/templates/activities.mjs
  module/documents/active-effect.mjs
  module/documents/activity/_module.mjs
  module/documents/activity/enchant.mjs
  module/documents/activity/mixin.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  module/registry.mjs
  templates/activity/enchant-usage-creation.hbs
  templates/apps/ability-use.hbs
  templates/items/details/details-feat.hbs
  templates/items/feat.hbs
  templates/items/parts/item-action.hbs
Labels: ui, system: enchantment, system: activities

#3995 [#3913] Move summoning functionality into `SummonActivity`
  lang/en.json
  module/applications/activity/_module.mjs
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/activity/enchant-usage-dialog.mjs
  module/applications/activity/summon-usage-dialog.mjs
  module/applications/item/ability-use-dialog.mjs
  module/data/activity/summon-data.mjs
  module/data/item/fields/summons-field.mjs
  module/data/item/templates/activities.mjs
  module/documents/activity/summon.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/documents/token.mjs
  module/registry.mjs
  templates/activity/summon-usage-creation.hbs
  templates/items/parts/item-action.hbs
Labels: ui, system: summoning, system: activities

#4003 [#3983] Add weapon masteries to weapons & characters
  lang/en.json
  less/elements.less
  less/v2/actors.less
  less/v2/apps.less
  less/v2/dark/apps.less
  less/v2/dark/character.less
  less/v2/dark/forms.less
  less/v2/forms.less
  module/applications/actor/_module.mjs
  module/applications/actor/api/base-config-sheet.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/config/weapons-config.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/components/checkbox.mjs
  module/config.mjs
  module/data/actor/character.mjs
  module/data/item/race.mjs
  module/data/item/weapon.mjs
  module/utils.mjs
  templates/actors/config/weapons-config.hbs
  templates/items/details/details-weapon.hbs
Labels: ui, feature request, ux

#4004 [#3910, #3911, #3912] Add damage type selection to roll dialog
  module/data/activity/base-activity.mjs
  module/dice/damage-roll.mjs
  module/dice/dice.mjs
  module/documents/activity/mixin.mjs
  templates/chat/roll-dialog.hbs
Labels: ui, system: dice, system: activities

#4005 [#3910] Add attack mode selection, relay mode to damage rolls
  lang/en.json
  module/applications/components/enchantment-application.mjs
  module/config.mjs
  module/data/abstract.mjs
  module/data/activity/attack-data.mjs
  module/data/activity/enchant-data.mjs
  module/data/item/templates/activities.mjs
  module/data/item/weapon.mjs
  module/dice/d20-roll.mjs
  module/dice/dice.mjs
  module/documents/active-effect.mjs
  module/documents/activity/attack.mjs
  module/documents/chat-message.mjs
  module/registry.mjs
  templates/chat/roll-dialog.hbs
Labels: system: dice, system: activities

#3699 [#3590] Add additional enchantment restrictions
  lang/en.json
  module/applications/activity/enchant-sheet.mjs
  module/data/activity/enchant-data.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/loot.mjs
  module/data/item/templates/item-type.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/documents/activity/enchant.mjs
  templates/activity/parts/enchant-restrictions.hbs
Labels: feature request, system: enchantment

#4012 [#1866, #4011] Update ammo types, add ammo damage & type to weapon
  lang/en.json
  module/applications/activity/attack-sheet.mjs
  module/applications/item/item-sheet-2.mjs
  module/config.mjs
  module/data/activity/attack-data.mjs
  module/data/item/consumable.mjs
  module/data/item/weapon.mjs
  templates/items/details/details-consumable.hbs
  templates/items/details/details-damage.hbs
  templates/items/details/details-weapon.hbs
  templates/items/parts/item-activation.hbs
Labels: feature request, localization, system: activities

#4014 [#1039, #3268, #3314] Add ammo selection, consumption, & bonuses
  module/data/activity/attack-data.mjs
  module/data/item/weapon.mjs
  module/dice/d20-roll.mjs
  module/dice/dice.mjs
  module/documents/activity/attack.mjs
  templates/chat/roll-dialog.hbs
Labels: ui, feature request, ux, system: dice, system: activities

#4015 Activity Sheets: Attack
  lang/en.json
  less/v2/activities.less
  less/v2/apps.less
  less/v2/compendium-browser.less
  less/v2/dark/apps.less
  less/v2/dark/forms.less
  less/v2/forms.less
  less/v2/tooltips.less
  module/applications/activity/_module.mjs
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/save-sheet.mjs
  module/applications/api/application.mjs
  module/applications/fields.mjs
  module/applications/item/item-sheet-2.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/spell.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/utils.mjs
  templates/activity/parts/activity-consumption.hbs
  templates/activity/parts/activity-effects.hbs
  templates/activity/parts/activity-targeting.hbs
  templates/activity/parts/activity-time.hbs
  templates/activity/parts/attack-damage.hbs
  templates/activity/parts/attack-details.hbs
  templates/activity/parts/damage-part.hbs
  templates/activity/parts/damage-parts.hbs
  templates/items/details/details-damage.hbs
  templates/items/details/details-spell.hbs
  templates/shared/fields/field-activation.hbs
  templates/shared/fields/field-duration.hbs
  templates/shared/fields/field-range.hbs
  templates/shared/fields/field-targets.hbs
  templates/shared/fields/field-uses.hbs
  templates/shared/uses-recovery.hbs
  templates/shared/uses-values.hbs
Labels: ui, ux

#4016 [#1964] Re-implement uses recovery, adjust resting design
  lang/en.json
  module/config.mjs
  module/data/item/templates/activities.mjs
  module/data/shared/uses-field.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/hit-dice.mjs
Labels: api, system: activities

#4018 [#1964] Add back Place Template & Consume Resource buttons
  lang/en.json
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/components/enchantment-application.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/damage.mjs
  module/documents/activity/heal.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/save.mjs
  module/documents/activity/summon.mjs
  module/documents/activity/utility.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
Labels: ui, system: activities

#4019 [#1964] Tweak how activity migrations are performed
  module/data/activity/base-activity.mjs
  module/data/item/templates/activities.mjs
  module/documents/item.mjs
  module/migration.mjs
Labels: bug, migration, system: activities

#4020 [#1964] Migrate reach & versatile damage for non-weapons
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/damage-data.mjs
  module/data/activity/enchant-data.mjs
  module/data/activity/heal-data.mjs
  module/data/activity/save-data.mjs
  module/data/activity/summon-data.mjs
  module/data/activity/utility-data.mjs
  module/data/item/templates/activities.mjs
  module/data/item/weapon.mjs
  module/migration.mjs
Labels: migration, system: activities

#4023 [#1964] Migrate uses, fix recovery on charges items w/o formula
  module/data/item/templates/activities.mjs
  module/migration.mjs
Labels: migration, system: activities

#4028 [#4026, #4027] Cap concentration DC at 30, rename exotic languages
  lang/en.json
  module/documents/actor/actor.mjs
Labels: feature request, localization

#4022 Activity Sheets: Remainder
  lang/en.json
  less/dnd5e.less
  less/v2/activities.less
  less/v2/dark/activities.less
  less/v2/forms.less
  module/applications/activity/activity-sheet.mjs
  module/applications/fields.mjs
  module/utils.mjs
  templates/activity/attack-identity.hbs
  templates/activity/identity.hbs
  templates/activity/parts/damage-damage.hbs
  templates/activity/parts/damage-part.hbs
  templates/activity/parts/enchant-enchantments.hbs
  templates/activity/parts/enchant-restrictions.hbs
  templates/activity/parts/heal-healing.hbs
  templates/activity/parts/save-damage.hbs
  templates/activity/parts/summon-changes.hbs
  templates/activity/parts/summon-profiles.hbs
  templates/activity/summon-identity.hbs
  templates/activity/utility-effect.hbs
  templates/activity/utility-identity.hbs
  templates/items/details/details-consumable.hbs
  templates/items/details/details-weapon.hbs
  templates/shared/fields/field-damage.hbs
Labels: ui, ux, system: activities

#4025 [#4024] Add `CheckActivity` type for ability & tool checks
  icons/LICENSE
  icons/svg/activity/check.svg
  lang/en.json
  module/applications/activity/_module.mjs
  module/applications/activity/attack-sheet.mjs
  module/applications/activity/check-sheet.mjs
  module/applications/activity/save-sheet.mjs
  module/config.mjs
  module/data/activity/_module.mjs
  module/data/activity/attack-data.mjs
  module/data/activity/check-data.mjs
  module/data/activity/save-data.mjs
  module/data/item/templates/activities.mjs
  module/documents/activity/_module.mjs
  module/documents/activity/check.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/save.mjs
  module/documents/item.mjs
  module/enrichers.mjs
  system.json
  templates/activity/check-effect.hbs
  templates/activity/parts/check-details.hbs
  templates/activity/parts/save-details.hbs
Labels: feature request, system: activities

#4030 [#1964] Move concentration into activity duration
  lang/en.json
  module/config.mjs
  module/data/activity/base-activity.mjs
  module/data/item/spell.mjs
  module/documents/item.mjs
  templates/activity/parts/activity-time.hbs
Labels: system: activities

#4040 Restore hint text to label-top form groups.
  lang/en.json
  less/v2/dark/forms.less
  less/v2/forms.less
  module/applications/api/application.mjs
  templates/activity/parts/activity-consumption.hbs
Labels: ui

#4035 [#1964] Support activities on spells that don't consume slots
  lang/en.json
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/activity-usage-dialog.mjs
  module/data/activity/base-activity.mjs
  module/documents/activity/mixin.mjs
  templates/activity/parts/activity-consumption.hbs
Labels: feature request, system: activities

#4033 [#1964] Adjust styling of usage, switch to <dialog> element
  less/v2/activities.less
  less/v2/apps.less
  less/v2/compendium-browser.less
  less/v2/dark/apps.less
  less/v2/dark/forms.less
  less/v2/forms.less
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/activity/summon-usage-dialog.mjs
  module/applications/api/application.mjs
  module/applications/fields.mjs
  templates/activity/activity-usage-concentration.hbs
  templates/activity/activity-usage-consumption.hbs
  templates/activity/activity-usage-creation.hbs
  templates/activity/activity-usage-scaling.hbs
  templates/activity/enchant-usage-creation.hbs
  templates/activity/summon-usage-creation.hbs
Labels: ui, system: activities

#4034 [#1964] Communicate consumption costs in usage dialog
  lang/en.json
  less/v2/activities.less
  less/v2/dark/activities.less
  module/applications/activity/activity-usage-dialog.mjs
  module/config.mjs
  module/data/activity/fields/consumption-targets-field.mjs
  templates/activity/activity-usage-consumption.hbs
Labels: ui, system: activities

#4044 [#2978] Add spell preparation count to character sheet.
  less/v2/character.less
  module/applications/actor/character-sheet-2.mjs
  module/data/item/class.mjs
  module/data/item/spell.mjs
  module/data/item/subclass.mjs
  module/documents/actor/actor.mjs
  templates/actors/tabs/creature-spells.hbs
  templates/items/details/details-spellcasting.hbs
Labels: ui, ux

#4049 [#1964] Extend [[/item]] enricher to trigger activities
  lang/en.json
  module/documents/macro.mjs
  module/enrichers.mjs
Labels: feature request, system: enrichers, system: activities

#4042 BasicRoll Configuration styling
  icons/svg/dice/d10.svg
  icons/svg/dice/d12.svg
  icons/svg/dice/d20.svg
  icons/svg/dice/d4.svg
  icons/svg/dice/d6.svg
  icons/svg/dice/d8.svg
  less/v2/apps.less
  less/v2/chat.less
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/api/application.mjs
  module/applications/dice/roll-configuration-dialog.mjs
  module/documents/activity/utility.mjs
  templates/dice/roll-formulas.hbs
Labels: ui, ux

#4041 [#1964] Update spell scroll creation to work with activities
  module/config.mjs
  module/documents/activity/mixin.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
Labels: bug, system: activities

#4047 [#3836, #3853] Add Has Spellcasting & Class filters to subclasses
  dnd5e.mjs
  module/data/item/subclass.mjs
  module/registry.mjs
Labels: feature request, api, system: compendium browser

#4046 [#3786] Add system for consolidated spell lists
  module/module-registration.mjs
  module/registry.mjs
  system.json
Labels: api

#4053 Activities Migration: Conditionaly check for save
  module/data/item/templates/activities.mjs
Labels: bug, migration, system: activities

#4045 [#4043] Refresh Create Scroll UI, allow custom spell values
  lang/en.json
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/api/dialog.mjs
  module/applications/item/create-scroll-dialog.mjs
  module/data/item/class.mjs
  module/data/item/fields/spellcasting-field.mjs
  module/data/item/subclass.mjs
  module/documents/item.mjs
  templates/apps/spell-scroll-dialog.hbs
Labels: ui, feature request

#4055 [#1964] Remember attack mode, ammunition, & damage types
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/dice/damage-roll.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/mixin.mjs
Labels: ux, system: activities

#4058 Add activity choice dialog
  icons/svg/mouse-left.svg
  lang/en.json
  less/v2/activities.less
  less/v2/apps.less
  less/v2/items.less
  less/v2/tooltips.less
  module/applications/activity/_module.mjs
  module/applications/activity/activity-choice-dialog.mjs
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/api/application.mjs
  module/applications/components/inventory.mjs
  module/documents/item.mjs
  module/enrichers.mjs
  templates/activity/activity-choices.hbs
  templates/items/parts/item-tooltip.hbs
Labels: system: activities

#4052 [#1012, #1229] Display classes providing spells on spell sheet
  less/v2/items.less
  module/data/item/spell.mjs
  module/registry.mjs
Labels: ui, feature request, api

#4064 [#4063] Add cylinder AoE type, split AoE list into sections
  lang/en.json
  module/config.mjs
  templates/shared/fields/field-targets.hbs
Labels: ui, feature request

#4062 [#1964] Automatically create activities on new Weapons & Tools
  module/data/activity/base-activity.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
Labels: ux, system: activities

#4054 [#1964] Re-implement effect application for activities
  less/v2/chat.less
  module/applications/components/_module.mjs
  module/applications/components/damage-application.mjs
  module/applications/components/effect-application.mjs
  module/applications/components/targeted-application-mixin.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/enchant-data.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/mixin.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  templates/chat/activity-card.hbs
Labels: ui, ux, system: activities

#4066 [#3701] Set spellcasting ability when adding new class to character
  module/data/actor/templates/attributes.mjs
  module/data/item/class.mjs
  module/data/item/subclass.mjs
  module/documents/item.mjs
Labels: ux

#4065 [#1011] Adjust emanation template size when placing
  module/applications/activity/activity-sheet.mjs
  module/applications/item/item-sheet-2.mjs
  module/canvas/ability-template.mjs
  module/config.mjs
  module/data/shared/target-field.mjs
Labels: feature request, ux

#4067 [#1012] Select source class for spells when added to sheet
  module/data/item/spell.mjs
Labels: feature request, ux

#4073 Implement 2024 shape-shift options for adding temp HP, and retaining HP, HD, and creature type.
  dnd5e.mjs
  lang/en.json
  module/config.mjs
  module/documents/actor/actor.mjs
Labels: api

#4072 [#1407] Add Subclass advancement & selection interface on sheet
  icons/LICENSE
  icons/svg/subclass.svg
  lang/en.json
  less/v2/actors.less
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/advancement/_module.mjs
  module/applications/advancement/advancement-flow.mjs
  module/applications/advancement/subclass-flow.mjs
  module/config.mjs
  module/documents/advancement/_module.mjs
  module/documents/advancement/subclass.mjs
  packs/_source/classes/barbarian.json
  packs/_source/classes/bard.json
  packs/_source/classes/cleric.json
  packs/_source/classes/druid.json
  packs/_source/classes/fighter.json
  packs/_source/classes/monk.json
  packs/_source/classes/paladin.json
  packs/_source/classes/ranger.json
  packs/_source/classes/rogue.json
  packs/_source/classes/sorcerer.json
  packs/_source/classes/warlock.json
  packs/_source/classes/wizard.json
  templates/actors/parts/actor-classes.hbs
  templates/advancement/advancement-flow.hbs
  templates/journal/page-class-view.hbs
Labels: feature request, ux, system: advancement

#4074 [#3983] Add weapon mastery support to `TraitAdvancement`
  lang/en.json
  module/applications/advancement/trait-config.mjs
  module/config.mjs
  module/documents/actor/select-choices.mjs
  module/documents/actor/trait.mjs
  module/documents/advancement/trait.mjs
Labels: system: advancement
