Repository foundryvtt/dnd5e, pull requests merged in 2024-10, with the labels that each got.

#4481 Divorce system Appv2 apps from Appv1 styles.
  less/v2/activities.less
  less/v2/apps.less
  less/v2/character.less
  less/v2/forms.less
  less/v2/inventory.less
  less/v2/items.less
  less/v2/journal.less
  less/v2/tooltips.less
  less/variables.less
  module/applications/activity/activity-sheet.mjs
  module/applications/api/dialog.mjs
  module/applications/compendium-browser.mjs
  module/applications/dice/roll-configuration-dialog.mjs
  module/applications/source-config.mjs
  templates/actors/tabs/character-biography.hbs
  templates/apps/source-config.hbs
Labels: ui

#4491 [#4490] Toggle status effect on actors
  module/enrichers.mjs
Labels: compatibility

#4487 [#4287] Spell Scroll Icon
  module/documents/item.mjs
Labels: feature request

#4488 [#4292] Set default spell slot if the default option is disabled
  module/applications/activity/activity-usage-dialog.mjs
Labels: bug, system: activities

#4493 [#4489] AC cover calculation
  module/config.mjs
  module/data/actor/templates/common.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/utils.mjs
Labels: feature request

#4537 [#4536] Fix typo in variable name causing `ReferenceError` in deprecated hooks
  module/documents/activity/mixin.mjs
Labels: bug

#4290 Adjust enchantment and summon level limits to refer to character level
  module/data/activity/enchant-data.mjs
  module/data/activity/summon-data.mjs
Labels: system: summoning, system: enchantment

#4328 [#4310] Re-design skill & tool config to use V2 apps & styles
  lang/en.json
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/config/ability-config.mjs
  module/applications/actor/config/base-proficiency-config.mjs
  module/applications/actor/config/skill-tool-config.mjs
  module/applications/actor/deprecated/ability-config.mjs
  module/applications/actor/deprecated/proficiency-config.mjs
  module/applications/actor/proficiency-config.mjs
  module/applications/actor/skills-config.mjs
  templates/actors/config/ability-config.hbs
  templates/actors/config/concentration-config.hbs
  templates/actors/config/skill-tool-config.hbs
  templates/apps/proficiency-config.hbs
Labels: ui

#4450 [#4310] Re-design skills & tools config to use V2 apps & styles
  less/v2/apps.less
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/config/skills-config.mjs
  module/applications/actor/config/tools-config.mjs
  module/applications/actor/config/traits-config.mjs
  module/applications/actor/deprecated/skills-config.mjs
  module/applications/actor/deprecated/tool-selector.mjs
  module/applications/actor/skills-config.mjs
  module/applications/actor/tool-selector.mjs
  module/applications/components/proficiency-cycle.mjs
  templates/actors/config/skills-config.hbs
  templates/actors/config/tools-config.hbs
  templates/actors/config/traits-config.hbs
Labels: ui

#4508 [#4310] Re-design hit dice & hit points config for V2
  lang/en.json
  less/v1/apps.less
  less/v2/apps.less
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/config/hit-dice-config.mjs
  module/applications/actor/config/hit-points-config.mjs
  module/applications/actor/deprecated/hit-dice-config.mjs
  module/applications/actor/deprecated/hit-points-config.mjs
  module/applications/actor/hit-dice-config.mjs
  module/applications/actor/hit-points-config.mjs
  module/applications/property-attribution.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/vehicle.mjs
  module/documents/actor/actor.mjs
  module/utils.mjs
  templates/actors/config/hit-dice-config.hbs
  templates/actors/config/hit-points-config.hbs
  templates/apps/hit-dice-config.hbs
  templates/apps/hit-points-config.hbs
Labels: ui

#4506 [#4261] Add consumption warnings to activity usage dialog
  lang/en.json
  less/v2/activities.less
  less/variables.less
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/item/_module.mjs
  module/applications/item/ability-use-dialog.mjs
  module/config.mjs
  module/data/activity/fields/consumption-targets-field.mjs
  module/utils.mjs
  templates/activity/activity-usage-concentration.hbs
  templates/activity/activity-usage-consumption.hbs
  templates/activity/activity-usage-creation.hbs
  templates/activity/activity-usage-scaling.hbs
  templates/activity/parts/activity-usage-notes.hbs
  templates/apps/ability-use.hbs
Labels: ui, system: activities

#4516 [#4310] Re-design initiative config to use V2 app & styles
  lang/en.json
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/config/initiative-config.mjs
  module/applications/actor/deprecated/initiative-config.mjs
  module/applications/actor/initiative-config.mjs
  templates/actors/config/initiative-config.hbs
  templates/apps/initiative-config.hbs
Labels: ui

#4520 [#4310] Re-implement spell slots config using ApplicationV2
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/config/spell-slots-config.mjs
  module/applications/actor/deprecated/spell-slots-config.mjs
  module/applications/actor/spell-slots-config.mjs
  templates/actors/config/spell-slots-config.hbs
Labels: ui

#4521 [#4310] Merge & re-design movement & senses configs for V2
  less/v2/forms.less
  module/applications/_module.mjs
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/deprecated/movement-config.mjs
  module/applications/actor/deprecated/senses-config.mjs
  module/applications/actor/group-sheet.mjs
  module/applications/actor/movement-config.mjs
  module/applications/actor/senses-config.mjs
  module/applications/item/item-sheet.mjs
  module/applications/shared/_module.mjs
  module/applications/shared/movement-senses-config.mjs
  templates/apps/movement-config.hbs
  templates/apps/senses-config.hbs
  templates/shared/config/movement-senses-config.hbs
Labels: ui

#4567 [#4566] Fix item use tracking
  module/applications/token-config.mjs
Labels: bug

#4474 [#4061] Add spell caching system to Cast activities
  lang/en.json
  module/data/activity/base-activity.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/templates/activities.mjs
  module/data/item/templates/identifiable.mjs
  module/documents/active-effect.mjs
  module/documents/activity/cast.mjs
  module/documents/activity/mixin.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/documents/mixins/document.mjs
Labels: in progress, system: activities

#4531 [#4061] Allow Cast Activity to trigger linked spells
  module/applications/activity/activity-usage-dialog.mjs
  module/documents/activity/cast.mjs
  module/documents/activity/mixin.mjs
Labels: feature request, in progress, ux, system: activities

#4547 [#4310] Re-design creature type config for V2 apps & styles
  less/v2/apps.less
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/deprecated/type-config.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/actor/type-config.mjs
  module/applications/api/application-v2-mixin.mjs
  module/applications/item/item-sheet.mjs
  module/applications/shared/_module.mjs
  module/applications/shared/creature-type-config.mjs
  templates/apps/actor-type.hbs
  templates/shared/config/creature-type-config.hbs
Labels: ui

#4517 [#4310] Implement damage modification config in `DamagesConfig`
  lang/en.json
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/config/damages-config.mjs
  module/applications/actor/config/traits-config.mjs
  module/applications/actor/damage-modification-config.mjs
  module/applications/actor/deprecated/damage-modification-config.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/advancement/trait-config.mjs
  module/config.mjs
  module/documents/actor/trait.mjs
  module/documents/advancement/trait.mjs
  templates/actors/config/damages-config.hbs
  templates/actors/config/traits-config.hbs
  templates/apps/damage-modification-config.hbs
  templates/apps/parts/traits-list.hbs
Labels: ui

#4512 [#4310] Re-design armor class config to use V2 app & styles
  lang/en.json
  less/v2/apps.less
  module/applications/actor/_module.mjs
  module/applications/actor/armor-config.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/config/armor-class-config.mjs
  module/applications/actor/config/hit-points-config.mjs
  module/applications/actor/deprecated/armor-config.mjs
  module/data/item/equipment.mjs
  templates/actors/config/armor-class-config.hbs
  templates/actors/config/hit-points-config.hbs
Labels: ui

#4584 Add icons to DamagesConfig.
  less/v2/apps.less
  less/v2/dark/apps.less
  module/applications/actor/config/damages-config.mjs
  templates/apps/parts/traits-list.hbs
Labels: ui

#4275 [#2138] Refactor `D20Roll` for new API, deprecate `d20Roll` method
  dnd5e.mjs
  module/applications/dice/_module.mjs
  module/applications/dice/d20-configuration-dialog.mjs
  module/applications/dice/damage-configuration-dialog.mjs
  module/applications/dice/roll-configuration-dialog.mjs
  module/dice/_module.mjs
  module/dice/basic-roll.mjs
  module/dice/d20-die.mjs
  module/dice/d20-roll.mjs
  module/dice/damage-roll.mjs
  module/dice/dice.mjs
  templates/dice/roll-buttons.hbs
Labels: api, system: dice

#4597 [#4525] Add Facility item & sheet.
  icons/LICENSE
  icons/svg/items/facility.svg
  lang/en.json
  less/v2/items.less
  module/applications/item/item-sheet-2.mjs
  module/config.mjs
  module/data/item/_module.mjs
  module/data/item/facility.mjs
  module/utils.mjs
  system.json
  templates/items/details/details-facility.hbs
Labels: feature request, api

#4484 [#2138] Re-implement `rollAbilityTest` & `rollAbilitySave`
  module/applications/actor/base-sheet.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/data/shared/uses-field.mjs
  module/dice/basic-roll.mjs
  module/dice/d20-roll.mjs
  module/dice/dice.mjs
  module/documents/activity/check.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/save.mjs
  module/documents/activity/utility.mjs
  module/documents/actor/actor.mjs
  module/enrichers.mjs
Labels: api, system: dice

#4532 [#4383] Add `dnd5e.postRollConfiguration` hooks
  module/dice/basic-roll.mjs
Labels: api, system: dice

#4460 [#2094] Move item socket event handlers into type data models
  module/data/item/background.mjs
  module/data/item/class.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/race.mjs
  module/data/item/spell.mjs
  module/data/item/subclass.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/templates/physical-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/documents/item.mjs
Labels: api

#4540 [#2138, #3140] Re-implement concentration, death saves, & initiative
  module/applications/actor/character-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/dice/roll-configuration-dialog.mjs
  module/dice/basic-roll.mjs
  module/dice/d20-roll.mjs
  module/dice/damage-roll.mjs
  module/documents/actor/actor.mjs
  module/enrichers.mjs
Labels: api, system: dice

#4601 Register `TokenConfig` subclass in V12 only
  dnd5e.mjs
Labels: compatibility

#4543 [#4061] Add Cast activity to SRD items
  packs/_source/items/equipment/amulet-of-the-planes.json
  packs/_source/items/equipment/boots-of-levitation.json
  packs/_source/items/equipment/cape-of-the-mountebank.json
  packs/_source/items/equipment/circlet-of-blasting.json
  packs/_source/items/equipment/cloak-of-arachnida.json
  packs/_source/items/equipment/eyes-of-charming.json
  packs/_source/items/equipment/hat-of-disguise.json
  packs/_source/items/equipment/helm-of-brilliance.json
  packs/_source/items/equipment/helm-of-comprehending-languages.json
  packs/_source/items/equipment/helm-of-telepathy.json
  packs/_source/items/equipment/helm-of-teleportation.json
  packs/_source/items/equipment/medallion-of-thoughts.json
  packs/_source/items/equipment/necklace-of-prayer-beads.json
  packs/_source/items/equipment/robe-of-stars.json
  packs/_source/items/ring/ring-of-air-elemental-command.json
  packs/_source/items/ring/ring-of-animal-influence.json
  packs/_source/items/ring/ring-of-earth-elemental-command.json
  packs/_source/items/ring/ring-of-fire-elemental-command.json
  packs/_source/items/ring/ring-of-jumping.json
  packs/_source/items/ring/ring-of-shooting-stars.json
  packs/_source/items/ring/ring-of-telekinesis.json
  packs/_source/items/ring/ring-of-the-ram.json
  packs/_source/items/ring/ring-of-three-wishes.json
  packs/_source/items/ring/ring-of-water-elemental-command.json
  packs/_source/items/rod/rod-of-alertness.json
  packs/_source/items/trinket/crystal-ball-of-mind-reading.json
  packs/_source/items/trinket/crystal-ball-of-telepathy.json
  packs/_source/items/trinket/crystal-ball-of-true-seeing.json
  packs/_source/items/wand/wand-of-binding.json
  packs/_source/items/wand/wand-of-fireballs.json
  packs/_source/items/wand/wand-of-lightning-bolts.json
  packs/_source/items/wand/wand-of-magic-detection.json
  packs/_source/items/wand/wand-of-magic-missiles.json
  packs/_source/items/wand/wand-of-polymorph.json
  packs/_source/items/wand/wand-of-web.json
  packs/_source/items/weapon/staff-of-charming.json
  packs/_source/items/weapon/staff-of-fire.json
  packs/_source/items/weapon/staff-of-frost.json
  packs/_source/items/weapon/staff-of-healing.json
  packs/_source/items/weapon/staff-of-power.json
  packs/_source/items/weapon/staff-of-striking.json
  packs/_source/items/weapon/staff-of-swarming-insects.json
  packs/_source/items/weapon/staff-of-the-magi.json
  packs/_source/items/weapon/staff-of-the-python.json
  packs/_source/items/weapon/staff-of-the-woodlands.json
  packs/_source/items/weapon/staff-of-thunder-and-lightning.json
  packs/_source/items/weapon/staff-of-withering.json
Labels: compendium content, system: activities

#4542 [#1530, #2138] Re-implement `rollSkill` and `rollToolCheck`
  module/applications/actor/base-sheet.mjs
  module/applications/dice/_module.mjs
  module/applications/dice/roll-configuration-dialog.mjs
  module/applications/dice/skill-tool-configuration-dialog.mjs
  module/data/actor/templates/common.mjs
  module/dice/d20-roll.mjs
  module/dice/dice.mjs
  module/documents/activity/check.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/proficiency.mjs
  module/documents/item.mjs
  module/enrichers.mjs
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet.hbs
Labels: bug, api, system: dice

#4614 [#2138] Re-implement `rollAttack` using new rolling APIs
  module/applications/dice/_module.mjs
  module/applications/dice/attack-configuration-dialog.mjs
  module/data/activity/attack-data.mjs
  module/data/item/weapon.mjs
  module/data/shared/uses-field.mjs
  module/dice/basic-roll.mjs
  module/dice/d20-roll.mjs
  module/dice/dice.mjs
  module/documents/activity/attack.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
Labels: system: dice

#4616 [#4061, #4613] Add Cast overrides, activity changes via enchanting
  module/documents/active-effect.mjs
  module/documents/activity/cast.mjs
Labels: api, system: active effects, system: activities
