Repository foundryvtt/dnd5e, pull requests merged in 2024-05, with the labels that each got.

#3515 [#3475] Moved getRollData method from character to creature
  module/data/actor/character.mjs
  module/data/actor/templates/creature.mjs
Labels: bug

#3506 [#3305] Enforce enchantment restrictions when dropping onto item
  lang/en.json
  module/applications/components/effects.mjs
  module/applications/item/enchantment-config.mjs
  module/applications/item/item-sheet.mjs
  module/data/item/feat.mjs
  module/data/item/fields/enchantment-field.mjs
  module/data/item/spell.mjs
  module/data/item/templates/action.mjs
  module/documents/active-effect.mjs
  module/documents/item.mjs
  templates/items/parts/item-action.hbs
Labels: in progress, api, ux, system: enchantment

#3472 [#2299] Add replacement option for ItemChoiceAdvancement
  lang/en.json
  less/v1/advancement.less
  module/applications/advancement/advancement-config.mjs
  module/applications/advancement/item-choice-config.mjs
  module/applications/advancement/item-choice-flow.mjs
  module/data/advancement/_module.mjs
  module/data/advancement/item-choice.mjs
  module/documents/advancement/ability-score-improvement.mjs
  module/documents/advancement/advancement.mjs
  module/documents/advancement/item-choice.mjs
  module/documents/advancement/item-grant.mjs
  templates/advancement/item-choice-config.hbs
  templates/advancement/item-choice-flow.hbs
Labels: feature request, system: advancement

#3525 [#3524] Add summon level to all summoned creatures
  module/applications/item/ability-use-dialog.mjs
  module/data/item/fields/summons-field.mjs
Labels: api, system: summoning

#3509 Add initializeSource hook
  module/documents/item.mjs
Labels: api

#3518 [#3517] Add spell level to granted and dependent effects
  module/documents/item.mjs
Labels: api

#3499 [#3498] Add prone separately for sleeping/unconscious
  module/config.mjs
  module/documents/active-effect.mjs
Labels: api, ux

#3523 [#3426] Add simple string interpolation to active effects
  module/documents/active-effect.mjs
Labels: feature request, system: active effects

#3531 [#3380] Added .content-link to dark/character.less
  less/v2/dark/character.less
Labels: bug, ui

#3532 Propose resolution to synchronous UUID link generation bug
  module/utils.mjs
Labels: bug

#3513 [#3305] Add enchantment usage dialog & application tray
  lang/en.json
  less/v2/chat.less
  module/applications/components/_module.mjs
  module/applications/components/enchantment-application.mjs
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/enchantment-config.mjs
  module/data/item/fields/enchantment-field.mjs
  module/documents/active-effect.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  templates/apps/ability-use.hbs
  templates/items/parts/item-action.hbs
Labels: epic, feature request, in progress, ux, system: enchantment

#3520 [#3512] Allow enchantments to be limited by level
  lang/en.json
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/enchantment-config.mjs
  module/data/item/fields/enchantment-field.mjs
  module/documents/item.mjs
  templates/apps/ability-use.hbs
  templates/apps/enchantment-config.hbs
  templates/apps/summoning-config.hbs
Labels: ui, feature request, in progress, system: enchantment

#3535 [#3534] Add summoner modifier into summoned flags
  module/data/item/fields/summons-field.mjs
Labels: feature request, system: summoning

#3540 [#3500] Allow ordering of inventory categories to be set
  module/applications/actor/character-sheet.mjs
  module/data/abstract.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/loot.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
Labels: api

#3542 [#3541] Add Consume Usage and Consume Resource buttons to chat
  lang/en.json
  module/documents/chat-message.mjs
  module/documents/item.mjs
  templates/chat/item-card.hbs
Labels: feature request

#3545 [#3544] Add static registry of summoned creatures in world
  module/data/item/fields/summons-field.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/documents/token.mjs
Labels: in progress, api, system: summoning

#3546 [#3291] Add setting to control chat card tray expansion
  lang/en.json
  module/applications/components/chat-tray-element.mjs
  module/applications/components/damage-application.mjs
  module/documents/chat-message.mjs
  module/settings.mjs
Labels: ux

#3294 [#2780] Allow default concept compendiums to be defined
  module/applications/actor/character-sheet-2.mjs
  module/config.mjs
Labels: api

#3415 Update metrics values
  module/config.mjs
Labels: localization

#3529 [#3511] Add additional effects that ride along with enchantments
  lang/en.json
  module/applications/item/enchantment-config.mjs
  module/documents/active-effect.mjs
  module/documents/item.mjs
  templates/apps/enchantment-config.hbs
Labels: epic, feature request, system: active effects, system: enchantment

#1959 [#1909] Add units to item weight & properly convert for calculating encumbrance
  lang/en.json
  less/v1/items.less
  module/applications/actor/vehicle-sheet.mjs
  module/config.mjs
  module/data/item/container.mjs
  module/data/item/templates/physical-item.mjs
  module/documents/actor/actor.mjs
  module/utils.mjs
  templates/items/parts/item-description.hbs
  templates/shared/inventory.hbs
Labels: feature request, breaking

#3538 [#2094, #3537] Convert target value into formula, move prep logic
  module/data/abstract.mjs
  module/data/item/templates/activated-effect.mjs
  module/documents/item.mjs
  module/utils.mjs
  templates/items/parts/item-activation.hbs
Labels: feature request, api

#3553 [#3305] Allow "Enchant Prompt" to still enchant if prompt is shown
  lang/en.json
  module/data/item/fields/enchantment-field.mjs
  module/documents/item.mjs
  templates/apps/ability-use.hbs
  templates/items/parts/item-action.hbs
Labels: ux, system: enchantment

#3552 [#2111, #3551] Split attunement & attuned, add optional attunement
  lang/en.json
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/components/inventory.mjs
  module/config.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/documents/item.mjs
  templates/items/consumable.hbs
  templates/items/equipment.hbs
  templates/items/tool.hbs
  templates/items/weapon.hbs
Labels: feature request, api, breaking

#2785 [#1546] Add enricher that rolls items
  lang/en.json
  module/documents/item.mjs
  module/enrichers.mjs
Labels: feature request

#3422 Spell sorting by priority as an option
  lang/en.json
  module/applications/components/item-list-controls.mjs
  module/data/user/user-system-flags.mjs
  templates/actors/tabs/character-spells.hbs
Labels: ui, ux

#3569 [#3565] Move Award button to group actor control bar
  templates/actors/group-sheet.hbs
  templates/actors/tabs/group-members.hbs
Labels: ui

#3560 [#3305] Improve enchantment list on item sheet, add controls
  lang/en.json
  less/v1/items.less
  module/applications/item/item-sheet.mjs
  module/data/item/fields/enchantment-field.mjs
  module/documents/active-effect.mjs
  templates/items/parts/item-action.hbs
Labels: ui

#3564 [#3544] Add summoned creature list of item details tab
  lang/en.json
  module/applications/item/item-sheet.mjs
  templates/items/parts/item-action.hbs
Labels: ui, system: summoning

#3559 [#2111, #3259] Move encumbrance calcs & add multipliers & bonuses
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/vehicle.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
Labels: api

#3548 Summoning considerations for linked (e.g. unique) actors.
  module/data/item/fields/summons-field.mjs
Labels: api, system: summoning

#3567 [#3305] Add ability for enchantments to add rider items
  lang/en.json
  less/elements.less
  less/v2/apps.less
  module/applications/item/enchantment-config.mjs
  module/data/item/fields/enchantment-field.mjs
  module/documents/active-effect.mjs
  module/utils.mjs
  templates/apps/enchantment-config.hbs
Labels: feature request, system: enchantment

#3576 [#3444] Re-implement summoned item modifications using enchantments
  module/data/item/fields/summons-field.mjs
  module/documents/active-effect.mjs
  module/documents/item.mjs
Labels: system: summoning, system: enchantment

#3577 Control hints & other UI tweaks
  icons/LICENSE
  icons/svg/mouse-middle.svg
  icons/svg/mouse.svg
  lang/en.json
  less/v2/apps.less
  less/v2/character.less
  less/v2/tooltips.less
  module/data/abstract.mjs
  module/settings.mjs
  templates/items/parts/item-tooltip.hbs
  ui/resize-handle.webp
Labels: ui, ux

#3580 [#3441] Removed leading / on css url() and on icon in config.mjs
  less/v2/character.less
  less/v2/dark/character.less
  module/applications/actor/character-sheet-2.mjs
  module/config.mjs
Labels: bug

#3403 Wiki updates for 3.2.x
  wiki/Modifying-Your-Game-with-Scripts.md
  wiki/Roll-Formulas.md
Labels: documentation

#3585 Additional Wiki updates for 3.2.x
  wiki/Active-Effect-Guide.md
  wiki/Enchantment.md
  wiki/Enrichers.md
  wiki/Home.md
  wiki/Summoning.md
  wiki/images/enchantment/enchantment-changes.jpg
  wiki/images/enchantment/enchantment-chat-message.jpg
  wiki/images/enchantment/enchantment-configuration.jpg
  wiki/images/enchantment/enchantment-item-details.jpg
  wiki/images/enchantment/enchantment-summary.jpg
  wiki/images/summoning/summoning-configuration.jpg
  wiki/images/summoning/summoning-quantity-level.jpg
Labels: documentation

#3579 [#3572] Embed enricher styling for item sheets.
  less/v1/items.less
Labels: ui

#3581 [#3401] Modified actor-features.hbs input node for item-detail
  module/applications/actor/sheet-mixin.mjs
Labels: bug

#3641 [#3622] Fix advancement when race uses legacy string value
  module/applications/advancement/advancement-manager.mjs
Labels: bug

#3638 [#3616] Fix attunement not being settable when attuned is set by enchantment
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
Labels: bug

#3636 [#3635] Fix unconfigurable transfer value after effect is made a rider
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
Labels: bug

#3654 [#3650, #3651] Fix references to `sourceId` in V12
  module/applications/actor/sheet-mixin.mjs
  module/applications/source-config.mjs
  module/data/abstract.mjs
  module/data/item/fields/summons-field.mjs
  module/utils.mjs
  utils/packs.mjs
Labels: bug

#3658 [#3604] Fix non-draggable content links in V11
  module/applications/journal/class-page-sheet.mjs
  module/enrichers.mjs
  module/utils.mjs
Labels: bug

#3666 [#3659] Added clear call for preview
  module/canvas/token-placement.mjs
Labels: bug

#3673 Update various weapon descriptions and images for accuracy.
  packs/_source/items/weapon/blowgun-1.json
  packs/_source/items/weapon/blowgun-2.json
  packs/_source/items/weapon/blowgun-3.json
  packs/_source/items/weapon/blowgun.json
  packs/_source/items/weapon/club-1.json
  packs/_source/items/weapon/club-2.json
  packs/_source/items/weapon/club-3.json
  packs/_source/items/weapon/club.json
  packs/_source/items/weapon/flail-1.json
  packs/_source/items/weapon/flail-2.json
  packs/_source/items/weapon/flail-3.json
  packs/_source/items/weapon/flail.json
  packs/_source/items/weapon/mace-1.json
  packs/_source/items/weapon/mace-2.json
  packs/_source/items/weapon/mace-3.json
  packs/_source/items/weapon/mace.json
  packs/_source/items/weapon/pike-1.json
  packs/_source/items/weapon/pike-2.json
  packs/_source/items/weapon/pike-3.json
  packs/_source/items/weapon/pike.json
  packs/_source/items/weapon/trident-1.json
  packs/_source/items/weapon/trident-2.json
  packs/_source/items/weapon/trident-3.json
  packs/_source/items/weapon/trident.json
Labels: compendium content
