Repository foundryvtt/dnd5e, pull requests merged in 2024-02, with the labels that each got.

#2836 Prevent chat card rendering from failing if sender has been removed from message
  module/documents/chat-message.mjs
Labels: bug

#2822 [#2819] Remove subject fallback to prevent 404s
  module/documents/token.mjs
Labels: breaking

#2815 [#2796] Align encumbrance arrows on centre
  less/v2/inventory.less
Labels: bug, ui

#2840 [#2827] Fix localization strings for bypasses, make tooltip clearer
  lang/en.json
  templates/actors/tabs/character-details.hbs
Labels: bug, ui, localization

#2738 Add reference to the tool being used in tool checks
  module/documents/item.mjs
Labels: api

#2884 [#2842] use flex-basis auto for checkboxes in flex labels
  less/v1/apps.less
Labels: bug, ui

#2861 Add a `dnd5e.calculateDamage` hook
  module/documents/actor/actor.mjs
Labels: api

#2808 [#2798] Support adjustable encumbrance arrows
  less/v2/inventory.less
  templates/shared/inventory2.hbs
Labels: ui

#2904 [#2903] Show skill tooltip on the skill row, rather on the skill label
  templates/actors/tabs/character-details.hbs
Labels: ui

#2846 [#2809, #2858, #2859] Add user configuration for status conditions and exhaustion
  module/config.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/templates/traits.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
Labels: api

#2880 [#2765] Add scaleCorrection to the token config UI
  templates/apps/parts/dynamic-ring.hbs
Labels: ui

#2875 [#2868] Fix issue with active tab not being saved when sheet is re-opened
  module/applications/actor/character-sheet-2.mjs
Labels: bug, ux

#2881 [#2770] Toggle effect on actor if it already exists
  module/documents/item.mjs
Labels: bug

#2882 [#2838] Don't collapse chat card if the user clicked a link or button in the collapsible region
  module/documents/item.mjs
Labels: bug, ux

#2899 Fix linter warnings
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/token-config.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/shared/source-field.mjs
  module/dice/simplify-roll-formula.mjs
  module/documents/actor/trait.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  module/documents/token.mjs
  module/migration.mjs
  module/module-art.mjs
  package.json
Labels: tooling

#2922 [#2911] Privatize item roll cards
  less/v2/chat.less
  module/documents/chat-message.mjs
Labels: bug, ui

#2926 [#2895] convert spell to scroll when dropping in container
  module/applications/item/container-sheet.mjs
Labels: bug

#2929 [#2883] Support passive ability checks and passive skill checks with arbitrary base skills
  lang/en.json
  module/documents/actor/actor.mjs
  module/tooltips.mjs
Labels: bug

#2962 Added compatibility with v12 condition filters.
  module/canvas/shaders/token-ring-shader.mjs
  module/canvas/token-ring.mjs
  module/canvas/token.mjs
Labels: api

#2977 [#2879] Ensure grandchild documents with identical IDs are displayed properly
  module/applications/components/item-list-controls.mjs
Labels: bug

#2973 [#2843, #2972] Fix issues with AC bonuses & attribution
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
Labels: bug

#2961 [#2927] Fix token ring effects not appearing on linked tokens
  module/documents/actor/actor.mjs
Labels: bug

#2941 [#2939, #2940] Fix sidebar branding appearing twice, not showing update badge
  dnd5e.mjs
  less/v2/apps.less
Labels: ui

#2988 [#2949] Rename some conditions
  lang/en.json
  module/config.mjs
Labels: localization

#2987 [#2976] Use total of all rolls for temphp, prevent errors for broken tokens
  module/documents/chat-message.mjs
Labels: bug

#2959 Allow for exhaustion to be configurable
  module/applications/actor/character-sheet-2.mjs
  module/config.mjs
  module/data/actor/templates/attributes.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
  templates/actors/character-sheet-2.hbs
Labels: api

#2982 Fix Adding Skills and Tools as Favorites
  module/data/actor/character.mjs
Labels: bug

#2945 [#2931] Fallback to default item type label
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/weapon.mjs
Labels: bug

#2996 [#2992] Use different icons for unprepared & always prepared states
  module/applications/actor/character-sheet-2.mjs
  templates/actors/tabs/character-spells.hbs
Labels: ui, accessibility

#2974 [#2845] Display temp max on character sheet HP bar
  less/v2/apps.less
  less/v2/character.less
  module/applications/actor/group-sheet.mjs
  module/canvas/token.mjs
  module/documents/actor/actor.mjs
  module/documents/token.mjs
  templates/actors/character-sheet-2.hbs
Labels: ui

#2997 [#2947] Add metadata.supportsAdvancement, fix issue with deleteDialog failing
  module/applications/actor/base-sheet.mjs
  module/applications/item/item-sheet.mjs
  module/data/abstract.mjs
  module/data/actor/character.mjs
  module/data/actor/group.mjs
  module/data/item/background.mjs
  module/data/item/race.mjs
  module/documents/item.mjs
Labels: bug, api

#2999 [#2867] Add context menus to race, background, classes, & subclasses
  module/applications/actor/character-sheet-2.mjs
Labels: ux

#3001 [#2876] Fix context menus being displayed off the bottom of the screen
  module/applications/context-menu.mjs
Labels: bug, ui

#3005 [#2995] Fix transformation reversion errors
  module/data/token/token-system-flags.mjs
Labels: bug

#3006 Show pact slots in `ActorSpellSlotsConfig` if actor has at least one spell with "pact" preparation mode
  module/applications/actor/spell-slots-config.mjs
Labels: bug

#3004 [#2885] Hide active effect names when from unidentified item
  module/applications/components/effects.mjs
Labels: bug, ui

#3002 [#2979] Clamp damage/healing amount so it doesn't exceed HP bounds
  module/documents/actor/actor.mjs
Labels: bug

#2866 [#2863] Increase contrast on sheet UI when prefers-contrast: more is enabled
  less/elements.less
  less/v2/apps.less
  less/v2/character.less
  less/v2/inventory.less
  less/variables.less
  ui/ability-score-tab-hc.svg
Labels: ui, accessibility

#2893 [#2869] Added Limited Sheets, Partial sheets, and Modified logic in character sheet 2 if permission is limited
  less/v2/character.less
  module/applications/actor/character-sheet-2.mjs
  templates/actors/limited-sheet-2.hbs
Labels: ui

#3061 [#2934] Fix issue with active effect de-duplication
  module/migration.mjs
Labels: bug, migration

#3087 [#3030] Add config property for default abilities
  module/config.mjs
  module/documents/actor/actor.mjs
  module/documents/advancement/hit-points.mjs
Labels: api

#3049 Don't forward database operations to the type data model in V12
  module/documents/mixins/document.mjs
Labels: api

#3107 [#3055] Fix issue with token ring not being handled properly when transforming
  module/documents/actor/actor.mjs
Labels: bug

#3114 [#2841, #3110, #3111, #3113] Update build script to fix issues & remove deprecations
  .github/workflows/release.yml
Labels: tooling

#2748 [#2747] Move advancement valid item types into config so module subtypes can change it
  module/applications/advancement/advancement-selection.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/fields.mjs
  module/data/item/race.mjs
  module/documents/actor/actor.mjs
  module/documents/advancement/ability-score-improvement.mjs
  module/documents/advancement/advancement.mjs
  module/documents/advancement/hit-points.mjs
  module/documents/advancement/scale-value.mjs
  module/documents/advancement/size.mjs
  module/documents/item.mjs
Labels: api

#2727 Expose ItemUseConfiguration in AbilityUseDialog
  module/applications/item/ability-use-dialog.mjs
Labels: api

#2750 [#2749] Generalize alternative spellcasting types in the `AbilityUseDialog` and when upcasting
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/spell-slots-config.mjs
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/documents/item.mjs
  templates/advancement/parts/advancement-spell-config.hbs
  templates/items/spell.hbs
Labels: api

#2549 [#456] NPC Death Saves - Updated Schema and Sheet
  module/applications/actor/npc-sheet.mjs
  module/data/actor/npc.mjs
  templates/actors/npc-sheet.hbs
Labels: feature request

#3012 [#2224] Only automatically set item sheet height on tab change
  module/applications/item/item-sheet.mjs
Labels: bug, ui, ux

#3025 [#2864] Add theme option to sheet config & system settings
  dnd5e.mjs
  lang/en.json
  module/applications/_module.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/sheet-config.mjs
  module/config.mjs
  module/settings.mjs
  templates/shared/sheet-config.hbs
Labels: ui, ux

#3082 [#3058] Fix bad spacing with alternate font sizes
  less/v2/apps.less
  less/v2/character.less
Labels: bug, ui

#3095 [#2849] Display damage modification on sheet, add configuration app
  lang/en.json
  less/v1/apps.less
  module/applications/actor/_module.mjs
  module/applications/actor/armor-config.mjs
  module/applications/actor/base-config.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/damage-modification-config.mjs
  module/applications/actor/hit-points-config.mjs
  module/applications/actor/movement-config.mjs
  module/applications/actor/trait-selector.mjs
  templates/actors/tabs/character-details.hbs
  templates/apps/damage-modification-config.hbs
Labels: ui

#3096 [#893] Add data model & configuration data for summoning
  lang/en.json
  less/v1/items.less
  module/applications/item/_module.mjs
  module/applications/item/item-sheet.mjs
  module/applications/item/summoning-config.mjs
  module/config.mjs
  module/data/item/templates/action.mjs
  templates/apps/summoning-config.hbs
  templates/items/parts/item-action.hbs
Labels: epic, ui, feature request, in progress, api
