Repository foundryvtt/dnd5e, pull requests merged in 2024-11, with the labels that each got.

#4621 Add bastion tab to character sheet.
  icons/LICENSE
  icons/svg/facilities/craft.svg
  icons/svg/facilities/empower.svg
  icons/svg/facilities/enlarge.svg
  icons/svg/facilities/harvest.svg
  icons/svg/facilities/maintain.svg
  icons/svg/facilities/recruit.svg
  icons/svg/facilities/research.svg
  icons/svg/facilities/trade.svg
  lang/en.json
  less/v2/apps.less
  less/v2/character.less
  less/v2/dark/character.less
  module/applications/actor/character-sheet-2.mjs
  module/applications/item/item-sheet-2.mjs
  module/config.mjs
  module/data/actor/character.mjs
  module/data/item/facility.mjs
  module/utils.mjs
  system.json
  templates/actors/character-sheet-2.hbs
  templates/actors/tabs/character-bastion.hbs
  templates/items/details/details-facility.hbs
  templates/items/item-sheet-2.hbs
Labels: ui, ux

#4600 [#4031] Add Forward activity
  icons/LICENSE
  icons/svg/activity/forward.svg
  lang/en.json
  module/applications/activity/_module.mjs
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/forward-sheet.mjs
  module/config.mjs
  module/data/activity/_module.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/forward-data.mjs
  module/documents/activity/_module.mjs
  module/documents/activity/forward.mjs
  module/documents/activity/mixin.mjs
  templates/activity/forward-activation.hbs
  templates/activity/forward-effect.hbs
  templates/activity/forward-identity.hbs
  templates/activity/parts/activity-consumption.hbs
Labels: system: activities

#4627 [#4031] Adjust Grant/Choose Items advancement to use Forward
  module/data/advancement/spell-config.mjs
Labels: system: advancement, system: activities

#4555 [#4459] Add action that triggers automatically with activity use
  module/documents/activity/attack.mjs
  module/documents/activity/damage.mjs
  module/documents/activity/heal.mjs
  module/documents/activity/mixin.mjs
Labels: ux

#4615 [#4603] Stored deleted items in consumed flag, add item restore
  module/data/item/templates/activities.mjs
  module/documents/activity/mixin.mjs
  module/documents/chat-message.mjs
Labels: bug, ux, system: activities

#4510 [#4485] Check for HP-related update in `_onUpdate`
  module/documents/actor/actor.mjs
Labels: bug

#4617 Associates linked summons with item rather than activity
  module/documents/activity/summon.mjs
Labels: system: summoning

#4651 Implement Order Activity for Facility Items
  icons/LICENSE
  icons/svg/activity/order.svg
  lang/en.json
  less/v2/activities.less
  less/v2/apps.less
  less/v2/character.less
  less/v2/items.less
  module/applications/activity/_module.mjs
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/activity/forward-sheet.mjs
  module/applications/activity/order-usage-dialog.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/currency-manager.mjs
  module/applications/item/item-sheet-2.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/config.mjs
  module/data/abstract.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/order-data.mjs
  module/data/advancement/base-advancement.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/facility.mjs
  module/data/item/loot.mjs
  module/data/item/templates/identifiable.mjs
  module/data/item/templates/physical-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/data/shared/uses-field.mjs
  module/documents/activity/_module.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/order.mjs
  module/documents/item.mjs
  templates/activity/order-usage.hbs
  templates/actors/tabs/character-bastion.hbs
  templates/chat/order-activity-card.hbs
  templates/items/details/details-facility.hbs
Labels: feature request, api

#4652 Bastion configuration settings
  lang/en.json
  module/applications/_module.mjs
  module/applications/activity/order-usage-dialog.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/bastion.mjs
  module/settings.mjs
  templates/apps/bastion-config.hbs
Labels: ui, feature request

#4526 [#4192] Support multiple save abilities to `SaveActivity`
  lang/en.json
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/data/activity/save-data.mjs
  module/documents/activity/save.mjs
  templates/actors/character-sheet-2.hbs
  templates/actors/parts/columns/column-roll.hbs
  templates/actors/tabs/creature-spells.hbs
Labels: feature request, system: activities

#4439 Update Lay On Hands to roll healing
  packs/_source/classfeatures/paladin/paladin-features/lay-on-hands.json
Labels: compendium content

#4338 Allow removal of exhaustion condition
  less/v2/character.less
  less/v2/sheets.less
  module/applications/actor/character-sheet-2.mjs
  templates/actors/character-sheet-2.hbs
  templates/actors/character-sheet.hbs
Labels: api

#4486 Various fixes to Hammer of Thunderbolts
  packs/_source/items/weapon/hammer-of-thunderbolts.json
Labels: compendium content

#3155 Allow custom currency icons
  module/applications/award.mjs
  module/config.mjs
  module/enrichers.mjs
  templates/apps/award.hbs
  templates/apps/currency-manager.hbs
  templates/items/item-sheet-2.hbs
  templates/shared/inventory2.hbs
Labels: api

#4655 Add build order for basic facilities.
  icons/LICENSE
  icons/svg/facilities/build.svg
  lang/en.json
  less/v2/character.less
  module/applications/activity/order-usage-dialog.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/item/item-sheet-2.mjs
  module/config.mjs
  module/data/item/facility.mjs
  module/documents/activity/order.mjs
  templates/activity/order-usage.hbs
  templates/actors/tabs/character-bastion.hbs
  templates/items/details/details-facility.hbs
Labels: feature request, api

#4658 Bastion turn automation
  dnd5e.mjs
  lang/en.json
  less/v2/activities.less
  less/v2/apps.less
  module/applications/activity/order-usage-dialog.mjs
  module/applications/bastion.mjs
  module/documents/_module.mjs
  module/documents/activity/order.mjs
  module/documents/actor/bastion.mjs
  module/documents/chat-message.mjs
  module/settings.mjs
  templates/apps/bastion-config.hbs
  templates/chat/bastion-turn-summary.hbs
  templates/chat/order-activity-card.hbs
Labels: feature request, api

#4660 Add change activity for Gardens
  icons/LICENSE
  icons/svg/facilities/change.svg
  lang/en.json
  module/applications/activity/order-usage-dialog.mjs
  module/applications/item/item-sheet-2.mjs
  module/config.mjs
  module/data/item/facility.mjs
Labels: feature request, api

#4663 Implement bastion attack resolution.
  icons/svg/facilities/repair.svg
  lang/en.json
  less/v2/activities.less
  module/applications/actor/character-sheet-2.mjs
  module/applications/item/item-sheet-2.mjs
  module/config.mjs
  module/data/item/facility.mjs
  module/documents/actor/bastion.mjs
  templates/actors/tabs/character-bastion.hbs
  templates/apps/bastion-attack-dialog.hbs
  templates/chat/bastion-attack-summary.hbs
  templates/items/details/details-facility.hbs
Labels: feature request, api

#4661 Document Cast & Forward activities
  wiki/Activities.md
  wiki/Activity-Type-Cast.md
  wiki/Activity-Type-Forward.md
  wiki/Home.md
  wiki/images/activities/activity-creation.jpg
  wiki/images/activities/cast-effect.jpg
  wiki/images/activities/cast-identity.jpg
  wiki/images/activities/cast-spellbook.jpg
  wiki/images/activities/forward-effect.jpg
Labels: documentation

#4664 Update hooks for new release
  wiki/Hooks.md
Labels: documentation

#4659 Implement various wiki changes for `4.1` release
  wiki/Active-Effect-Guide.md
  wiki/Compendium-Browser.md
  wiki/Enchantment.md
  wiki/FAQ.md
  wiki/images/compendium-browser/advanced-mode.jpg
  wiki/images/compendium-browser/class-selection.jpg
  wiki/images/compendium-browser/configure-sources.jpg
  wiki/images/compendium-browser/standard-mode.jpg
  wiki/images/settings/rules-version.jpg
Labels: documentation

#4635 [#4634] Fix Wing Attack damage of Adult Green Dragon
  packs/_source/monsters/dragon/adult-green-dragon.json
Labels: compendium content

#4670 [#4669] Add level filter for facilities in Compendium Browser
  module/applications/actor/character-sheet-2.mjs
  module/data/item/facility.mjs
Labels: system: compendium browser, system: bastions

#4717 #rollSkillTool() doesn't merge the message Object properly
  module/documents/actor/actor.mjs
Labels: bug, system: dice

#4779 Fix some v13 errors. Respect options.render when calling PhysicalItemTemplate#_renderContainers.
  module/data/item/templates/physical-item.mjs
Labels: bug
