Repository foundryvtt/dnd5e, pull requests merged in 2024-01, with the labels that each got.

#2704 [#2687] Optional chain RT
  module/documents/actor/actor.mjs
Labels: bug

#2703 [#2694] Prevent race being dropped on Group sheet
  module/applications/actor/group-sheet.mjs
Labels: bug

#2702 [#2697] Expose actor sheet mixin
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/group-sheet.mjs
  module/applications/actor/sheet-mixin.mjs
Labels: api

#2705 Add placeTemplate hooks
  module/canvas/ability-template.mjs
Labels: api

#2712 [#2692] Add source config button to vehicle sheets
  dnd5e.css
  less/vehicle.less
  templates/actors/vehicle-sheet.hbs
Labels: bug

#2711 [#2513] Add link for GMs to request roll from inline roll
  dnd5e.css
  lang/en.json
  less/chat.less
  module/enrichers.mjs
  module/utils.mjs
  templates/chat/request-card.hbs
Labels: feature request

#2708 [#1415] Prelocalize creature types
  module/config.mjs
  module/documents/actor/actor.mjs
Labels: localization

#2713 [#2636] Modify spell component migration to avoid losing properties
  module/data/item/spell.mjs
  module/documents/item.mjs
Labels: migration

#2714 [#2636] Migrate stealth disadvantage on armor to properties
  lang/en.json
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/documents/item.mjs
  templates/items/equipment.hbs
Labels: api

#2715 [#2636] Move valid properties into system data models
  module/applications/item/item-sheet.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/templates/item-description.mjs
Labels: api

#2719 Add humanoid to Creature Type value
  packs/src/heroes/riswynn-dwarf-rogue.json
Labels: compendium content

#2722 [#2716] Show AC only on armor/shield/vehicle
  module/data/item/equipment.mjs
Labels: bug

#2721 [#2352] Add consumable subtypes
  lang/en.json
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/item/consumable.mjs
  templates/items/consumable.hbs
  templates/items/feat.hbs
  templates/items/loot.hbs
Labels: feature request, api

#2717 Add 'concentration' to scroll properties, fix createScrollFromSpell
  module/data/item/consumable.mjs
  module/documents/item.mjs
Labels: bug, feature request

#2720 Add `isConcentration` getter
  module/data/item/templates/activated-effect.mjs
  module/documents/item.mjs
Labels: api

#2723 Add AC tag to siege weaponry
  module/applications/item/item-sheet.mjs
  module/data/item/weapon.mjs
  module/documents/item.mjs
Labels: feature request

#2725 Patch damage and healing types config, add color, label, isPhysical properties
  module/config.mjs
  module/documents/item.mjs
  module/enrichers.mjs
  templates/items/parts/item-action.hbs
Labels: api, breaking

#2701 [#2698] Move getRollData to system models
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/common.mjs
  module/data/actor/vehicle.mjs
  module/documents/actor/actor.mjs
Labels: api
