Repository foundryvtt/dnd5e, pull requests merged in 2024-03, with the labels that each got.

#3172 Allow stored item data in chat cards to contain active effects
  module/documents/item.mjs
  templates/chat/item-card.hbs
Labels: active effects

#3164 Add dark mode styles for character sheets.
  less/dnd5e.less
  less/elements.less
  less/v2/apps.less
  less/v2/character.less
  less/v2/dark/apps.less
  less/v2/dark/character.less
  less/v2/dark/inventory.less
  less/v2/inventory.less
  less/variables.less
  module/applications/context-menu.mjs
  module/settings.mjs
  ui/ability-score-tab-dark.svg
  ui/official/banner-character-dark.webp
Labels: ui

#3024 Movement speed calculation fixes
  module/config.mjs
  module/data/actor/character.mjs
  module/data/actor/templates/attributes.mjs
Labels: bug

#3138 [#2824] Enable ring gradient effect current combatant's token
  dnd5e.mjs
  module/documents/_module.mjs
  module/documents/combat.mjs
  module/documents/combatant.mjs
  module/documents/token.mjs
Labels: feature request

#2592 [#2591] Implement 'attack.flat' property
  lang/en.json
  module/data/item/templates/action.mjs
  module/documents/item.mjs
  templates/items/parts/item-action.hbs
Labels: api

#3118 [#3116] Add ability to embed actor & item descriptions
  module/enrichers.mjs
Labels: feature request

#3127 [#3125, #3126] Move damage calculation to own method
  module/documents/actor/actor.mjs
Labels: api

#3148 [#3147] Add magical bonus to weapons & armor
  lang/en.json
  module/data/item/equipment.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/weapon.mjs
  module/documents/item.mjs
  templates/items/equipment.hbs
  templates/items/weapon.hbs
Labels: feature request

#3190 [#2920, #3147] Add magical bonus to ammo, fix attack bonus data
  module/data/item/consumable.mjs
  module/documents/item.mjs
  templates/items/consumable.hbs
Labels: bug, feature request

#3097 [#3033] Add concentration actor method and hooks
  module/documents/actor/actor.mjs
Labels: api

#3167 [#893] Add summoning to item activation workflow
  lang/en.json
  module/applications/item/ability-use-dialog.mjs
  module/data/item/templates/action.mjs
  module/data/item/templates/activated-effect.mjs
  module/documents/item.mjs
  templates/apps/ability-use.hbs
  templates/apps/summoning-config.hbs
  templates/chat/item-card.hbs
  templates/items/parts/item-action.hbs
Labels: epic, feature request, in progress, ux

#3152 [#997] Add lookup enricher for including non-roll data
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/enrichers.mjs
Labels: feature request

#3166 [#3028, #3034, #3037] Concentration prompts
  lang/en.json
  module/applications/item/ability-use-dialog.mjs
  module/config.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  templates/apps/ability-use.hbs
Labels: epic, feature request, in progress, ux

#3169 Adapt high contrast mode to dark mode
  less/dnd5e.less
  less/elements.less
  less/v2/apps.less
  less/v2/character.less
  less/v2/dark/apps.less
  less/v2/high-contrast/apps.less
  less/v2/high-contrast/character.less
  less/v2/high-contrast/inventory.less
  less/v2/inventory.less
  less/variables.less
  module/settings.mjs
Labels: ui

#3045 [#1871] Add starting equipment data
  lang/en.json
  less/v1/items.less
  module/applications/item/_module.mjs
  module/applications/item/item-sheet.mjs
  module/applications/item/starting-equipment-config.mjs
  module/data/item/_module.mjs
  module/data/item/background.mjs
  module/data/item/class.mjs
  module/data/item/templates/starting-equipment.mjs
  templates/apps/starting-equipment-config.hbs
  templates/items/background.hbs
  templates/items/class.hbs
  templates/items/parts/item-advancement.hbs
Labels: feature request, in progress, advancement

#3201 [#3200] Fix available uses displaying as `null` in ability use dialog
  module/applications/item/ability-use-dialog.mjs
Labels: bug

#3202 [#2935] Prevent effect migrations from running more than once
  module/migration.mjs
Labels: migration

#3208 [#2094, #3185] Move ability & hp prep, fix advancement HP on NPCs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/templates/common.mjs
  module/data/actor/vehicle.mjs
  module/documents/actor/actor.mjs
  templates/actors/npc-sheet.hbs
  templates/apps/hit-points-config.hbs
Labels: api, advancement

#3227 Fix some item descriptions containing odd html
  packs/_source/items/equipment/amulet-of-proof-against-detection-and-location.json
  packs/_source/items/equipment/amulet-of-the-planes.json
  packs/_source/items/trinket/alchemy-jug.json
  packs/_source/items/trinket/apparatus-of-the-crab.json
Labels: compendium content

#3220 [#3130] Modified roll CSS Position
  less/v2/chat.less
Labels: bug, ui

#3198 Add deprecation note to spell comps and tags
  module/config.mjs
Labels: documentation

#3207 [#3039] Add method on `Actor5e` for creating a conc prompt
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/enrichers.mjs
Labels: epic, feature request, in progress, ux

#3159 Convert several attribute fields to use `RollConfigField`
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/templates/creature.mjs
  module/data/shared/roll-config-field.mjs
  module/documents/actor/actor.mjs
Labels: api

#3209 [#2668] Derive NPC details from race item if present
  module/applications/actor/npc-sheet.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/item/race.mjs
Labels: feature request

#3241 [#3183] Adjust rollDamage to return merged roll, rather than first
  module/dice/dice.mjs
  module/documents/item.mjs
Labels: bug, api

#3217 [#893] Add summoning actor updates & overall workflow
  lang/en.json
  module/applications/item/summoning-config.mjs
  module/data/item/_module.mjs
  module/data/item/fields/summons-field.mjs
  module/data/item/templates/action.mjs
  module/documents/item.mjs
  templates/apps/summoning-config.hbs
Labels: epic, feature request, in progress, ux

#3255 Migrate ItemGrant & Choice to store items as objects rather than UUIDs
  module/applications/advancement/advancement-config.mjs
  module/applications/advancement/item-choice-config.mjs
  module/applications/advancement/item-choice-flow.mjs
  module/applications/advancement/item-grant-config.mjs
  module/applications/advancement/item-grant-flow.mjs
  module/data/advancement/item-choice.mjs
  module/data/advancement/item-grant.mjs
  module/data/fields.mjs
  module/documents/advancement/item-choice.mjs
  module/documents/advancement/item-grant.mjs
  templates/advancement/item-choice-config.hbs
  templates/advancement/item-grant-config.hbs
Labels: api, breaking, advancement

#3196 Deprecate `DND5E.LimitedUseFormulaPeriods`
  lang/en.json
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  templates/advancement/parts/advancement-spell-config.hbs
  templates/items/parts/item-activation.hbs
Labels: api, breaking

#3244 [#893] Add damage & healing bonuses to summoning configuration
  lang/en.json
  module/data/item/fields/summons-field.mjs
  templates/apps/summoning-config.hbs
Labels: epic, feature request, in progress

#3258 [#893] Hide options in ability use dialog when summoning from chat
  module/applications/item/ability-use-dialog.mjs
  module/documents/item.mjs
Labels: ui, in progress

#3256 [#3165] Prevent template placement if no scene is open
  module/documents/chat-message.mjs
  module/documents/item.mjs
Labels: bug, ux

#3249 [#3248] Invert healing automatically in `calculateDamage`
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
Labels: api, breaking

#3219 [#893] Improve permissions checks & allow compendium summoning
  lang/en.json
  module/data/item/fields/summons-field.mjs
  module/data/item/templates/action.mjs
  module/data/token/token-system-flags.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  module/settings.mjs
Labels: epic, feature request, in progress

#3251 [#3250] Aggregate damage types before passing to `applyDamage`
  module/dice/_module.mjs
  module/dice/aggregate-damage-rolls.mjs
  module/documents/chat-message.mjs
Labels: api

#3270 [#3039] Add concentration interactivity to the character sheet.
  icons/svg/break-concentration.svg
  lang/en.json
  less/v2/apps.less
  less/v2/character.less
  less/v2/inventory.less
  module/applications/actor/character-sheet-2.mjs
  module/applications/components/effects.mjs
  module/applications/components/inventory.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  templates/actors/tabs/character-details.hbs
  templates/actors/tabs/character-spells.hbs
  templates/shared/active-effects2.hbs
  templates/shared/inventory2.hbs
Labels: ui, in progress, ux

#3271 [#3158, #3250] Use `aggregateDamageRolls` to improve chat damage previews
  module/dice/aggregate-damage-rolls.mjs
  module/documents/chat-message.mjs
Labels: bug, ui

#3265 [#1015, #1372] Add damage application tray to chat cards
  lang/en.json
  less/v2/chat.less
  module/applications/components/_module.mjs
  module/applications/components/damage-application.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  module/enrichers.mjs
  templates/chat/item-card.hbs
Labels: ui, feature request, in progress, ux

#3211 [#3035] Remove various dependencies on "dhp" and "dtemp" properties and add damage/healing hooks
  module/documents/actor/actor.mjs
  module/documents/token.mjs
Labels: breaking

#3272 [#3099] Move to pure CSS solution for collapsibles.
  less/v1/items.less
  less/v2/chat.less
  module/applications/components/damage-application.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  templates/chat/item-card.hbs
  templates/chat/roll-breakdown.hbs
Labels: ui, breaking

#3274 [#3028] Add concentration configuration.
  lang/en.json
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/concentration-config.mjs
  module/documents/actor/actor.mjs
  templates/apps/concentration-config.hbs
Labels: ui

#3273 [#1372] Add display of resistances, etc. in damage application
  lang/en.json
  less/v2/chat.less
  module/applications/components/damage-application.mjs
  module/documents/actor/actor.mjs
Labels: feature request, ux

#3278 [#3028] Prompt for concentration save when damage is taken
  module/documents/actor/actor.mjs
Labels: ux

#3252 Fix Adult white dragon wing attack
  packs/_source/monsters/dragon/adult-white-dragon.json
Labels: compendium content

#3279 [#3028] Clear dependent effects when concentration is broken.
  lang/en.json
  module/documents/active-effect.mjs
  module/documents/item.mjs
Labels: api, active effects

#3081 Adjust `ActiveEffect.fromStatusEffect` for V12
  dnd5e.mjs
  module/documents/active-effect.mjs
  module/documents/token.mjs
  templates/shared/active-effects.hbs
Labels: api

#3154 Move trackable attributes to setup
  dnd5e.mjs
Labels: api

#2629 [#2628] Fall back to first damage part for spell scaling
  module/documents/item.mjs
Labels: feature request, ux

#3066 [#2892] Quality of life changes to attack/damage roll messages
  lang/en.json
  less/v2/chat.less
  module/documents/chat-message.mjs
Labels: ui, ux

#3284 [#3038] Add setting to disable concentration
  lang/en.json
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/settings.mjs
Labels: api

#3235 [#893] Add system for selecting summoning placement
  module/canvas/_module.mjs
  module/canvas/token-placement.mjs
  module/data/item/fields/summons-field.mjs
Labels: epic, feature request, in progress, ux

#3287 Corrects default summon label
  module/applications/item/ability-use-dialog.mjs
Labels: bug

#3261 Update roll data and active effect wikis for 3.x
  wiki/Active-Effect-Guide.md
  wiki/Roll-Formulas.md
Labels: documentation

#3288 Document summoning features on wiki
  wiki/Home.md
  wiki/Summoning.md
  wiki/images/summoning/summoning-chat-message.jpg
  wiki/images/summoning/summoning-configuration.jpg
  wiki/images/summoning/summoning-item-details.jpg
  wiki/images/summoning/summoning-permission.jpg
  wiki/images/summoning/summoning-prompt.jpg
  wiki/images/summoning/summoning-summary.jpg
Labels: documentation

#3292 Add details about concentration to AE page
  wiki/Active-Effect-Guide.md
Labels: documentation

#3289 Add lookup enricher description to wiki, fix table heading
  wiki/Enrichers.md
  wiki/images/enricher-lookup.jpg
Labels: documentation

#3293 Update wiki with new hooks
  wiki/Active-Effect-Guide.md
  wiki/Advancement-Type-Item-Choice.md
  wiki/Hooks.md
  wiki/Roll-Formulas.md
Labels: documentation

#3302 [#3301] Remove everything related to conc if the item does not require conc at all
  module/applications/item/ability-use-dialog.mjs
Labels: bug, ui

#3312 [#3311] Fix bug with rolling upcast damage, fix Magic Missile scaling
  module/documents/item.mjs
  packs/_source/spells/1st-level/magic-missile.json
Labels: bug, compendium content

#3309 [#3308] Fix item changes not being retained on summons
  module/data/item/fields/summons-field.mjs
  module/data/token/token-system-flags.mjs
Labels: bug

#3348 Reinstate advancement data cleaning and ensure migrations are run before cleaning.
  module/data/fields.mjs
Labels: api, advancement

#3340 [#3269] Add spell components back to chat cards
  module/data/item/spell.mjs
Labels: feature request

#3325 [#3323, #3324] Fix advancement issues with missing linked items
  module/applications/advancement/item-choice-flow.mjs
  module/documents/advancement/item-grant.mjs
Labels: bug

#3303 [#3297] Prevent magical bonuses from applying if the item is not magical
  module/data/item/templates/equippable-item.mjs
Labels: bug

#3329 Add kh and kl as valid dice modifiers in Dice Scale Values
  module/utils.mjs
Labels: api

#3304 [#3263] Preserve dice modifiers when simplifying formulas
  module/dice/simplify-roll-formula.mjs
Labels: bug, dice

#3356 [#3354] Allow enricher rolls to target multiple actors
  module/documents/item.mjs
  module/enrichers.mjs
  module/utils.mjs
Labels: feature request, ux

#3328 [#3326] Add option to create spell scrolls with reduced description
  module/config.mjs
  module/documents/item.mjs
  packs/_source/rules/appendix-e-rules.json
  packs/_source/rules/chapter-11-dm-tools.json
Labels: feature request

#3331 [#3320] Add option to convert spell to scroll from context menu
  dnd5e.mjs
  lang/en.json
  module/applications/components/inventory.mjs
  module/documents/item.mjs
Labels: feature request, ux

#3330 [#3321] Allow spell scrolls to be created at increased level
  module/documents/item.mjs
Labels: feature request

#3173 [#1280] Add Ritual Spell Preparation Mode
  lang/en.json
  module/applications/actor/base-sheet.mjs
  module/config.mjs
Labels: ui, feature request

#3376 [#3320, #3321] Add configuration dialog for spell scroll creation
  lang/en.json
  module/applications/actor/base-sheet.mjs
  module/applications/actor/group-sheet.mjs
  module/data/user/user-system-flags.mjs
  module/documents/item.mjs
  templates/apps/spell-scroll-dialog.hbs
Labels: ui, feature request

#3343 [#1856] Allows HD & attribute consumption to be set on world items
  less/v1/items.less
  module/applications/item/item-sheet.mjs
  templates/items/parts/item-activation.hbs
Labels: feature request, ux

#3372 [#3242] Add ability to change creature type when summoning
  lang/en.json
  less/v1/items.less
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/summoning-config.mjs
  module/data/item/fields/summons-field.mjs
  module/documents/item.mjs
  templates/apps/ability-use.hbs
  templates/apps/summoning-config.hbs
Labels: feature request, in progress

#3359 [#3260] Add healing enricher & healing types to damage enricher
  lang/en.json
  module/dice/damage-roll.mjs
  module/enrichers.mjs
Labels: feature request

#3360 [#3358] Properly handle temporary hit points in `applyDamage`
  less/v2/chat.less
  less/variables.less
  module/applications/components/damage-application.mjs
  module/documents/actor/actor.mjs
Labels: bug, ui, ux
