Repository foundryvtt/dnd5e, pull requests merged in 2024-04, with the labels that each got.

#3344 [#1856, #3342] Allow UUIDs to be used as consumption targets
  lang/en.json
  less/v1/items.less
  module/applications/item/item-sheet.mjs
  module/data/abstract.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/spell.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/weapon.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  templates/items/parts/item-activation.hbs
Labels: feature request, api, ux

#3364 [#3353, #3361, #3362] Add support for NPC hit dice based on HP formula
  lang/en.json
  module/applications/actor/short-rest.mjs
  module/config.mjs
  module/data/actor/npc.mjs
  module/documents/actor/actor.mjs
  module/documents/advancement/hit-points.mjs
Labels: feature request, api, advancement

#3383 [#1833] Add level prerequisite to feature items used by item choice
  lang/en.json
  module/applications/advancement/item-choice-flow.mjs
  module/data/item/feat.mjs
  templates/items/feat.hbs
Labels: feature request, advancement

#3349 [#3345] Add Place Members buttons to group to place into scene
  lang/en.json
  module/applications/actor/group-sheet.mjs
  module/canvas/token-placement.mjs
  module/data/actor/group.mjs
  module/data/item/fields/summons-field.mjs
  templates/actors/tabs/group-members.hbs
Labels: feature request, ux

#3370 [#3092] Add custom journal page for subclasses
  dnd5e.mjs
  lang/en.json
  less/v1/journal.less
  module/applications/journal/class-page-sheet.mjs
  module/data/journal/_module.mjs
  module/data/journal/class.mjs
  module/data/journal/map.mjs
  module/data/journal/rule.mjs
  module/data/journal/subclass.mjs
  template.json
  templates/journal/page-class-edit.hbs
  templates/journal/page-class-view.hbs
  templates/journal/page-subclass-edit.hbs
  templates/journal/page-subclass-view.hbs
Labels: feature request

#3398 Add more SRD summoning spells
  packs/_source/monsters/summons/_folder.json
  packs/_source/monsters/summons/arcane-eye.json
  packs/_source/monsters/summons/arcane-hand.json
  packs/_source/monsters/summons/arcane-sword.json
  packs/_source/monsters/summons/mage-hand.json
  packs/_source/monsters/summons/unseen-servant.json
  packs/_source/spells/1st-level/unseen-servant.json
  packs/_source/spells/4th-level/arcane-eye.json
  packs/_source/spells/5th-level/arcane-hand.json
  packs/_source/spells/7th-level/arcane-sword.json
  packs/_source/spells/cantrip/mage-hand.json
Labels: compendium content

#3399 [#3368] Use starting equipment to class journal pages
  lang/en.json
  module/applications/journal/class-page-sheet.mjs
  packs/_source/rules/chapter-3-classes.json
  templates/journal/page-class-view.hbs
Labels: feature request, compendium content

#3109 [#1787] Add custom journal page for spell lists
  dnd5e.mjs
  lang/en.json
  less/v1/journal.less
  module/applications/journal/_module.mjs
  module/applications/journal/spells-page-sheet.mjs
  module/config.mjs
  module/data/journal/_module.mjs
  module/data/journal/spells.mjs
  template.json
  templates/journal/page-spell-list-edit.hbs
  templates/journal/page-spell-list-view.hbs
Labels: feature request, compendium content

#3395 [#1833] Add level prerequisites to eldritch invocations
  packs/_source/classfeatures/warlock/eldritch-invocations/ascendant-step.json
  packs/_source/classfeatures/warlock/eldritch-invocations/bewitching-whispers.json
  packs/_source/classfeatures/warlock/eldritch-invocations/chains-of-carceri.json
  packs/_source/classfeatures/warlock/eldritch-invocations/dreadful-word.json
  packs/_source/classfeatures/warlock/eldritch-invocations/lifedrinker.json
  packs/_source/classfeatures/warlock/eldritch-invocations/master-of-myriad-forms.json
  packs/_source/classfeatures/warlock/eldritch-invocations/minions-of-chaos.json
  packs/_source/classfeatures/warlock/eldritch-invocations/mire-the-mind.json
  packs/_source/classfeatures/warlock/eldritch-invocations/one-with-shadows.json
  packs/_source/classfeatures/warlock/eldritch-invocations/otherworldly-leap.json
  packs/_source/classfeatures/warlock/eldritch-invocations/sculptor-of-flesh.json
  packs/_source/classfeatures/warlock/eldritch-invocations/sign-of-ill-omen.json
  packs/_source/classfeatures/warlock/eldritch-invocations/thirsting-blade.json
  packs/_source/classfeatures/warlock/eldritch-invocations/visions-of-distant-realms.json
  packs/_source/classfeatures/warlock/eldritch-invocations/whispers-of-the-grave.json
  packs/_source/classfeatures/warlock/eldritch-invocations/witch-sight.json
Labels: compendium content

#3397 [#3322] Support individual optional ItemGrant features
  lang/en.json
  less/v1/advancement.less
  module/applications/advancement/item-grant-flow.mjs
  module/data/advancement/item-grant.mjs
  templates/advancement/item-grant-config.hbs
  templates/advancement/item-grant-flow.hbs
Labels: feature request, advancement

#3413 [#3412] Allow specifying creature size during summoning
  lang/en.json
  less/v1/items.less
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/summoning-config.mjs
  module/data/item/fields/summons-field.mjs
  module/documents/item.mjs
  templates/apps/ability-use.hbs
  templates/apps/summoning-config.hbs
Labels: feature request

#3439 [#3242] Add level limits to summoning profiles
  lang/en.json
  less/v1/items.less
  less/v2/apps.less
  less/v2/chat.less
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/summoning-config.mjs
  module/data/item/fields/summons-field.mjs
  templates/apps/summoning-config.hbs
Labels: feature request

#3394 [#3176] Powerful Critical Preserve flavor
  module/dice/damage-roll.mjs
Labels: bug, dice

#3409 [#3374] Add enchantment active effect that modifies an item
  lang/en.json
  less/v1/items.less
  module/applications/actor/base-config.mjs
  module/applications/item/item-sheet.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  templates/items/consumable.hbs
  templates/items/container.hbs
  templates/items/equipment.hbs
  templates/items/loot.hbs
  templates/items/tool.hbs
  templates/items/weapon.hbs
Labels: epic, feature request, in progress, active effects

#3411 [#3374] Add enchantment feature type, improve effects tab
  lang/en.json
  module/applications/components/effects.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/abstract.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/loot.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/documents/item.mjs
  templates/items/parts/item-action.hbs
  templates/shared/active-effects.hbs
Labels: epic, ui, feature request, active effects

#3464 [#3463] Default to config if skill's ability doesn't exist in src data
  module/applications/actor/base-sheet.mjs
Labels: bug

#3435 [#3418] Add enchantment configuration & restrictions
  lang/en.json
  less/v1/items.less
  less/v2/apps.less
  module/applications/components/effects.mjs
  module/applications/item/enchantment-config.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/item/_module.mjs
  module/data/item/feat.mjs
  module/data/item/fields/enchantment-field.mjs
  module/data/item/fields/summons-field.mjs
  module/data/item/spell.mjs
  templates/apps/enchantment-config.hbs
  templates/apps/summoning-config.hbs
  templates/items/feat.hbs
  templates/items/parts/item-action.hbs
Labels: epic, feature request, api

#3467 [#3453] Adjust how finesse is applied
  module/data/item/weapon.mjs
Labels: bug

#3484 Allow for null/undefined prerequisites value in items when advancing
  module/applications/advancement/item-choice-flow.mjs
Labels: bug

#2730 Add colors to damage types config
  module/config.mjs
Labels: feature request, api

#3491 [#3452] Don't replace `damage.active` set in `preCalculateDamage`
  module/documents/actor/actor.mjs
Labels: api

#3402 [#1833] Check level restriction for feats in ASIAdvancement
  lang/en.json
  module/applications/advancement/ability-score-improvement-flow.mjs
  module/applications/advancement/item-choice-flow.mjs
Labels: feature request

#3448 [#1787] Allow spell lists to be embedded
  less/v1/journal.less
  module/applications/journal/spells-page-sheet.mjs
  module/enrichers.mjs
  templates/journal/page-spell-list-table.hbs
  templates/journal/page-spell-list-view.hbs
Labels: feature request

#3487 [#2597] Add identifier field to background, add identifier input
  module/data/item/background.mjs
  templates/items/background.hbs
  templates/items/class.hbs
  templates/items/race.hbs
  templates/items/subclass.hbs
Labels: ui, feature request, api

#3437 [#3242] Support summoning more than one creature at a time
  lang/en.json
  module/applications/item/ability-use-dialog.mjs
  module/data/item/fields/summons-field.mjs
  templates/apps/summoning-config.hbs
Labels: feature request

#3493 [#3492] Add tooltips to active effects
  lang/en.json
  less/v2/inventory.less
  module/applications/actor/character-sheet-2.mjs
  module/documents/active-effect.mjs
  module/documents/item.mjs
  module/tooltips.mjs
  templates/effects/parts/effect-tooltip.hbs
  templates/shared/active-effects2.hbs
Labels: ui, feature request

#3485 [#2773] Display limited spell uses on sheet
  less/v2/inventory.less
  templates/actors/tabs/character-features.hbs
  templates/actors/tabs/character-spells.hbs
Labels: ui

#3482 [#1787] Support potentially unlinked spells in spell lists
  lang/en.json
  less/v1/journal.less
  module/applications/journal/spells-page-sheet.mjs
  module/applications/journal/spells-unlinked-config.mjs
  module/data/journal/spells.mjs
  module/data/shared/source-field.mjs
  module/utils.mjs
  templates/journal/page-spell-list-edit.hbs
  templates/journal/page-spell-list-unlinked-config.hbs
  templates/journal/page-spell-list-view.hbs
Labels: feature request

#3460 [#2892] Allow for selecting token via any chat message
  module/documents/chat-message.mjs
Labels: feature request, ux

#3468 [#1537, #3450] Add `ActivatedEffectTemplate` to tool items
  lang/en.json
  module/data/item/tool.mjs
  templates/items/tool.hbs
Labels: feature request

#3496 Store the level a spell was cast at when concentrating
  module/documents/active-effect.mjs
Labels: api

#3486 [#3071] Fix rendering issues with UP & DOWN item tooltips
  module/tooltips.mjs
Labels: bug

#3501 [#3500] Allow module item types to appear in inventory
  module/applications/actor/character-sheet.mjs
  module/data/abstract.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/loot.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
Labels: api
