Repository foundryvtt/dnd5e, pull requests merged in 2024-07, with the labels that each got.

#3556 [#2930]Added recharge logic to character-features.hbs
  lang/en.json
  less/v2/inventory.less
  module/applications/actor/character-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/actor/vehicle-sheet.mjs
  module/applications/components/inventory.mjs
  module/documents/item.mjs
  templates/actors/parts/actor-features.hbs
  templates/actors/tabs/character-features.hbs
Labels: ui, feature request

#3792 Updated/added tokens from new FA packs
  json/fa-token-mapping.json
  tokens/beast/DireWolf.webp
  tokens/beast/FlyingSnake.webp
  tokens/beast/GiantBadger.webp
  tokens/beast/GiantFrog.webp
  tokens/beast/Goat.webp
  tokens/beast/Panther.webp
  tokens/beast/Stirge.webp
  tokens/dragon/BlueDragonAncient.webp
  tokens/undead/Zombie.webp
Labels: compendium content

#3405 Attack targets iteration
  lang/en.json
  less/v2/chat.less
  module/documents/chat-message.mjs
  module/documents/item.mjs
Labels: ui, ux

#3766 [#3730] Add additional type-specific filters
  lang/en.json
  less/elements.less
  less/v2/compendium-browser.less
  module/applications/compendium-browser.mjs
  module/applications/components/_module.mjs
  module/applications/components/filter-state.mjs
  module/data/abstract.mjs
  module/data/actor/npc.mjs
  module/data/item/class.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/loot.mjs
  module/data/item/race.mjs
  module/data/item/spell.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/templates/item-description.mjs
  module/data/item/templates/physical-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/filter.mjs
  module/module-art.mjs
  templates/compendium/browser-sidebar-filters.hbs
Labels: epic, feature request, in progress, api

#3771 [#3761] Pass allowInteractive: false to blind rolls
  module/dice/d20-roll.mjs
  module/dice/damage-roll.mjs
  module/dice/dice.mjs
  module/documents/item.mjs
Labels: system: dice, compatibility

#3768 [#3742] Replace safeEval with evaluateSync in V12
  lang/en.json
  module/data/advancement/spell-config.mjs
  module/data/item/templates/activated-effect.mjs
  module/dice/simplify-roll-formula.mjs
  module/documents/actor/actor.mjs
  module/migration.mjs
  module/utils.mjs
Labels: bug, compatibility

#3808 Add inventory tab to NPC sheet v2.
  less/v2/inventory.less
  less/v2/npc.less
  module/applications/actor/npc-sheet-2.mjs
  module/applications/actor/npc-sheet.mjs
  templates/actors/npc-sheet-2.hbs
  templates/shared/inventory2.hbs
Labels: epic, ui, in progress

#3810 Add spells tab to NPC sheet v2.
  less/v2/npc.less
  module/applications/actor/npc-sheet-2.mjs
  templates/actors/npc-sheet-2.hbs
  templates/apps/skills-config.hbs
Labels: epic, ui, in progress

#3709 [#3705] Add option to completely replace map location page markers
  module/canvas/map-location-control-icon.mjs
  module/config.mjs
  module/data/journal/map.mjs
Labels: feature request, api

#3744 Fix polymorphing with Token Ring in V12
  module/documents/actor/actor.mjs
Labels: bug

#3732 Remove statuses that the actor is immune against
  module/documents/actor/actor.mjs
Labels: bug

#3679 [#3647] Display enchanted item count & limit on enchantment cards
  lang/en.json
  less/v2/chat.less
  module/applications/components/enchantment-application.mjs
Labels: ui, feature request, system: enchantment

#3745 fix dynamic token flashing on targeting
  module/canvas/token.mjs
Labels: bug

#3746 [#3730] Implement initial version of the Compendium Browser
  dnd5e.mjs
  icons/LICENSE
  icons/svg/items/background.svg
  icons/svg/items/class.svg
  icons/svg/items/race.svg
  icons/svg/items/subclass.svg
  icons/svg/monster.svg
  icons/svg/range-connector.svg
  icons/svg/vehicle.svg
  lang/en.json
  less/dnd5e.less
  less/elements.less
  less/v2/actors.less
  less/v2/apps.less
  less/v2/compendium-browser.less
  less/v2/dark/apps.less
  less/v2/dark/compendium-browser.less
  module/applications/_module.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/npc-sheet-2.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/compendium-browser.mjs
  module/applications/components/_module.mjs
  module/applications/components/checkbox.mjs
  module/applications/components/filter-state.mjs
  module/data/abstract.mjs
  module/data/actor/npc.mjs
  module/data/item/class.mjs
  module/data/item/consumable.mjs
  module/data/item/container.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/loot.mjs
  module/data/item/race.mjs
  module/data/item/spell.mjs
  module/data/item/templates/equippable-item.mjs
  module/data/item/templates/item-description.mjs
  module/data/item/templates/physical-item.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/filter.mjs
  module/module-art.mjs
  system.json
  templates/compendium/browser-entry.hbs
  templates/compendium/browser-footer.hbs
  templates/compendium/browser-header.hbs
  templates/compendium/browser-results.hbs
  templates/compendium/browser-sidebar-filters.hbs
  templates/compendium/browser-sidebar-search.hbs
  templates/compendium/browser-sidebar-types.hbs
  templates/compendium/browser-tabs.hbs
Labels: epic, ui, feature request, in progress, api

#3769 [#3652] Add config option to prevent damage aggregation in chat messages
  module/config.mjs
  module/documents/chat-message.mjs
Labels: api

#3790 [#3039] Add enricher for concentration checks
  module/enrichers.mjs
Labels: system: enrichers

#3818 Sleight of Hand Typo in Roll Formulas
  wiki/Roll-Formulas.md
Labels: documentation

#3789 [#2728] Add hint to all advancement types
  module/applications/advancement/advancement-config.mjs
  module/applications/advancement/size-flow.mjs
  module/applications/advancement/trait-flow.mjs
  module/applications/journal/class-page-sheet.mjs
  module/data/advancement/base-advancement.mjs
  module/data/advancement/item-choice.mjs
  module/data/advancement/size.mjs
  module/data/advancement/trait.mjs
  module/documents/advancement/trait.mjs
  templates/advancement/ability-score-improvement-flow.hbs
  templates/advancement/advancement-flow.hbs
  templates/advancement/hit-points-flow.hbs
  templates/advancement/item-choice-config.hbs
  templates/advancement/item-choice-flow.hbs
  templates/advancement/item-grant-flow.hbs
  templates/advancement/parts/advancement-controls.hbs
  templates/advancement/scale-value-flow.hbs
  templates/advancement/size-config.hbs
  templates/advancement/trait-config.hbs
Labels: system: advancement

#3753 Update staves
  packs/_source/items/weapon/staff-of-charming.json
  packs/_source/items/weapon/staff-of-fire.json
  packs/_source/items/weapon/staff-of-frost.json
  packs/_source/items/weapon/staff-of-healing.json
  packs/_source/items/weapon/staff-of-power.json
  packs/_source/items/weapon/staff-of-striking.json
  packs/_source/items/weapon/staff-of-swarming-insects.json
  packs/_source/items/weapon/staff-of-the-magi.json
  packs/_source/items/weapon/staff-of-the-python.json
  packs/_source/items/weapon/staff-of-the-woodlands.json
  packs/_source/items/weapon/staff-of-thunder-and-lightning.json
  packs/_source/items/weapon/staff-of-withering.json
Labels: compendium content

#3773 [#3772] Add configuration for CR-based summoning mode
  lang/en.json
  less/v1/items.less
  less/v2/apps.less
  module/applications/item/ability-use-dialog.mjs
  module/applications/item/summoning-config.mjs
  module/data/item/fields/summons-field.mjs
  templates/apps/ability-use.hbs
  templates/apps/summoning-config.hbs
Labels: feature request, system: summoning

#3764 [#3763] Select spellcasting ability based on spell's associated class
  module/data/item/spell.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
Labels: feature request

#3828 [#3772] Implement summoning based on CR
  lang/en.json
  module/applications/components/checkbox.mjs
  module/applications/item/ability-use-dialog.mjs
  module/data/item/fields/summons-field.mjs
Labels: feature request, system: summoning

#3832 [#3830] Update SRD spells with CR-based summoning
  packs/_source/spells/3rd-level/conjure-animals.json
  packs/_source/spells/4th-level/conjure-minor-elementals.json
  packs/_source/spells/4th-level/conjure-woodland-beings.json
  packs/_source/spells/5th-level/conjure-elemental.json
  packs/_source/spells/6th-level/conjure-fey.json
  packs/_source/spells/7th-level/conjure-celestial.json
Labels: compendium content, system: summoning

#3833 Update summoning page with details on CR-based summoning
  wiki/Summoning.md
  wiki/images/summoning/summoning-configuration.jpg
  wiki/images/summoning/summoning-cr-configuration.jpg
  wiki/images/summoning/summoning-cr-prompt.jpg
Labels: documentation

#3831 Add compendium browser information to wiki
  wiki/Compendium-Browser.md
  wiki/Home.md
  wiki/images/compendium-browser/advanced-mode.jpg
  wiki/images/compendium-browser/class-selection.jpg
  wiki/images/compendium-browser/standard-mode.jpg
Labels: documentation

#3835 Add journal page types to wiki & fix various issues
  wiki/Awards.md
  wiki/Home.md
  wiki/Journal-Pages.md
  wiki/Modifying-Your-Game-with-Scripts.md
  wiki/images/journal/pages-class-subclass.jpg
  wiki/images/journal/pages-map-location.jpg
  wiki/images/journal/pages-rule.jpg
  wiki/images/journal/pages-spell-list.jpg
Labels: documentation

#3851 Don't register Diagonal Movement Rule setting in V12
  module/settings.mjs
Labels: compatibility

#3869 [#3725] Add preparation warnings to v2 sheets.
  less/v2/actors.less
  less/v2/apps.less
  module/applications/actor/sheet-v2-mixin.mjs
  module/utils.mjs
  templates/actors/character-sheet-2.hbs
  templates/actors/npc-sheet-2.hbs
  templates/actors/parts/actor-warnings-dialog.hbs
Labels: ui

#3157 [#3156] Add setting to show attack roll result (AC check) card to players
  lang/en.json
  module/documents/chat-message.mjs
  module/settings.mjs
Labels: feature request, ux

#3870 [#3521, #3625, #3848] Drop V11 support
  dnd5e.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/advancement/advancement-selection.mjs
  module/applications/award.mjs
  module/applications/compendium-browser.mjs
  module/applications/components/checkbox.mjs
  module/applications/components/filter-state.mjs
  module/applications/item/ability-use-dialog.mjs
  module/applications/token-config.mjs
  module/canvas/_module.mjs
  module/canvas/grid.mjs
  module/canvas/shaders/parts/token-ring-shader-core.mjs
  module/canvas/shaders/token-ring-shader-v11.mjs
  module/canvas/token-ring.mjs
  module/canvas/token.mjs
  module/config.mjs
  module/data/advancement/spell-config.mjs
  module/data/fields.mjs
  module/data/item/fields/summons-field.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/shared/source-field.mjs
  module/dice/damage-roll.mjs
  module/dice/simplify-roll-formula.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/trait.mjs
  module/documents/chat-message.mjs
  module/documents/combatant.mjs
  module/documents/item.mjs
  module/documents/token.mjs
  module/enrichers.mjs
  module/migration.mjs
  module/settings.mjs
  module/utils.mjs
  system.json
  templates/apps/parts/dynamic-ring.hbs
Labels: compatibility

#3871 [#3117] Rework embeds to use core's implementation
  less/v1/journal.less
  module/data/abstract.mjs
  module/data/journal/class.mjs
  module/data/journal/map.mjs
  module/data/journal/rule.mjs
  module/data/journal/spells.mjs
  module/data/journal/subclass.mjs
  module/enrichers.mjs
Labels: api, compatibility

#3146 [#2138] Add BasicRoll type as part of the roll refactor
  dnd5e.mjs
  lang/en.json
  module/applications/_module.mjs
  module/applications/actor/hit-dice-config.mjs
  module/applications/actor/short-rest.mjs
  module/applications/api/_module.mjs
  module/applications/api/application.mjs
  module/applications/dice/_module.mjs
  module/applications/dice/roll-configuration-dialog.mjs
  module/dice/_module.mjs
  module/dice/basic-roll.mjs
  module/documents/actor/actor.mjs
  templates/dice/roll-buttons.hbs
  templates/dice/roll-configuration.hbs
  templates/dice/roll-formulas.hbs
Labels: epic, api, system: dice

#3757 [#461, #1964] Build base data model for activities
  lang/en.json
  module/data/_module.mjs
  module/data/activity/_module.mjs
  module/data/activity/base-activity.mjs
Labels: epic, feature request, in progress, api, system: activities

#3892 [#1964] Implement data structures for storing activities
  icons/LICENSE
  icons/svg/activity/utility.svg
  lang/en.json
  module/config.mjs
  module/data/_module.mjs
  module/data/activity/_module.mjs
  module/data/activity/base-activity.mjs
  module/data/fields.mjs
  module/data/fields/_module.mjs
  module/data/fields/activities-field.mjs
  module/data/fields/advancement-data-field.mjs
  module/data/fields/advancement-field.mjs
  module/data/fields/formula-field.mjs
  module/data/fields/identifier-field.mjs
  module/data/fields/local-document-field.mjs
  module/data/fields/mapping-field.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/spell.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/templates/activities.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/data/shared/_module.mjs
  module/data/shared/uses-field.mjs
  module/documents/_module.mjs
  module/documents/activity/_module.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/utility.mjs
  module/documents/item.mjs
  module/documents/mixins/pseudo-document.mjs
  templates/apps/document-create.hbs
Labels: epic, feature request, in progress, api, system: activities

#3902 Add getters for smallest and largest available hit dice
  module/documents/actor/hit-dice.mjs
Labels: feature request, api

#3885 [#3652] Fix aggregate damage CONFIG option
  module/documents/chat-message.mjs
Labels: api

#3904 [#1964] Add basic activity configuration sheet
  dnd5e.mjs
  lang/en.json
  module/applications/_module.mjs
  module/applications/activity/_module.mjs
  module/applications/activity/activity-sheet.mjs
  module/applications/api/application.mjs
  module/config.mjs
  module/data/activity/base-activity.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/utility.mjs
  module/documents/mixins/pseudo-document.mjs
  templates/activity/activation.hbs
  templates/activity/effect.hbs
  templates/activity/identity.hbs
  templates/activity/parts/activity-consumption.hbs
  templates/activity/parts/activity-targeting.hbs
  templates/activity/parts/activity-time.hbs
  templates/shared/uses-recovery.hbs
  templates/shared/uses-values.hbs
Labels: epic, ui, in progress, ux, system: activities

#3915 [#1964] Add attribute & material consumption & recharge recovery
  lang/en.json
  module/applications/activity/activity-sheet.mjs
  module/applications/item/item-sheet.mjs
  module/config.mjs
  module/data/activity/base-activity.mjs
  module/data/shared/uses-field.mjs
  module/documents/item.mjs
  module/utils.mjs
  templates/shared/uses-recovery.hbs
Labels: epic, feature request, in progress, system: activities

#3907 [#1964] Add applied effects data to activities & sheet
  lang/en.json
  module/applications/activity/activity-sheet.mjs
  module/data/activity/base-activity.mjs
  module/documents/mixins/pseudo-document.mjs
  templates/activity/effect.hbs
  templates/activity/parts/activity-consumption.hbs
  templates/activity/parts/activity-effects.hbs
  templates/shared/uses-recovery.hbs
Labels: ui, feature request, in progress, system: activities
