Repository foundryvtt/dnd5e, pull requests merged in 2024-06, with the labels that each got.

#3678 Update FAQ with new spell scroll instructions & 2024 rulebook plans
  wiki/FAQ.md
Labels: documentation

#3664 [#3663] Add option to hide advancement types from selection
  module/applications/advancement/advancement-selection.mjs
  module/config.mjs
Labels: api, system: advancement

#3665 [#3078] Allow special journal blocks to be used on other sheets
  less/v2/journal.less
Labels: feature request

#3708 [#3707] Fixes marker font, add shadow color, improve documentation
  module/canvas/_module.mjs
  module/canvas/map-location-control-icon.mjs
  module/config.mjs
Labels: bug, api

#3677 [#3676] Fix issue with summoning using pact slot not setting level
  module/applications/item/ability-use-dialog.mjs
Labels: bug

#3682 Document Item Use Enrichers
  wiki/Enrichers.md
  wiki/images/enricher-item.png
Labels: documentation

#3729 [#3696] Fix Item Choice replacement with dropped items
  module/applications/advancement/item-choice-flow.mjs
Labels: bug, system: advancement

#3733 Item enricher wiki format fix
  wiki/Enrichers.md
Labels: documentation

#3749 Update Swarm of Poisonous Snakes image path
  json/fa-token-mapping.json
Labels: compendium content

#3755 Add missing param level to Character Sheet aria-label string
  templates/actors/character-sheet-2.hbs
Labels: bug, localization, accessibility

#3431 [#1351] Allow spells to be linked to a specific class
  lang/en.json
  module/data/item/spell.mjs
  module/documents/actor/actor.mjs
  templates/items/spell.hbs
Labels: feature request, api
