Repository foundryvtt/dnd5e, pull requests merged in 2024-12, with the labels that each got.

#4500 Move hit dice data, add "additional" property
  lang/en.json
  module/applications/actor/config/hit-dice-config.mjs
  module/data/activity/fields/consumption-targets-field.mjs
  module/data/actor/character.mjs
  module/data/actor/templates/creature.mjs
  module/data/item/class.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/hit-dice.mjs
  module/documents/advancement/hit-points.mjs
  templates/items/class.hbs
  templates/items/details/details-class.hbs
  templates/journal/parts/journal-modern-traits.hbs
Labels: api, migration

#4649 Use the template's `getSnappedPosition` method when dragging preview
  module/canvas/ability-template.mjs
Labels: api

#4793 [#3355] Add attack enricher
  lang/en.json
  module/documents/activity/attack.mjs
  module/enrichers.mjs
Labels: system: enrichers

#4784 [#4718] Automatically consume legendary actions
  lang/en.json
  module/applications/activity/activity-usage-dialog.mjs
  module/documents/activity/mixin.mjs
  templates/activity/activity-usage-consumption.hbs
Labels: feature request, ux, system: activities

#4785 [#2359] Automatically reset legendary actions during combat
  module/data/abstract.mjs
  module/data/actor/npc.mjs
  module/documents/combat.mjs
  module/documents/combatant.mjs
Labels: feature request, ux

#4813 [#4812] Add setting to use initiative scores rather than rolls
  lang/en.json
  module/documents/actor/actor.mjs
  module/settings.mjs
Labels: feature request

#4822 [#4778, #4820] Fix minor issues on AE wiki page.
  wiki/Active-Effect-Guide.md
Labels: documentation

#4796 [#3357] Support variable types & multiple damage parts in enricher
  lang/en.json
  less/v1/chat.less
  less/v2/journal.less
  module/enrichers.mjs
Labels: feature request, system: enrichers

#4792 [#3798] Add embeddable NPC statblocks
  lang/en.json
  less/v2/journal.less
  module/applications/actor/npc-sheet-2.mjs
  module/config.mjs
  module/data/actor/npc.mjs
  module/utils.mjs
  templates/actors/embeds/npc-embed.hbs
Labels: feature request, in progress, system: enrichers

#4823 [#2568, #3355] Add activity linking for attack & damage enrichers
  module/config.mjs
  module/data/item/weapon.mjs
  module/enrichers.mjs
Labels: feature request, system: enrichers

#4832 Tidy up mixin definitions
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/api/application-v2-mixin.mjs
  module/documents/activity/mixin.mjs
  module/documents/mixins/document.mjs
  module/documents/mixins/flags.mjs
  module/documents/mixins/pseudo-document.mjs
  system.json
Labels: api

#4814 [#4751] Split `BasicRoll#build` into three parts
  module/data/shared/uses-field.mjs
  module/dice/basic-roll.mjs
  module/documents/activity/attack.mjs
Labels: api, system: dice

#4817 [#4798] Add option to conceal item descriptions from players
  lang/en.json
  less/v2/chat.less
  module/applications/_module.mjs
  module/applications/bastion.mjs
  module/applications/compendium-browser-source-config.mjs
  module/applications/compendium-browser.mjs
  module/applications/settings/_module.mjs
  module/applications/settings/base-settings.mjs
  module/applications/settings/bastion-settings.mjs
  module/applications/settings/compendium-browser-settings.mjs
  module/applications/settings/module-art-settings.mjs
  module/applications/settings/visibility-settings.mjs
  module/data/abstract.mjs
  module/documents/activity/mixin.mjs
  module/documents/chat-message.mjs
  module/module-art.mjs
  module/settings.mjs
  module/utils.mjs
  templates/apps/bastion-config.hbs
  templates/chat/activity-card.hbs
  templates/chat/item-card.hbs
  templates/settings/base-config.hbs
  templates/settings/bastion-config.hbs
  templates/shared/fields/fieldlist.hbs
Labels: feature request

#4829 [#4828] Add extended formatting option to attack & damage enrichers
  lang/en.json
  module/data/activity/attack-data.mjs
  module/enrichers.mjs
Labels: feature request, system: enrichers

#4847 Add parameter for preventing subsequent actions
  module/documents/activity/mixin.mjs
Labels: api

#4841 [#4840] Switch custom elements to extend `AbstractFormInputElement`
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/components/checkbox.mjs
  module/applications/components/proficiency-cycle.mjs
  module/applications/components/slide-toggle.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
Labels: api

#4860 [#4859] Add option to use lookup enricher on activity
  module/enrichers.mjs
Labels: system: enrichers

#4852 [#4851] Add option to override casting ability in `CastActivity`
  lang/en.json
  module/applications/activity/cast-sheet.mjs
  module/data/activity/cast-data.mjs
  module/documents/activity/cast.mjs
  templates/activity/parts/cast-details.hbs
Labels: feature request, system: activities

#4850 [#4827] Add hook for when NPC stat blocks are rendered
  module/data/actor/npc.mjs
Labels: api, system: enrichers

#4853 [#3958] Add formatters for distance and weight units
  lang/en.json
  less/v2/inventory.less
  module/applications/activity/activity-sheet.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/item/item-sheet-2.mjs
  module/applications/shared/movement-senses-config.mjs
  module/config.mjs
  module/data/advancement/scale-value.mjs
  module/data/item/race.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/templates/physical-item.mjs
  module/data/item/weapon.mjs
  module/data/shared/range-field.mjs
  module/data/shared/target-field.mjs
  module/utils.mjs
  templates/activity/columns/activity-column-range.hbs
  templates/actors/tabs/creature-spells.hbs
  templates/advancement/scale-value-config.hbs
Labels: api, localization, breaking

#4836 [#3798] Add limited uses labels for NPC stat block actions
  lang/en.json
  module/data/activity/base-activity.mjs
  module/data/activity/fields/consumption-targets-field.mjs
  module/data/actor/npc.mjs
  module/data/item/templates/activities.mjs
  module/data/shared/uses-field.mjs
Labels: system: enrichers

#4838 Track advantage modes
  module/data/fields/_module.mjs
  module/data/fields/advantage-mode-field.mjs
  module/data/shared/roll-config-field.mjs
Labels: api

#4839 [#4384, #4828] Adds plural targets, add target to attack enricher
  dnd5e.mjs
  lang/en.json
  module/applications/activity/activity-sheet.mjs
  module/applications/item/item-sheet-2.mjs
  module/config.mjs
  module/data/activity/base-activity.mjs
  module/data/shared/target-field.mjs
  module/enrichers.mjs
  module/utils.mjs
  templates/items/parts/item-activation.hbs
  templates/shared/fields/field-targets.hbs
Labels: localization, breaking, system: enrichers

#4864 [#4846] Add "Passive Trait" property to features for group control
  lang/en.json
  module/applications/actor/character-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/config.mjs
  module/data/actor/npc.mjs
Labels: feature request

#4835 [#4826] Rename "Utility" activity to "Use"
  lang/en.json
Labels: localization, system: activities

#4867 [#4856] Show temporary spell slots
  icons/svg/spell-slot.svg
  lang/en.json
  less/v2/inventory.less
  module/applications/actor/sheet-v2-mixin.mjs
Labels: ui, ux

#2073 [#2071] Default to metric length units for movement and senses
  dnd5e.mjs
  lang/en.json
  module/applications/actor/base-sheet.mjs
  module/applications/shared/movement-senses-config.mjs
  module/config.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/item/race.mjs
  module/data/item/templates/physical-item.mjs
  module/data/shared/movement-field.mjs
  module/data/shared/senses-field.mjs
  module/data/shared/target-field.mjs
  module/documents/actor/actor.mjs
  module/settings.mjs
  module/utils.mjs
Labels: localization

#4868 [#4866] Display nicer text for a dc-less passive skill enricher
  lang/en.json
  module/enrichers.mjs
Labels: system: enrichers

#4933 Avoid crash when getting scene targets when canvas is disabled
  module/utils.mjs
Labels: bug

#4904 [#4873] Fix enricher pattern to be able to contain ] symbol in item name
  module/enrichers.mjs
Labels: system: enrichers

#4926 Show ability-mod-using bonuses on sheet
  module/data/actor/templates/common.mjs
Labels: feature request

#4925 [#4924] Change `parseInt` to `Number`
  module/data/activity/base-activity.mjs
Labels: bug

#4940 Update damage types example
  wiki/Modifying-Your-Game-with-Scripts.md
Labels: documentation

#4941 Minor wiki updates
  wiki/Active-Effect-Guide.md
Labels: documentation

#4833 Improve consistency of Item Sheet display
  less/v2/forms.less
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/components/checkbox.mjs
  module/applications/components/inventory.mjs
  module/applications/item/item-compendium.mjs
  module/applications/item/item-directory.mjs
  module/applications/item/item-sheet.mjs
  module/applications/item/sheet-v2-mixin.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/data/item/consumable.mjs
  module/data/item/weapon.mjs
  templates/actors/parts/actor-classes.hbs
  templates/actors/tabs/character-details.hbs
  templates/shared/inventory2.hbs
Labels: ui, ux
