Repository foundryvtt/dnd5e, pull requests merged in 2025-05, with the labels that each got.

#5495 [#5072] Improvements to subclass summary table generation.
  module/applications/journal/class-page-sheet.mjs
  module/documents/actor/actor.mjs
Labels: ux, system: journals

#5594 [#5577] Fixed actor sheet tool rolls
  module/applications/actor/api/base-actor-sheet.mjs
Labels: system: actor sheets

#5590 [#5589] Changed to getChatMessageContextOptions hook and changed addChatMessageContextOptions function accordingly
  dnd5e.mjs
  module/documents/chat-message.mjs
Labels: compatibility

#5615 [#5601] Change item to entry in _onRollRecharge
  module/applications/components/inventory.mjs
Labels: system: actor sheets

#5560 Resolve some deprecation warnings for moved implementations
  module/applications/activity/order-usage-dialog.mjs
  module/applications/activity/summon-sheet.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/deprecated/base-sheet.mjs
  module/applications/actor/group-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/advancement/advancement-config-v2.mjs
  module/applications/advancement/advancement-config.mjs
  module/applications/advancement/advancement-flow.mjs
  module/applications/advancement/advancement-migration-dialog.mjs
  module/applications/compendium-browser.mjs
  module/applications/components/enchantment-application.mjs
  module/applications/components/inventory.mjs
  module/applications/item/config/starting-equipment-config.mjs
  module/applications/item/container-sheet.mjs
  module/applications/item/item-directory.mjs
  module/applications/item/item-sheet.mjs
  module/applications/journal/class-page-sheet.mjs
  module/applications/journal/journal-editor.mjs
  module/applications/journal/journal-sheet.mjs
  module/applications/journal/map-page-sheet.mjs
  module/applications/journal/rule-page-sheet.mjs
  module/applications/journal/spells-page-sheet.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/data/abstract.mjs
  module/data/abstract/chat-message-data-model.mjs
  module/data/actor/npc.mjs
  module/data/chat-message/rest-message-data.mjs
  module/data/journal/rule.mjs
  module/documents/active-effect.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/order.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/bastion.mjs
  module/documents/item.mjs
  module/documents/mixins/pseudo-document.mjs
  module/documents/token.mjs
  module/enrichers.mjs
  module/tooltips.mjs
Labels: compatibility

#5638 [#5530] Fix embedded Document marshalling in synthetic Actor transformations.
  module/documents/actor/actor.mjs
Labels: bug, api

#5426 `TargetedApplicationMixin#buildTargetsList` throws if a token that has no actor is selected
  module/applications/components/targeted-application-mixin.mjs
Labels: bug

#5640 [#5605] Prevent blank values in duration & range units
  module/data/shared/duration-field.mjs
  module/data/shared/range-field.mjs
Labels: compatibility

#5628 [#5569] Simplifies tracker sheet styling to match SRD.
  less/v2/journal.less
Labels: ui, system: journals, compendium content: 2024

#5639 [#5612] Add ability to specify source books on a per-pack basis
  module/data/shared/source-field.mjs
  system.json
Labels: api

#5661 [#5649] Enable highlight matches plugin for ProseMirror editors
  module/applications/api/application-v2-mixin.mjs
Labels: system: actor sheets, system: item sheets

#5670 [#5465] Change "apply damage" to always remove hp, "apply healing" to always add hp
  lang/en.json
  module/documents/chat-message.mjs
Labels: bug, ux

#5684 Deprecation Warning for `instanceof Token` in `blindsight.testVisibility()`
  module/canvas/detection-modes/blindsight.mjs
Labels: bug

#5623 Added option to not reset temp max hp during long rest
  lang/en.json
  module/applications/actor/rest/base-rest-dialog.mjs
  module/config.mjs
  templates/actors/rest/long-rest.hbs
  templates/actors/rest/short-rest.hbs
Labels: system: rests

#5712 [#4727] [#5692] Set spell source class appropriately during Advancement.
  module/data/advancement/spell-config.mjs
Labels: bug, system: advancement

#5561 [#2834] Add guidance for modify SVGs to work with system
  wiki/Modifying-Your-Game-with-Scripts.md
Labels: documentation

#5665 Update Modifying-Your-Game-with-Scripts wikiPage to correct incorrect Variable
  wiki/Modifying-Your-Game-with-Scripts.md
Labels: documentation

#5632 Bring ActiveEffect5e#isSuppressed in line with core expectations
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
Labels: api, system: active effects
