Repository foundryvtt/dnd5e, pull requests merged in 2025-01, with the labels that each got.

#4901 Allow natural weapons to make ranged attacks without "thrown"
  lang/en.json
  module/applications/activity/attack-sheet.mjs
  module/config.mjs
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/data/item/weapon.mjs
  module/enrichers.mjs
Labels: bug, system: activities

#4887 Update build script with more automation & flexibility
  .github/workflows/release.yml
  foundryvtt.json
Labels: tooling

#4892 Adds a new "Resist" button beneath saving throws that have been
  lang/en.json
  less/v2/chat.less
  module/applications/activity/activity-usage-dialog.mjs
  module/applications/actor/npc-sheet-2.mjs
  module/data/actor/npc.mjs
  module/documents/activity/mixin.mjs
  module/documents/chat-message.mjs
  templates/actors/npc-sheet-2.hbs
  templates/actors/npc-sheet.hbs
Labels: feature request, ux

#4899 [#4898] Add support for multiple abilities in single save enricher
  module/documents/actor/actor.mjs
  module/enrichers.mjs
  templates/chat/request-card.hbs
Labels: system: enrichers

#4919 [#4898] Add support for multiple skills/tools in single enricher
  module/enrichers.mjs
Labels: system: enrichers

#4902 [#3798] Add gear to embedded NPCs
  module/data/actor/npc.mjs
Labels: system: enrichers

#4875 [#1982] Add support for ranged communication like telepathy
  .eslintrc.json
  dnd5e.mjs
  lang/en.json
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/config/languages-config.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/config.mjs
  module/data/actor/character.mjs
  module/data/actor/fields/damage-trait-field.mjs
  module/data/actor/fields/simple-trait-field.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/traits.mjs
  module/data/actor/vehicle.mjs
  templates/actors/config/languages-config.hbs
  templates/actors/npc-sheet-2.hbs
  templates/actors/parts/actor-trait-pills.hbs
  templates/actors/tabs/character-details.hbs
Labels: feature request

#4871 [#2359, #4799] Add new turn chat message
  dnd5e.mjs
  lang/en.json
  less/v2/chat.less
  module/data/_module.mjs
  module/data/abstract/_module.mjs
  module/data/abstract/chat-message-data-model.mjs
  module/data/chat-message/_module.mjs
  module/data/chat-message/fields/_module.mjs
  module/data/chat-message/fields/deltas-field.mjs
  module/data/chat-message/turn-message-data.mjs
  module/documents/chat-message.mjs
  module/documents/combatant.mjs
  module/utils.mjs
  system.json
  templates/chat/turn-card.hbs
Labels: feature request, system: combat

#4908 [#3798, #4644] Add "All Languages", group primordial languages
  lang/en.json
  module/applications/actor/config/traits-config.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/advancement/trait-config.mjs
  module/config.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/traits.mjs
  module/documents/actor/trait.mjs
  templates/apps/parts/trait-list.hbs
  templates/apps/parts/traits-list.hbs
Labels: feature request, system: advancement

#4911 [#4861] Add combat activation types that display in turn message
  lang/en.json
  less/v2/apps.less
  less/v2/chat.less
  module/applications/actor/npc-sheet.mjs
  module/config.mjs
  module/data/abstract.mjs
  module/data/actor/npc.mjs
  module/data/chat-message/turn-message-data.mjs
  module/documents/combat.mjs
  module/documents/combatant.mjs
  templates/chat/turn-card.hbs
Labels: feature request, system: combat

#1845 [#1795] Add ability for items added with through advancement to trigger their own advancements
  lang/en.json
  less/dnd5e.less
  less/v2/advancement.less
  module/applications/advancement/advancement-manager.mjs
  module/applications/advancement/subclass-flow.mjs
  module/data/advancement/_module.mjs
  module/data/advancement/subclass.mjs
  module/data/fields/local-document-field.mjs
  module/documents/advancement/subclass.mjs
  templates/advancement/advancement-visualizer.hbs
  templates/advancement/subclass-flow.hbs
Labels: system: advancement

#4961 [#4862] Add activity-linked check & save enrichers
  module/enrichers.mjs
Labels: system: enrichers

#4765 [#4708] Convert `AdvancementManager` to V2 app & styles
  lang/en.json
  less/v1/advancement.less
  less/v2/advancement.less
  module/applications/advancement/advancement-manager.mjs
  templates/advancement/advancement-manager.hbs
Labels: ui, system: advancement

#4959 [#4958] Allow features to be repeatable in item choice
  lang/en.json
  module/applications/advancement/ability-score-improvement-flow.mjs
  module/applications/advancement/item-choice-flow.mjs
  module/data/item/feat.mjs
  templates/items/details/details-feat.hbs
Labels: feature request, system: advancement

#4969 [#3695] Add ASI Advancement support to feature items
  module/config.mjs
  module/data/item/feat.mjs
Labels: feature request, system: advancement

#4893 [#4215] Ensure exhaustion speed reduction matches movement units
  module/config.mjs
  module/data/actor/templates/attributes.mjs
  module/utils.mjs
Labels: bug, localization

#4722 [#4708] Redesign `ItemGrantConfig` for V2, implement drag-drop
  dnd5e.mjs
  lang/en.json
  less/dnd5e.less
  less/v2/advancement.less
  module/applications/advancement/advancement-config-v2.mjs
  module/applications/advancement/advancement-config.mjs
  module/applications/advancement/item-grant-config.mjs
  module/data/advancement/item-grant.mjs
  module/data/advancement/spell-config.mjs
  module/documents/advancement/advancement.mjs
  module/documents/advancement/item-grant.mjs
  templates/advancement/advancement-spell-config-section.hbs
  templates/advancement/item-choice-config.hbs
  templates/advancement/item-grant-config-details.hbs
  templates/advancement/item-grant-config-items.hbs
  templates/advancement/item-grant-config.hbs
  templates/advancement/parts/advancement-spell-config.hbs
Labels: ui, system: advancement

#4912 [#3629, #4142] Add units to container capacity, add volume capacity
  lang/en.json
  module/config.mjs
  module/data/item/container.mjs
  module/settings.mjs
  module/utils.mjs
  templates/items/details/details-container.hbs
  templates/shared/inventory.hbs
Labels: feature request, localization

#4743 [#4739] Redesign short & long rest dialogs for V2 app & styles
  dnd5e.mjs
  lang/en.json
  less/v2/activities.less
  less/v2/apps.less
  less/v2/forms.less
  less/variables.less
  module/applications/actor/_module.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/long-rest.mjs
  module/applications/actor/rest/base-rest-dialog.mjs
  module/applications/actor/rest/long-rest-dialog.mjs
  module/applications/actor/rest/short-rest-dialog.mjs
  module/applications/actor/short-rest.mjs
  module/applications/api/dialog.mjs
  module/data/actor/character.mjs
  module/documents/actor/actor.mjs
  templates/actors/character-sheet-2.hbs
  templates/actors/character-sheet.hbs
  templates/actors/config/hit-dice-config.hbs
  templates/actors/npc-sheet-2.hbs
  templates/actors/rest/long-rest.hbs
  templates/actors/rest/short-rest.hbs
  templates/actors/tabs/group-members.hbs
  templates/apps/long-rest.hbs
  templates/apps/short-rest.hbs
Labels: ui

#4749 [#3958] Improve localization of rest messages
  lang/en.json
  module/applications/actor/rest/base-rest-dialog.mjs
  module/applications/actor/rest/long-rest-dialog.mjs
  module/applications/actor/rest/short-rest-dialog.mjs
  module/config.mjs
  module/documents/actor/actor.mjs
  module/utils.mjs
Labels: api, localization, system: rests

#4943 Add examples & option tables for system enrichers
  wiki/Enrichers.md
Labels: documentation

#4903 Display activity uses on spells tab for spells from Cast activity
  module/applications/actor/sheet-v2-mixin.mjs
  templates/actors/tabs/creature-spells.hbs
Labels: ui, system: activities

#4524 [#4249] Add "Select Class" pill when in editing mode
  module/applications/actor/character-sheet-2.mjs
  module/applications/compendium-browser.mjs
  templates/actors/character-sheet-2.hbs
  templates/actors/parts/actor-classes.hbs
Labels: ui, feature request, system: compendium browser

#5001 [#3798] Display in-lair XP on embedded NPC stat blocks
  lang/en.json
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/npc-sheet-2.mjs
  module/applications/award.mjs
  module/data/actor/character.mjs
  module/data/actor/group.mjs
  module/data/actor/npc.mjs
  module/enrichers.mjs
  module/utils.mjs
  templates/actors/character-sheet-2.hbs
  templates/actors/group-sheet.hbs
  templates/actors/tabs/group-members.hbs
  templates/apps/award.hbs
Labels: feature request, system: enrichers

#5009 [#5006] Fix issues around misconfigured save abilities
  module/applications/actor/character-sheet-2.mjs
  module/data/activity/save-data.mjs
Labels: bug

#4766 [#4708] Redesign `AbilityScoreImprovementConfig` for V2
  lang/en.json
  less/v2/advancement.less
  module/applications/advancement/ability-score-improvement-config.mjs
  module/applications/advancement/item-grant-config.mjs
  module/applications/api/pseudo-document-sheet.mjs
  module/applications/components/checkbox.mjs
  templates/advancement/ability-score-improvement-config-details.hbs
  templates/advancement/ability-score-improvement-config-scores.hbs
  templates/advancement/ability-score-improvement-config.hbs
  templates/advancement/parts/advancement-ability-score-control-v2.hbs
Labels: ui, system: advancement

#4767 [#4708] Redesign `ScaleValueConfig` for V2
  lang/en.json
  less/v1/advancement.less
  less/v2/advancement.less
  less/v2/forms.less
  module/applications/advancement/scale-value-config.mjs
  module/data/advancement/scale-value.mjs
  module/documents/advancement/scale-value.mjs
  templates/advancement/item-choice-config-levels.hbs
  templates/advancement/scale-value-config-details.hbs
  templates/advancement/scale-value-config-levels.hbs
  templates/advancement/scale-value-config.hbs
Labels: ui, system: advancement

#4768 [#4708] Redesign `SizeConfig` for V2 app and styles
  lang/en.json
  less/v1/advancement.less
  less/v2/advancement.less
  less/v2/forms.less
  module/applications/advancement/size-config.mjs
  module/documents/advancement/size.mjs
  templates/advancement/size-config-details.hbs
  templates/advancement/size-config.hbs
Labels: ui, system: advancement

#4970 [#3695] Adjust ASI advancement in modern rules to be feat-first
  lang/en.json
  less/v1/advancement.less
  module/applications/advancement/ability-score-improvement-flow.mjs
  module/documents/advancement/ability-score-improvement.mjs
  templates/advancement/ability-score-improvement-flow.hbs
Labels: ui, system: advancement

#4974 [#4973] Add auto-generated ASI description to class journals
  lang/en.json
  module/applications/journal/class-page-sheet.mjs
  module/utils.mjs
Labels: system: journals

#4996 [#4929, #4931] Fix mountable data models, add cover to feat sheet
  lang/en.json
  module/applications/actor/vehicle-sheet.mjs
  module/applications/item/item-sheet-2.mjs
  module/config.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/templates/mountable.mjs
  module/data/item/weapon.mjs
  templates/items/details/details-feat.hbs
  templates/items/details/details-mountable.hbs
  templates/items/parts/item-mountable.hbs
Labels: bug

#4857 [#3214, #4738] Add combat-related usage recovery periods
  lang/en.json
  module/applications/activity/activity-sheet.mjs
  module/applications/item/item-sheet-2.mjs
  module/config.mjs
  module/data/abstract.mjs
  module/data/activity/fields/consumption-targets-field.mjs
  module/data/actor/npc.mjs
  module/documents/activity/mixin.mjs
  module/documents/combat.mjs
  module/documents/combatant.mjs
  templates/items/details/details-feat.hbs
  templates/items/feat.hbs
  templates/shared/fields/field-uses.hbs
Labels: feature request, system: combat

#4980 Update enricher documentation to match changes in 4.2
  wiki/Enrichers.md
Labels: documentation

#5013 Update activity pages with new changes
  wiki/Activity-Type-Cast.md
  wiki/Activity-Type-Utility.md
  wiki/images/activities/cast-effect.jpg
  wiki/images/activities/utility-effect.jpg
  wiki/images/activities/utility-identity.jpg
Labels: documentation

#4982 Update documentation for Advancement system
  wiki/Advancement-Type-Ability-Score-Improvement.md
  wiki/Advancement-Type-Hit-Points.md
  wiki/Advancement-Type-Item-Choice.md
  wiki/Advancement-Type-Item-Grant.md
  wiki/Advancement-Type-Scale-Value.md
  wiki/Advancement-Type-Size.md
  wiki/Advancement-Type-Subclass.md
  wiki/Advancement-Type-Trait.md
  wiki/Advancement.md
  wiki/Home.md
  wiki/images/advancement/asi-configuration-class.jpg
  wiki/images/advancement/asi-configuration-race.jpg
  wiki/images/advancement/asi-flow-class.jpg
  wiki/images/advancement/asi-flow-modern.jpg
  wiki/images/advancement/asi-flow-race.jpg
  wiki/images/advancement/hit-points-configuration.jpg
  wiki/images/advancement/hit-points-flow-first-level.jpg
  wiki/images/advancement/hit-points-flow-other-levels.jpg
  wiki/images/advancement/item-choice-configuration.jpg
  wiki/images/advancement/item-choice-flow.jpg
  wiki/images/advancement/item-grant-configuration-normal.jpg
  wiki/images/advancement/item-grant-configuration-spells.jpg
  wiki/images/advancement/item-grant-flow.jpg
  wiki/images/advancement/scale-value-configuration.jpg
  wiki/images/advancement/scale-value-flow.jpg
  wiki/images/advancement/size-configuration.jpg
  wiki/images/advancement/size-flow.jpg
  wiki/images/advancement/subclass-flow-initial.jpg
  wiki/images/advancement/subclass-flow-selected.jpg
  wiki/images/advancement/trait-advancement-list.jpg
  wiki/images/advancement/trait-configuration-choices.jpg
  wiki/images/advancement/trait-configuration-grants.jpg
  wiki/images/advancement/trait-flow-choices.jpg
  wiki/images/advancement/trait-flow-grants.jpg
Labels: documentation

#4975 [#3788] Add enhanced rest chat message with recovery info
  lang/en.json
  less/v2/chat.less
  module/data/chat-message/_module.mjs
  module/data/chat-message/fields/deltas-field.mjs
  module/data/chat-message/rest-message-data.mjs
  module/data/chat-message/turn-message-data.mjs
  module/documents/actor/actor.mjs
  module/utils.mjs
  system.json
  templates/chat/parts/card-deltas.hbs
  templates/chat/rest-card.hbs
  templates/chat/turn-card.hbs
Labels: ui, feature request, system: rests

#5030 [#5040] Fix human readable attribute labels for activities
  module/utils.mjs
Labels: bug

#5054 [#5053] Adds DeathConfig to module\applications\actor\_module.mjs
  module/applications/actor/_module.mjs
Labels: api

#4922 Add advantage modes to `abilities` objects
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/templates/common.mjs
  module/data/shared/roll-config-field.mjs
  templates/actors/character-sheet.hbs
  templates/actors/npc-sheet-2.hbs
  templates/actors/npc-sheet.hbs
  templates/actors/tabs/character-details.hbs
Labels: feature request

#4909 [#2094] Move actor data preparation into data models
  module/applications/activity/attack-sheet.mjs
  module/applications/advancement/advancement-selection.mjs
  module/applications/token-config.mjs
  module/data/abstract.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/templates/creature.mjs
  module/data/actor/templates/traits.mjs
  module/data/actor/vehicle.mjs
  module/data/item/templates/action.mjs
  module/data/shared/movement-field.mjs
  module/data/shared/senses-field.mjs
  module/documents/actor/actor.mjs
  module/documents/token.mjs
Labels: api

#5062 [#5049] Add view option to item context menus.
  module/applications/components/inventory.mjs
  module/applications/item/item-compendium.mjs
  module/applications/item/item-directory.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
Labels: ui, ux

#5071 Update Starter Heroes with fresh items and add favorites
  packs/_source/heroes/akra-dragonborn-cleric.json
  packs/_source/heroes/aoth-human-druid.json
  packs/_source/heroes/beiro-half-elf-bard.json
  packs/_source/heroes/krusk-half-orc-paladin.json
  packs/_source/heroes/merric-halfling-barbarian.json
  packs/_source/heroes/morthos-tiefling-sorcerer.json
  packs/_source/heroes/perrin-halfling-monk.json
  packs/_source/heroes/quillathe-elf-ranger.json
  packs/_source/heroes/randal-human-fighter.json
  packs/_source/heroes/riswynn-dwarf-rogue.json
  packs/_source/heroes/sefris-half-elf-warlock.json
  packs/_source/heroes/zanna-gnome-wizard.json
Labels: compendium content

#4549 [#4548] Save chat tray state between message renders
  dnd5e.mjs
  module/applications/_module.mjs
  module/applications/chat-log.mjs
  module/documents/chat-message.mjs
Labels: bug, ui

#4476 [#4408] Add roll data to journal entry pages
  dnd5e.mjs
  module/documents/_module.mjs
  module/documents/journal-entry-page.mjs
Labels: feature request, api, system: journals

#4624 [#4623] Add `createScrollFromCompendiumSpell` that uses Cast
  module/documents/item.mjs
Labels: feature request

#4897 [#3667] Add grouping to initiative tracker
  dnd5e.mjs
  lang/en.json
  less/v2/apps.less
  module/applications/combat/combat-tracker.mjs
  module/documents/combat.mjs
  module/documents/combatant.mjs
Labels: ui, feature request, system: combat

#4879 [#4876] Add support for modifier keys during drag operations
  .eslintrc.json
  dnd5e.mjs
  lang/en.json
  less/v2/apps.less
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/group-sheet.mjs
  module/applications/actor/sheet-mixin.mjs
  module/applications/item/container-sheet.mjs
  module/applications/item/item-compendium.mjs
  module/applications/item/item-directory.mjs
  module/applications/mixins/drag-drop-mixin.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/drag-drop.mjs
  module/settings.mjs
  module/utils.mjs
  templates/shared/inventory2.hbs
Labels: ux

#4913 [#3617] Add enchantment effect for modifying damage types
  module/applications/activity/activity-sheet.mjs
  module/data/active-effect/enchantment.mjs
  module/data/activity/base-activity.mjs
  templates/activity/parts/damage-part.hbs
Labels: feature request, system: enchantment

#5080 [#3754] Add `system.damage.bonus` AE target & adjust summoning
  module/data/activity/base-activity.mjs
  module/documents/activity/summon.mjs
Labels: bug, system: summoning, system: enchantment

#4994 [#4819, #4993] Add activity macros, pass event to item macros
  dnd5e.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/npc-sheet-2.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/documents/macro.mjs
Labels: feature request, api, system: activities, system: macros
