Repository foundryvtt/dnd5e, pull requests merged in 2025-03, with the labels that each got.

#5347 Remove old item templates & config apps, move starting equipment
  module/applications/item/_module.mjs
  module/applications/item/config/starting-equipment-config.mjs
  module/applications/item/enchantment-config.mjs
  module/applications/item/item-sheet.mjs
  module/applications/item/summoning-config.mjs
  module/utils.mjs
  templates/items/background.hbs
  templates/items/class.hbs
  templates/items/consumable.hbs
  templates/items/container.hbs
  templates/items/equipment.hbs
  templates/items/feat.hbs
  templates/items/loot.hbs
  templates/items/parts/item-action.hbs
  templates/items/parts/item-activation.hbs
  templates/items/parts/item-advancement.hbs
  templates/items/parts/item-description.hbs
  templates/items/parts/item-mountable.hbs
  templates/items/parts/item-source.hbs
  templates/items/parts/item-spellcasting.hbs
  templates/items/race.hbs
  templates/items/spell.hbs
  templates/items/subclass.hbs
  templates/items/tool.hbs
  templates/items/weapon.hbs
Labels: api

#5349 [#5348] Fix custom elements in `ApplicationV2`
  module/applications/components/effects.mjs
  module/applications/components/inventory.mjs
  module/applications/components/item-list-controls.mjs
Labels: bug, compatibility

#5336 Fix onTokenHUDRender and onRenderActorDirectory for V13
  dnd5e.mjs
  module/applications/item/item-compendium.mjs
  module/documents/active-effect.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
Labels: bug, compatibility

#5267 [#5033] Add dark mode styling for embedded stat blocks
  less/v2/dark/journal.less
  less/v2/journal.less
Labels: bug, ui, system: enrichers

#5286 Allow special ToC sections to be seen in chapters that hide pages
  module/applications/journal/table-of-contents.mjs
  templates/journal/table-of-contents.hbs
Labels: system: journals

#5354 [#5275, #5319] Fix flat damage label, display scaled cantrips
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/data/activity/damage-data.mjs
  module/data/activity/heal-data.mjs
  module/data/activity/save-data.mjs
Labels: bug, ui, system: activities

#5227 [#4708] Redesign `AdvancementMigrationDialog` for V2 app & styles
  lang/en.json
  less/v1/advancement.less
  less/v2/advancement.less
  module/applications/advancement/advancement-migration-dialog.mjs
  module/applications/api/dialog.mjs
  module/applications/item/item-sheet.mjs
  templates/advancement/advancement-migration-dialog.hbs
  templates/shared/dialog-content.hbs
Labels: ui, system: advancement

#5365 [#5332] Migrate to core's `CompendiumArt` system
  dnd5e.mjs
  module/documents/actor/actor.mjs
  module/migration.mjs
  module/module-art.mjs
  system.json
Labels: api

#5239 [#3877] Redesign transformation dialog, change settings design
  dnd5e.mjs
  lang/en.json
  less/v2/apps.less
  less/v2/dark/apps.less
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/transform-dialog.mjs
  module/applications/settings/bastion-settings.mjs
  module/config.mjs
  module/data/_module.mjs
  module/data/settings/_module.mjs
  module/data/settings/bastion-setting.mjs
  module/data/settings/primary-party-setting.mjs
  module/data/settings/transformation-setting.mjs
  module/documents/actor/actor.mjs
  module/settings.mjs
  templates/apps/polymorph-prompt.hbs
  templates/apps/transform-details.hbs
  templates/apps/transform-presets.hbs
  templates/apps/transform-settings.hbs
Labels: ui, api, breaking, ux, system: transformation

#5263 [#3877, #5261] Rework `transformInto` using new settings object
  module/applications/actor/base-sheet.mjs
  module/config.mjs
  module/data/settings/transformation-setting.mjs
  module/documents/actor/actor.mjs
Labels: api, system: transformation

#5314 System Typography Generalization
  .gitignore
  less/dnd5e.less
  less/v2/apps.less
  less/v2/chat.less
  less/v2/dark/journal.less
  less/v2/dark/typography.less
  less/v2/journal.less
  less/v2/typography.less
  less/variables.less
Labels: ui, system: journals

#5260 [#5259] Add temp HP formula to transformation, replacing `addTemp`
  dnd5e.mjs
  lang/en.json
  module/applications/actor/transform-dialog.mjs
  module/config.mjs
  module/data/actor/templates/creature.mjs
  module/data/settings/transformation-setting.mjs
  module/documents/actor/actor.mjs
  templates/apps/transform-details.hbs
Labels: api, system: transformation

#5407 [#5087] Fix i18n for Turn End & Turn Start abbreviations
  lang/en.json
Labels: bug, localization

#5315 [#4059] Add `TransformActivity`
  icons/LICENSE
  icons/svg/activity/transform.svg
  lang/en.json
  module/applications/activity/_module.mjs
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/summon-sheet.mjs
  module/applications/activity/transform-sheet.mjs
  module/applications/activity/transform-usage-dialog.mjs
  module/applications/actor/transform-dialog.mjs
  module/config.mjs
  module/data/activity/_module.mjs
  module/data/activity/transform-data.mjs
  module/data/actor/npc.mjs
  module/data/settings/transformation-setting.mjs
  module/documents/activity/_module.mjs
  module/documents/activity/enchant.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/summon.mjs
  module/documents/activity/transform.mjs
  module/documents/actor/actor.mjs
  templates/activity/parts/transform-profiles.hbs
  templates/activity/parts/transform-settings.hbs
  templates/activity/transform-effect.hbs
  templates/activity/transform-usage-creation.hbs
  templates/shared/fields/fieldlist.hbs
Labels: ui, ux, system: activities, system: transformation

#5421 Revert "[#5332] Migrate to core's `CompendiumArt` system"
  dnd5e.mjs
  module/documents/actor/actor.mjs
  module/migration.mjs
  module/module-art.mjs
  system.json
Labels: bug

#5333 Adds common inline class styles for direct HTML formatting
  less/dnd5e.less
  less/v2/blocks.less
  less/v2/dark/typography.less
  less/v2/typography.less
  less/variables.less
Labels: ui, system: journals

#5420 Backport enchant/summons profile localization fixes in V13
  lang/en.json
  module/documents/activity/enchant.mjs
  module/documents/activity/summon.mjs
Labels: localization

#5399 Handle `5.0` deprecations including those for activities & rolling
  module/applications/actor/_module.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/sheet-flags.mjs
  module/applications/award.mjs
  module/applications/currency-manager.mjs
  module/applications/journal/journal-editor.mjs
  module/canvas/ability-template.mjs
  module/config.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/item/_module.mjs
  module/data/item/consumable.mjs
  module/data/item/equipment.mjs
  module/data/item/feat.mjs
  module/data/item/spell.mjs
  module/data/item/templates/action.mjs
  module/data/item/templates/activated-effect.mjs
  module/data/item/templates/activities.mjs
  module/data/item/tool.mjs
  module/data/item/weapon.mjs
  module/data/shared/uses-field.mjs
  module/dice/_module.mjs
  module/dice/basic-roll.mjs
  module/dice/d20-roll.mjs
  module/dice/damage-roll.mjs
  module/dice/dice.mjs
  module/documents/active-effect.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/enchant.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/summon.mjs
  module/documents/activity/utility.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  templates/apps/actor-flags.hbs
Labels: api

#5400 Remove V12-compatible code
  dnd5e.mjs
  lang/en.json
  less/v2/apps.less
  module/applications/actor/base-sheet.mjs
  module/applications/chat-log.mjs
  module/applications/combat/combat-tracker.mjs
  module/applications/components/inventory.mjs
  module/applications/context-menu.mjs
  module/applications/dice/roll-configuration-dialog.mjs
  module/applications/item/item-compendium.mjs
  module/applications/journal/class-page-sheet.mjs
  module/applications/journal/journal-sheet.mjs
  module/applications/journal/map-page-sheet.mjs
  module/applications/journal/rule-page-sheet.mjs
  module/applications/journal/spells-page-sheet.mjs
  module/applications/journal/table-of-contents.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/applications/settings/sidebar.mjs
  module/applications/sheet-config.mjs
  module/applications/tabs.mjs
  module/applications/token-config.mjs
  module/canvas/ability-template.mjs
  module/canvas/detection-modes/blindsight.mjs
  module/canvas/note.mjs
  module/canvas/token.mjs
  module/data/collection/items-collection.mjs
  module/documents/active-effect.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/enchant.mjs
  module/documents/activity/mixin.mjs
  module/documents/activity/summon.mjs
  module/documents/activity/transform.mjs
  module/documents/actor/actor.mjs
  module/documents/actor/bastion.mjs
  module/documents/advancement/advancement.mjs
  module/documents/advancement/scale-value.mjs
  module/documents/chat-message.mjs
  module/documents/item.mjs
  module/documents/token.mjs
  module/drag-drop.mjs
  module/parse-uuid.mjs
  module/settings.mjs
  module/utils.mjs
Labels: compatibility
