Repository foundryvtt/dnd5e, pull requests merged in 2025-02, with the labels that each got.

#4884 [#4787] More informative roll dialog titles
  lang/en.json
  module/applications/dice/skill-tool-configuration-dialog.mjs
  module/documents/activity/attack.mjs
  module/documents/activity/heal.mjs
  module/documents/activity/mixin.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
Labels: ui, system: dice

#5097 Fix more issues with SRD weapons
  packs/_source/items/weapon/berserker-handaxe.json
  packs/_source/items/weapon/dagger-of-venom.json
  packs/_source/items/weapon/dancing-greatsword.json
  packs/_source/items/weapon/defender-greatsword.json
  packs/_source/items/weapon/dragon-slayer-greatsword.json
  packs/_source/items/weapon/dragon-slayer-longsword.json
  packs/_source/items/weapon/dragon-slayer-rapier.json
  packs/_source/items/weapon/dragon-slayer-scimitar.json
  packs/_source/items/weapon/dragon-slayer-shortsword.json
  packs/_source/items/weapon/dwarven-thrower.json
  packs/_source/items/weapon/giant-slayer-battleaxe.json
  packs/_source/items/weapon/giant-slayer-greataxe.json
  packs/_source/items/weapon/giant-slayer-greatsword.json
  packs/_source/items/weapon/giant-slayer-handaxe.json
  packs/_source/items/weapon/giant-slayer-longsword.json
  packs/_source/items/weapon/giant-slayer-rapier.json
  packs/_source/items/weapon/giant-slayer-scimitar.json
  packs/_source/items/weapon/giant-slayer-shortsword.json
  packs/_source/items/weapon/greatsword-of-life-stealing.json
  packs/_source/items/weapon/greatsword-of-sharpness.json
  packs/_source/items/weapon/greatsword-of-wounding.json
  packs/_source/items/weapon/holy-avenger-greatsword.json
  packs/_source/items/weapon/holy-avenger-longsword.json
  packs/_source/items/weapon/holy-avenger-rapier.json
  packs/_source/items/weapon/holy-avenger-scimitar.json
  packs/_source/items/weapon/holy-avenger-shortsword.json
  packs/_source/items/weapon/javelin-of-lightning.json
  packs/_source/items/weapon/longsword-of-life-stealing.json
  packs/_source/items/weapon/longsword-of-sharpness.json
  packs/_source/items/weapon/longsword-of-wounding.json
  packs/_source/items/weapon/luck-blade-greatsword.json
  packs/_source/items/weapon/luck-blade-rapier.json
  packs/_source/items/weapon/luck-blade-scimitar.json
  packs/_source/items/weapon/luck-blade-shortsword.json
  packs/_source/items/weapon/mace-of-disruption.json
  packs/_source/items/weapon/mace-of-smiting.json
  packs/_source/items/weapon/mace-of-terror.json
  packs/_source/items/weapon/nine-lives-stealer-greatsword.json
  packs/_source/items/weapon/nine-lives-stealer-longsword.json
  packs/_source/items/weapon/nine-lives-stealer-rapier.json
  packs/_source/items/weapon/nine-lives-stealer-scimitar.json
  packs/_source/items/weapon/nine-lives-stealer-shortsword.json
  packs/_source/items/weapon/oathbow.json
  packs/_source/items/weapon/rapier-of-life-stealing.json
  packs/_source/items/weapon/rapier-of-wounding.json
  packs/_source/items/weapon/scimitar-of-life-stealing.json
  packs/_source/items/weapon/scimitar-of-sharpness.json
  packs/_source/items/weapon/scimitar-of-speed.json
  packs/_source/items/weapon/scimitar-of-wounding.json
  packs/_source/items/weapon/shortsword-of-life-stealing.json
  packs/_source/items/weapon/shortsword-of-wounding.json
  packs/_source/items/weapon/trident-of-fish-command.json
  packs/_source/items/weapon/vicious-handaxe.json
  packs/_source/items/weapon/vorpal-greatsword.json
  packs/_source/items/weapon/vorpal-longsword.json
  packs/_source/items/weapon/vorpal-scimitar.json
Labels: compendium content

#4984 [#4744] Add "Advance Bastion Turn" option to group long rest dialog
  module/applications/actor/rest/long-rest-dialog.mjs
  module/data/actor/group.mjs
  module/documents/actor/actor.mjs
Labels: system: bastions, system: rests

#5094 [#5093] Adjust scaling label for cantrips
  lang/en.json
  module/applications/activity/activity-sheet.mjs
  module/applications/activity/heal-sheet.mjs
  module/config.mjs
Labels: ui, ux

#4998 [#3798, #4842] Add legendary action description to stat blocks
  lang/en.json
  less/v2/journal.less
  module/data/actor/npc.mjs
  templates/actors/embeds/npc-embed.hbs
Labels: feature request, system: enrichers

#5084 Adjust sourced items on actors to use remapped UUIDs
  dnd5e.mjs
  module/applications/journal/spells-page-sheet.mjs
  module/documents/actor/actor.mjs
  module/parse-uuid.mjs
Labels: compatibility

#5008 [#4992] Store roll type (attack, skill, ability, save, damage) in roll options
  module/dice/basic-roll.mjs
Labels: api

#5015 Recognize when last attack is critical and set damage & default button accordingly
  module/documents/activity/attack.mjs
Labels: ux, system: activities

#5007 [#4830] Only defer to item abilities if attack activity matches attack type
  module/data/activity/attack-data.mjs
Labels: bug, system: advancement

#5005 [#3751] Add ability to automatically manually sort compendiums
  dnd5e.mjs
  module/applications/advancement/advancement-manager.mjs
  module/migration.mjs
  module/module-registration.mjs
  module/utils.mjs
  system.json
Labels: feature request, api

#5018 Allow for arbitrary bonus to save DC on activities.
  module/data/activity/save-data.mjs
  module/documents/active-effect.mjs
Labels: feature request

#4545 [#2449, #2912] Re-design special traits config as actor sheet tab
  lang/en.json
  less/v2/actors.less
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/npc-sheet-2.mjs
  module/applications/actor/sheet-flags.mjs
  module/applications/actor/sheet-v2-mixin.mjs
  module/applications/components/effects.mjs
  module/applications/components/inventory.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/data/actor/character.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/creature.mjs
  module/documents/activity/mixin.mjs
  module/utils.mjs
  templates/actors/character-sheet-2.hbs
  templates/actors/npc-sheet-2.hbs
  templates/actors/tabs/creature-special-traits.hbs
  templates/apps/actor-flags.hbs
Labels: ui

#5103 [#5102] Add combat settings application with initiative & criticals
  lang/en.json
  module/applications/settings/combat-settings.mjs
  module/settings.mjs
  templates/settings/base-config.hbs
Labels: ui

#5079 [#5074] Rework `JournalEditor` & `SpellsUnlinkedConfig` for V2
  less/v1/journal.less
  less/v2/journal.less
  module/applications/journal/class-page-sheet.mjs
  module/applications/journal/journal-editor.mjs
  module/applications/journal/spells-page-sheet.mjs
  module/applications/journal/spells-unlinked-config.mjs
  module/data/journal/spells.mjs
  module/data/shared/source-field.mjs
  templates/journal/journal-editor.hbs
  templates/journal/page-spell-list-unlinked-config.hbs
  templates/journal/page-spell-list-unlinked-source.hbs
  templates/journal/page-spell-list-unlinked-spell.hbs
Labels: ui

#5021 [#4802] Add "display chat card" button to inventory item context menu
  lang/en.json
  module/applications/components/inventory.mjs
  module/documents/chat-message.mjs
Labels: feature request

#4544 [#4541] Option to auto-roll NPC HP
  lang/en.json
  module/applications/settings/combat-settings.mjs
  module/documents/token.mjs
  module/settings.mjs
Labels: feature request

#5111 [#5074] Adjust `CompendiumBrowser` to inherit from `Application5e`
  module/applications/compendium-browser.mjs
Labels: ui

#5110 [#5074] Convert `PropertyAttribution` to `ApplicationV2`
  module/applications/api/application-v2-mixin.mjs
  module/applications/property-attribution.mjs
Labels: ui

#5112 [#5102] Add variant rules settings application
  lang/en.json
  module/applications/settings/variant-rules-settings.mjs
  module/settings.mjs
Labels: ui

#4886 Extend rider conditions to generic effects
  dnd5e.mjs
  lang/en.json
  module/documents/active-effect.mjs
Labels: feature request, system: active effects

#5113 Suppress some V13 warnings and add alternate paths to others
  dnd5e.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/components/effects.mjs
  module/applications/components/inventory.mjs
  module/applications/dice/roll-configuration-dialog.mjs
  module/applications/item/item-sheet-2.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/documents/activity/mixin.mjs
  module/documents/advancement/advancement.mjs
Labels: compatibility

#4281 Update Modifying-Your-Game-with-Scripts.md
  wiki/Modifying-Your-Game-with-Scripts.md
Labels: documentation

#4845 Fix warnings migrations
  module/data/item/templates/activities.mjs
Labels: bug

#5116 [#4628] Preserve initial roll configuration for rebuilding.
  module/dice/basic-roll.mjs
  module/documents/activity/attack.mjs
  module/documents/actor/actor.mjs
Labels: bug, system: dice

#5004 [#5003] Add ability attack, spell attack, & spell ability labels
  dnd5e.mjs
  module/applications/actor/base-sheet.mjs
  module/applications/actor/npc-sheet-2.mjs
  module/config.mjs
  module/data/actor/npc.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/templates/common.mjs
  module/documents/activity/summon.mjs
  module/documents/actor/actor.mjs
  module/documents/item.mjs
  module/utils.mjs
  templates/actors/character-sheet.hbs
  templates/actors/parts/actor-spellbook.hbs
  templates/actors/tabs/creature-spells.hbs
Labels: feature request, api

#5115 [#4799] Add setting for automatically recharging NPC abilities
  lang/en.json
  module/applications/components/inventory.mjs
  module/applications/settings/combat-settings.mjs
  module/data/chat-message/fields/deltas-field.mjs
  module/data/chat-message/rest-message-data.mjs
  module/data/chat-message/turn-message-data.mjs
  module/data/item/templates/activities.mjs
  module/data/shared/uses-field.mjs
  module/documents/combatant.mjs
  module/settings.mjs
Labels: feature request, ux, system: combat

#5118 [#5117] Display rest/turn rolls inline on chat cards with deltas
  less/v2/chat.less
  module/data/activity/fields/consumption-targets-field.mjs
  module/data/chat-message/fields/deltas-field.mjs
  module/data/shared/uses-field.mjs
  templates/chat/parts/card-deltas.hbs
Labels: feature request, system: rests, system: combat

#5126 [#5125] Add habitat filter for Compendium Browser
  module/data/actor/npc.mjs
  module/filter.mjs
Labels: feature request, system: compendium browser

#5131 [#4665] Add compendium browser to select feat in ASI advancement
  lang/en.json
  less/v1/advancement.less
  less/v2/advancement.less
  module/applications/advancement/ability-score-improvement-flow.mjs
  module/applications/advancement/subclass-flow.mjs
  templates/advancement/ability-score-improvement-flow.hbs
  templates/advancement/subclass-flow.hbs
Labels: ux, system: advancement, system: compendium browser

#5136 Update tools and activation types for changes
  wiki/Modifying-Your-Game-with-Scripts.md
Labels: documentation

#5148 Fix nested keys values retrieving
  module/applications/actor/sheet-v2-mixin.mjs
Labels: bug, api

#5161 Avoid crash when drag-dropping facility to low-level actor
  module/data/item/facility.mjs
Labels: bug

#5162 Fix incorrect key use for StringField character flags
  module/applications/actor/sheet-v2-mixin.mjs
Labels: bug

#5163 Make new rider status dropdown's insertion more resilient to potential AE Config modifications
  module/documents/active-effect.mjs
Labels: bug

#5166 Add link to embedded actor if `cite` is set, use label as name
  less/v2/journal.less
  module/data/actor/npc.mjs
  templates/actors/embeds/npc-embed.hbs
Labels: system: enrichers

#5134 [#3068, #5104] Add ToC guide, enchantment changes, pack sorting
  wiki/Enchantment.md
  wiki/Home.md
  wiki/Module-Registration.md
  wiki/Table-of-Contents.md
  wiki/images/journal/table-of-contents-complete.jpg
  wiki/images/journal/table-of-contents-empty.jpg
Labels: documentation

#5159 Fix damage shortcut key bug introduced by #5015
  lang/en.json
  module/dice/damage-roll.mjs
Labels: bug, system: dice

#5206 Update Roll Formulas for 4.3
  wiki/Roll-Formulas.md
Labels: documentation

#5188 Ensure explicit false return for activity consumption hooks
  module/documents/activity/mixin.mjs
Labels: bug, system: activities

#5195 [#5194] Fix melee and natural weapons missing reach tags.
  module/data/activity/attack-data.mjs
  module/data/activity/base-activity.mjs
  module/data/item/weapon.mjs
Labels: bug

#5207 [#5196] Adds handling to `replaceFormulaData` to parse shims
  module/data/actor/templates/common.mjs
  module/dice/basic-roll.mjs
Labels: bug, system: dice

#5216 [#5215] Fix failed data preparation when sourceId compendium is no longer available.
  module/parse-uuid.mjs
Labels: bug

#5221 [#5220] Fix displaying cached spells on actors in compendiums
  module/data/activity/cast-data.mjs
  module/data/item/spell.mjs
Labels: bug, system: activities

#5274 HealActivity scaling fix
  module/data/activity/heal-data.mjs
Labels: bug, system: dice
