Repository foundryvtt/dnd5e, pull requests merged in 2025-08, with the labels that each got.

#5917 [#5914] Update item-sheet maxLevel check from `!configMode` to `this.item.parent`
  module/applications/item/item-sheet.mjs
Labels: bug, system: advancement, priority: high

#5930 Apply travel pace modifiers to skill roll modes when rolled from the group sheet.
  module/applications/actor/group-sheet.mjs
  module/config.mjs
  module/data/actor/group.mjs
  module/data/fields/advantage-mode-field.mjs
  module/data/shared/movement-field.mjs
  module/documents/actor/actor.mjs
Labels: system: dice

#5935 [#2735] Have natural weapons use the highest of str or dex by default.
  module/data/activity/attack-data.mjs
  module/data/item/weapon.mjs
Labels: bug, compendium content: 2014, breaking, compendium content: 2024

#5945 [#5944] Cached spell `uses` reference actual consumption target when necessary
  module/applications/actor/api/base-actor-sheet.mjs
Labels: system: actor sheets

#4805 [#4804] Add help icon and tooltip to AE Attribute Key header
  lang/en.json
  less/v2/apps.less
  module/documents/active-effect.mjs
Labels: ui, system: active effects, strategic, priority: low

#5948 [#5429] Use transformation source to-hit bonus when transformed.
  module/documents/actor/actor.mjs
Labels: bug, system: transformation

#5949 [#5419] When keep HP or spells transformation options are set, retain these values when reverting form.
  module/documents/actor/actor.mjs
Labels: system: transformation

#5893 Update Advancement pages on Wiki for 5.1 changes
  wiki/Advancement-Type-Ability-Score-Improvement.md
  wiki/Advancement-Type-Hit-Points.md
  wiki/Advancement-Type-Item-Choice.md
  wiki/Advancement-Type-Item-Grant.md
  wiki/Advancement-Type-Scale-Value.md
  wiki/Advancement-Type-Size.md
  wiki/Advancement-Type-Subclass.md
  wiki/Advancement-Type-Trait.md
  wiki/Advancement.md
  wiki/images/advancement/asi-configuration-class.jpg
  wiki/images/advancement/asi-configuration-race.jpg
  wiki/images/advancement/asi-flow-epic-boon.jpg
  wiki/images/advancement/item-choice-compendium-browser.jpg
  wiki/images/advancement/item-choice-flow.jpg
  wiki/images/advancement/item-grant-configuration-spells.jpg
Labels: documentation

#5986 Stop movement prior to a blocking token, rather than fully preventing the movement
  module/canvas/token.mjs
Labels: system: canvas

#5996 Item Choice Flow: Any Available Level option is not working correctly
  module/applications/advancement/item-choice-flow.mjs
Labels: bug, system: advancement

#6000 [#5999] Linked actor summon fix
  module/documents/actor/actor.mjs
Labels: system: summoning

#6012 [#6004] [#6006] [#6007] Improve prerequisite management in ItemChoiceFlow.
  module/applications/advancement/item-choice-flow.mjs
  module/data/item/feat.mjs
Labels: bug, system: advancement

#6054 Fix crawling cost in difficult terrain
  module/documents/token.mjs
Labels: bug, system: canvas

#6073 [#6078] Use source name in edit mode on character sheets
  templates/actors/character-header.hbs
Labels: system: actor sheets

#6081 [#6080] Allow `exhaustionDelta` in short rest
  module/documents/actor/actor.mjs
Labels: bug, system: rests

#6066 Don't consider token-blocking for resize "movements"
  module/canvas/token.mjs
Labels: bug, system: canvas

#6095 Add missing file path fields to manifest
  system.json
Labels: priority: high
