Repository foundryvtt/dnd5e, pull requests merged in 2025-04, with the labels that each got.

#5389 [#5372] Convert NPC sheet to ApplicationV2
  .gitignore
  dnd5e.mjs
  less/elements.less
  less/v2/actors.less
  less/v2/apps.less
  less/v2/dark/apps.less
  less/v2/dark/npc.less
  less/v2/forms.less
  less/v2/inventory.less
  less/v2/npc.less
  less/v2/sheets.less
  less/variables.less
  module/applications/actor/_module.mjs
  module/applications/actor/api/base-actor-sheet.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/deprecated/base-config.mjs
  module/applications/actor/deprecated/base-sheet.mjs
  module/applications/actor/deprecated/npc-sheet.mjs
  module/applications/actor/deprecated/sheet-mixin.mjs
  module/applications/actor/deprecated/sheet-v2-mixin.mjs
  module/applications/actor/group-sheet.mjs
  module/applications/actor/npc-sheet-2.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/actor/vehicle-sheet.mjs
  module/applications/advancement/advancement-config-v2.mjs
  module/applications/api/primary-sheet-mixin.mjs
  module/applications/components/item-list-controls.mjs
  module/applications/item/config/starting-equipment-config.mjs
  module/applications/item/item-sheet.mjs
  module/applications/journal/table-of-contents.mjs
  module/applications/mixins/drag-drop-mixin.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/applications/shared/_module.mjs
  module/applications/shared/source-config.mjs
  module/applications/source-config.mjs
  module/data/abstract.mjs
  module/data/item/spell.mjs
  module/utils.mjs
  package.json
  system.json
  templates/activity/activity-row-summary.hbs
  templates/actors/npc-header.hbs
  templates/actors/npc-sheet-2.hbs
  templates/actors/npc-sheet.hbs
  templates/actors/npc-sidebar-collapser.hbs
  templates/actors/npc-sidebar.hbs
  templates/actors/parts/actor-classes.hbs
  templates/actors/parts/actor-trait-pills.hbs
  templates/actors/parts/actor-warnings-dialog.hbs
  templates/actors/tabs/actor-effects.hbs
  templates/actors/tabs/actor-inventory.hbs
  templates/actors/tabs/creature-features.hbs
  templates/actors/tabs/creature-special-traits.hbs
  templates/actors/tabs/creature-spells.hbs
  templates/actors/tabs/npc-biography.hbs
  templates/shared/active-effects2.hbs
  templates/shared/inventory2.hbs
  templates/shared/sidebar-tabs.hbs
Labels: epic, ui, breaking, ux

#5390 [#5372] Convert Character sheet to ApplicationV2
  dnd5e.mjs
  less/v2/actors.less
  less/v2/apps.less
  less/v2/character.less
  less/v2/dark/character.less
  less/variables.less
  module/applications/actor/_module.mjs
  module/applications/actor/api/base-actor-sheet.mjs
  module/applications/actor/character-sheet-2.mjs
  module/applications/actor/character-sheet.mjs
  module/applications/actor/deprecated/character-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/applications/item/item-sheet.mjs
  templates/actors/character-ability-scores.hbs
  templates/actors/character-header.hbs
  templates/actors/character-sheet-2.hbs
  templates/actors/character-sheet.hbs
  templates/actors/character-sidebar.hbs
  templates/actors/tabs/character-bastion.hbs
  templates/actors/tabs/character-biography.hbs
  templates/actors/tabs/character-details.hbs
  templates/actors/tabs/creature-spells.hbs
Labels: epic, ui, breaking, ux

#5140 Swap from legacy to proper enchant keys for summon item changes
  module/documents/activity/summon.mjs
Labels: system: summoning, system: enchantment

#5041 [#5037] Add units display to ranged communication pill
  module/applications/actor/sheet-v2-mixin.mjs
Labels: ui, localization

#5356 Updated/added new tokens from the FA 60-65 packs
  json/fa-token-mapping.json
  tokens/beast/Boar.webp
  tokens/beast/Deer.webp
  tokens/beast/DraftHorse.webp
  tokens/beast/Elk.webp
  tokens/beast/Frog.webp
  tokens/beast/GiantPoisonousSnake.webp
  tokens/beast/Mastiff.webp
  tokens/beast/Pony.webp
  tokens/beast/RidingHorse.webp
  tokens/beast/Wolf.webp
  tokens/construct/Homonculus.webp
  tokens/dragon/GreenDragonAncient.webp
  tokens/dragon/WhiteDragonAncient.webp
  tokens/fiend/Nightmare.webp
  tokens/monstrosity/WinterWolf.webp
  tokens/monstrosity/Worg.webp
Labels: compendium content

#5269 Pass number of concentration effects to statuses.concentrating
  module/documents/actor/actor.mjs
Labels: feature request, api

#5430 Remove V12 DragDrop handling
  dnd5e.mjs
  module/applications/actor/deprecated/sheet-mixin.mjs
  module/applications/api/primary-sheet-mixin.mjs
  module/applications/item/item-compendium.mjs
  module/applications/item/item-directory.mjs
  module/applications/mixins/drag-drop-mixin.mjs
  module/applications/mixins/sheet-v2-mixin.mjs
  module/drag-drop.mjs
Labels: compatibility

#5451 [#5450] Fix for defaulting to no mastery under some circumstances
  module/data/item/weapon.mjs
Labels: bug

#5494 Miscellaneous SRD upgrades
  packs/_source/items/trinket/talisman-of-the-sphere.yml
  packs/_source/monsterfeatures/legendary-resistance.yml
  packs/_source/monsters/celestial/couatl.yml
  packs/_source/monsters/fiend/succubus-incubus.yml
  packs/_source/monsters/humanoid/assassin.yml
  packs/_source/monsters/humanoid/berserker.yml
  packs/_source/monsters/humanoid/druid.yml
  packs/_source/monsters/humanoid/gladiator.yml
  packs/_source/monsters/humanoid/mage.yml
  packs/_source/monsters/humanoid/noble.yml
  packs/_source/monsters/humanoid/priest.yml
  packs/_source/monsters/humanoid/scout.yml
  packs/_source/monsters/humanoid/weretiger.yml
Labels: compendium content

#5358 Add DamageTraitField and SimpleTraitField exports to module
  module/data/actor/_module.mjs
Labels: api

#5512 [#5510] Add SRD 5.2 to source books, adjust book selection behavior
  lang/en.json
  module/data/shared/source-field.mjs
  system.json
Labels: api, compendium content: 2024

#5505 [#5500] Fix inventory element for legacy sheets
  module/applications/actor/vehicle-sheet.mjs
  module/applications/components/inventory.mjs
  templates/actors/parts/actor-features.hbs
  templates/actors/parts/actor-spellbook.hbs
  templates/shared/inventory.hbs
Labels: compatibility, system: actor sheets

#5351 [#5297] Adjust order of operations on status effect config, and migrate properties to use `name` and `img` everywhere
  dnd5e.mjs
  module/applications/actor/api/base-actor-sheet.mjs
  module/applications/actor/deprecated/sheet-v2-mixin.mjs
  module/config.mjs
  module/documents/active-effect.mjs
  templates/shared/active-effects2.hbs
Labels: api, system: active effects

#5520 [#5510] Add system support for modern/legacy references
  dnd5e.mjs
  module/config-legacy.mjs
  module/config.mjs
  module/enrichers.mjs
  module/settings.mjs
Labels: compendium content: 2014, api, compendium content: 2024

#5524 [#5510] Add license information for SRD 5.2
  README.md
  dnd5e.mjs
Labels: compendium content: 2024

#5531 Update Rings of Resistance
  packs/_source/items/ring/ring-of-acid-resistance.yml
  packs/_source/items/ring/ring-of-cold-resistance.yml
  packs/_source/items/ring/ring-of-fire-resistance.yml
  packs/_source/items/ring/ring-of-force-resistance.yml
  packs/_source/items/ring/ring-of-lightning-resistance.yml
  packs/_source/items/ring/ring-of-necrotic-resistance.yml
  packs/_source/items/ring/ring-of-poison-resistance.yml
  packs/_source/items/ring/ring-of-psychic-resistance.yml
  packs/_source/items/ring/ring-of-radiant-resistance.yml
  packs/_source/items/ring/ring-of-thunder-resistance.yml
Labels: compendium content: 2014

#5532 More legacy SRD updates: Belts (and an amulet)
  packs/_source/items/equipment/amulet-of-health.yml
  packs/_source/items/equipment/belt-of-cloud-giant-strength.yml
  packs/_source/items/equipment/belt-of-dwarvenkind.yml
  packs/_source/items/equipment/belt-of-fire-giant-strength.yml
  packs/_source/items/equipment/belt-of-frost-giant-strength.yml
  packs/_source/items/equipment/belt-of-hill-giant-strength.yml
  packs/_source/items/equipment/belt-of-stone-giant-strength.yml
  packs/_source/items/equipment/belt-of-storm-giant-strength.yml
Labels: compendium content: 2014

#5534 SRD 5.1: Wands of the War Mage +1, +2, +3
  packs/_source/items/wand/wand-of-the-war-mage-1.yml
  packs/_source/items/wand/wand-of-the-war-mage-2.yml
  packs/_source/items/wand/wand-of-the-war-mage-3.yml
Labels: compendium content: 2014

#5529 [#5508] Fix transforming unlinked actors in V13
  module/documents/actor/actor.mjs
Labels: compatibility

#5439 [#5392] Fix `requiresReload` Option for Settings in D&D 5e System
  module/applications/settings/base-settings.mjs
Labels: bug

#5540 Fix bonus field labels in special traits tab in v13.
  module/applications/actor/sheet-v2-mixin.mjs
  module/data/actor/templates/creature.mjs
Labels: bug

#5543 Add Free Rules integration to build script
  .github/workflows/release.yml
  package-lock.json
  utils/integrate/action.yml
Labels: tooling, compendium content: 2024

#5542 Add journal navigation system from premium content to system sheets
  lang/en.json
  less/v2/journal.less
  module/applications/journal/journal-sheet.mjs
Labels: ux, system: journals

#5504 [#5503] Add `dnd5e.postBuildRollConfig` hook for skipped rolls
  module/applications/dice/roll-configuration-dialog.mjs
  module/dice/basic-roll.mjs
Labels: api

#5557 Fix errors with certain migrations removing items from actors
  module/migration.mjs
Labels: migration

#5242 Update FAQ with additional rules version changes
  wiki/FAQ.md
  wiki/images/settings/npc-rules-version.jpg
Labels: documentation

#5546 [#5544] Update module art guide to reflect move to core's system
  wiki/Dynamic-Module-Art.md
Labels: documentation

#5545 [#5544] Add docs for Transformation & Transform activity
  wiki/Activity-Type-Transform.md
  wiki/FAQ.md
  wiki/Home.md
  wiki/Transformation.md
  wiki/images/transformation/transform-chat-message.jpg
  wiki/images/transformation/transform-cr-prompt.jpg
  wiki/images/transformation/transform-profiles.jpg
  wiki/images/transformation/transform-prompt.jpg
  wiki/images/transformation/transform-setings.jpg
  wiki/images/transformation/transformation-dialog.jpg
  wiki/images/transformation/transformation-permissions.jpg
Labels: documentation

#5564 [#5241] Update wiki screenshots to reflect current system UI
  wiki/Advancement-Type-Item-Grant.md
  wiki/images/activities/attack-chat-dialog.jpg
  wiki/images/advancement/asi-configuration-class.jpg
  wiki/images/advancement/asi-configuration-race.jpg
  wiki/images/advancement/asi-flow-class.jpg
  wiki/images/advancement/asi-flow-modern.jpg
  wiki/images/advancement/subclass-flow-initial.jpg
  wiki/images/advancement/subclass-flow-selected.jpg
  wiki/images/advancement/trait-flow-choices.jpg
  wiki/images/advancement/trait-flow-grants.jpg
  wiki/images/advancement/trait-flow.jpg
  wiki/images/journal/pages-spell-list.jpg
Labels: documentation

#5563 Add `getRollData()` fallbacks to every enricher
  module/enrichers.mjs
Labels: api, system: enrichers
