Repository foundryvtt/dnd5e, pull requests merged in 2025-06, with the labels that each got.

#5621 Implement region behavior for rotating a part of the map
  dnd5e.mjs
  lang/en.json
  less/dnd5e.less
  less/v2/region-behaviors.less
  module/applications/_module.mjs
  module/applications/region-behavior/_module.mjs
  module/applications/region-behavior/rotate-area-config.mjs
  module/data/_module.mjs
  module/data/region-behavior/_module.mjs
  module/data/region-behavior/rotate-area.mjs
  module/utils.mjs
  system.json
  templates/region-behaviors/rotate-area-config.hbs
  templates/shared/fields/fieldlist.hbs
  templates/shared/fields/formlist.hbs
Labels: system: region behaviors

#5794 [#5507] Include `isDelta` in passed `options `for `dnd5e.preApplyDamage` and `dnd5e.applyDamage` hooks
  module/applications/components/damage-application.mjs
  module/documents/actor/actor.mjs
  module/documents/chat-message.mjs
Labels: api, uncontroversial, priority: medium

#5789 [#5744] If `type` is provided to `Item5e.createDialog`, pre-select that type in the creation dialog
  module/documents/item.mjs
  templates/apps/document-create.hbs
Labels: api, ux, uncontroversial, priority: medium

#5748 [#5129] Add setting to disallow resting from individual sheets
  lang/en.json
  less/v2/npc.less
  module/applications/actor/character-sheet.mjs
  module/applications/actor/npc-sheet.mjs
  module/documents/actor/actor.mjs
  module/settings.mjs
  templates/actors/character-header.hbs
  templates/actors/npc-header.hbs
Labels: system: rests, system: actor sheets, priority: high

#5791 [#5680] Ensure `config.isCritical` matches `isCritical`s of roll options for damage rolls
  module/applications/dice/damage-configuration-dialog.mjs
  module/dice/damage-roll.mjs
Labels: api, system: dice, uncontroversial, priority: medium

#5454 [#5338] Add modifier combinations for forcing advantage mode
  module/dice/d20-roll.mjs
Labels: accessibility, priority: high

#5418 [#5415] Maintain favorites on transformed actors
  module/documents/actor/actor.mjs
Labels: system: transformation, priority: high

#5417 [#5108] Preserve hidden state of token across transformation
  module/documents/actor/actor.mjs
Labels: system: transformation, priority: high

#5453 [#5172] Apply disadvantage based on certain conditions
  module/config.mjs
  module/data/actor/templates/attributes.mjs
  module/data/actor/templates/common.mjs
Labels: system: dice, priority: high

#5414 [#5410] Add minimum armor class formula during transformation
  lang/en.json
  module/applications/actor/transform-dialog.mjs
  module/config.mjs
  module/data/settings/transformation-setting.mjs
  module/documents/actor/actor.mjs
Labels: api, system: transformation, priority: high
